import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { RenderedFile } from "../fields";
import { collectTxtPaths, normalizeVersion, unwrap, type TreeNode } from "../utils";
import { processFileForVersion } from "./process-file";
import type { ReviewEntry, RuntimeContext } from "./types";

function renderVersionHeader(shortVersion: string, relativePaths: readonly string[]): string {
  const fileList = relativePaths.map((filePath) => `//   - ${filePath}`).join("\n");
  return `// This file is generated by scripts/codegen/generate-fields.ts. Do not edit directly.
// Unicode Version: ${shortVersion}
// Generated At: ${new Date().toISOString()}
// Files: ${relativePaths.length}
${fileList}

`;
}

export async function processVersion(inputVersion: string, runtime: RuntimeContext) {
  const { full, short } = normalizeVersion(inputVersion);
  console.log(`[v${short}] fetching file tree`);

  const tree = await runtime.fetchLimit.run(() => unwrap(runtime.client.versions.getFileTree(full)));
  const relativePaths = collectTxtPaths(tree as readonly TreeNode[]).toSorted((a, b) => a.localeCompare(b));
  const workerCount = Math.min(Math.max(relativePaths.length, 1), runtime.fileTaskConcurrency);
  console.log(`[v${short}] ${relativePaths.length} files (workers=${workerCount})`);

  const renderedByIndex: Array<RenderedFile | undefined> = new Array(relativePaths.length);
  const reviewByIndex: Array<ReviewEntry | undefined> = new Array(relativePaths.length);

  async function runWorker(workerIndex: number) {
    for (let index = workerIndex; index < relativePaths.length; index += workerCount) {
      const relPath = relativePaths[index]!;
      try {
        const processed = await processFileForVersion(full, short, relPath, runtime);
        renderedByIndex[index] = processed.renderedFile;
        reviewByIndex[index] = processed.reviewEntry;
      } catch (error) {
        console.error(`[v${short}] failed ${relPath}: ${String(error)}`);
      }
    }
  }

  await Promise.all(Array.from({ length: workerCount }, (_, workerIndex) => runWorker(workerIndex)));

  const outPath = join(runtime.outputDir, `v${short}.ts`);
  const chunks: string[] = [renderVersionHeader(short, relativePaths)];
  for (const rendered of renderedByIndex) {
    if (rendered == null) continue;
    chunks.push(`// #region ${rendered.relPath}\n${rendered.code}\n// #endregion\n\n`);
  }
  const bundled = chunks.join("");
  await writeFile(outPath, bundled, "utf-8");
  console.log(`[v${short}] wrote ${outPath}`);

  const reviewEntries = reviewByIndex.filter((entry): entry is ReviewEntry => entry != null);
  reviewEntries.sort((a, b) => a.confidence - b.confidence);

  const reviewPath = join(runtime.outputDir, `v${short}.review.json`);
  await writeFile(reviewPath, `${JSON.stringify(reviewEntries, null, 2)}\n`, "utf-8");
  const lowConfidenceCount = reviewEntries.filter((entry) => entry.confidence < runtime.confidenceThreshold).length;
  console.log(`[v${short}] wrote ${reviewPath} (${lowConfidenceCount} low-confidence of ${reviewEntries.length})`);
}
