import { mkdir, rename, rm, rmdir, writeFile } from "node:fs/promises";
import { basename, dirname, join } from "node:path";

import { processFileForVersion } from "./process-file";
import type { ProcessVersionOptions, ReviewEntry } from "./types";
import { collectTxtPaths, normalizeVersion, type TreeNode } from "./utils";

const FILE_WORKERS = 8;
const RESERVED_MODULE_BASENAMES = new Set(["index"]);

function renderVersionIndex(
  shortVersion: string,
  relativePaths: readonly string[],
  exportModulePaths: readonly string[],
): string {
  const fileList = relativePaths.map((filePath) => `//   - ${filePath}`).join("\n");
  const exports = exportModulePaths
    .map((modulePath) => `export * from "./${modulePath}";`)
    .join("\n");
  return `// This file is generated by scripts/codegen/generate-fields.ts. Do not edit directly.
// Unicode Version: ${shortVersion}
// Files: ${relativePaths.length}
${fileList}

${exports}
`;
}

function toGeneratedModulePath(relPath: string): string {
  const tsPath = relPath.replace(/\.txt$/i, ".ts");
  const moduleName = basename(tsPath, ".ts");
  if (!RESERVED_MODULE_BASENAMES.has(moduleName.toLowerCase())) {
    return tsPath;
  }
  return join(dirname(tsPath), `_${moduleName}.ts`);
}

export async function processVersion(inputVersion: string, options: ProcessVersionOptions) {
  const { full, short } = normalizeVersion(inputVersion);
  console.log(`[v${short}] fetching file tree`);

  const tree = await options.fetchFileTree(full);
  const relativePaths = collectTxtPaths(tree as readonly TreeNode[]).toSorted((a, b) =>
    a.localeCompare(b),
  );
  const workerCount = Math.min(Math.max(relativePaths.length, 1), FILE_WORKERS);
  console.log(`[v${short}] ${relativePaths.length} files (workers=${workerCount})`);

  const versionDir = join(options.outputDir, `v${short}`);
  const tempRootDir = join(options.outputDir, "..", ".codegen-tmp");
  const tempVersionDir = join(tempRootDir, `v${short}`);
  const legacyOutPath = join(options.outputDir, `v${short}.ts`);
  await rm(tempVersionDir, { recursive: true, force: true });
  await mkdir(tempVersionDir, { recursive: true });

  const moduleByIndex: Array<string | undefined> = new Array(relativePaths.length);
  const reviewByIndex: Array<ReviewEntry | undefined> = new Array(relativePaths.length);
  const failures: string[] = [];

  async function runWorker(workerIndex: number) {
    for (let index = workerIndex; index < relativePaths.length; index += workerCount) {
      const relPath = relativePaths[index]!;
      try {
        const processed = await processFileForVersion(full, short, relPath, options);
        const relativeOutPath = toGeneratedModulePath(relPath);
        const absoluteOutPath = join(tempVersionDir, relativeOutPath);
        await mkdir(dirname(absoluteOutPath), { recursive: true });
        await writeFile(absoluteOutPath, processed.renderedFile.code, "utf-8");
        moduleByIndex[index] = relativeOutPath.replace(/\.ts$/i, "").replace(/\\/g, "/");
        reviewByIndex[index] = processed.reviewEntry;
      } catch (error) {
        failures.push(`${relPath}: ${String(error)}`);
        console.error(`[v${short}] failed ${relPath}: ${String(error)}`);
      }
    }
  }

  await Promise.all(
    Array.from({ length: workerCount }, (_, workerIndex) => runWorker(workerIndex)),
  );

  if (failures.length > 0) {
    await rm(tempVersionDir, { recursive: true, force: true });
    await rmdir(tempRootDir).catch((error: NodeJS.ErrnoException) => {
      if (error.code !== "ENOENT" && error.code !== "ENOTEMPTY") throw error;
    });
    throw new Error(
      `[v${short}] failed ${failures.length}/${relativePaths.length} files; kept previous generated output\n${failures.join("\n")}`,
    );
  }

  const exportModulePaths = moduleByIndex.filter(
    (modulePath): modulePath is string => modulePath != null,
  );
  const indexPath = join(tempVersionDir, "index.ts");
  await writeFile(indexPath, renderVersionIndex(short, relativePaths, exportModulePaths), "utf-8");
  await rm(versionDir, { recursive: true, force: true });
  await rename(tempVersionDir, versionDir);
  await rmdir(tempRootDir).catch((error: NodeJS.ErrnoException) => {
    if (error.code !== "ENOENT" && error.code !== "ENOTEMPTY") throw error;
  });
  await rm(legacyOutPath, { force: true });
  console.log(
    `[v${short}] wrote ${join(versionDir, "index.ts")} (${exportModulePaths.length} modules)`,
  );

  const reviewEntries = reviewByIndex.filter((entry): entry is ReviewEntry => entry != null);
  reviewEntries.sort((a, b) => a.confidence - b.confidence);

  const reviewPath = join(options.outputDir, `v${short}.review.json`);
  await writeFile(reviewPath, `${JSON.stringify(reviewEntries, null, 2)}\n`, "utf-8");
  const lowConfidenceCount = reviewEntries.filter(
    (entry) => entry.confidence < options.confidenceThreshold,
  ).length;
  console.log(
    `[v${short}] wrote ${reviewPath} (${lowConfidenceCount} low-confidence of ${reviewEntries.length})`,
  );
}
