// This file is generated by scripts/codegen/generate-fields.ts. Do not edit directly.
// Unicode Version: 10
// Files: 32
//   - ArabicShaping.txt
//   - BidiBrackets.txt
//   - BidiMirroring.txt
//   - Blocks.txt
//   - CJKRadicals.txt
//   - CaseFolding.txt
//   - CompositionExclusions.txt
//   - DerivedAge.txt
//   - DerivedCoreProperties.txt
//   - DerivedNormalizationProps.txt
//   - EmojiSources.txt
//   - Index.txt
//   - IndicPositionalCategory.txt
//   - IndicSyllabicCategory.txt
//   - Jamo.txt
//   - LineBreak.txt
//   - NamedSequences.txt
//   - NamedSequencesProv.txt
//   - auxiliary/GraphemeBreakProperty.txt
//   - auxiliary/SentenceBreakProperty.txt
//   - auxiliary/WordBreakProperty.txt
//   - extracted/DerivedBidiClass.txt
//   - extracted/DerivedBinaryProperties.txt
//   - extracted/DerivedCombiningClass.txt
//   - extracted/DerivedDecompositionType.txt
//   - extracted/DerivedEastAsianWidth.txt
//   - extracted/DerivedGeneralCategory.txt
//   - extracted/DerivedJoiningGroup.txt
//   - extracted/DerivedJoiningType.txt
//   - extracted/DerivedLineBreak.txt
//   - extracted/DerivedName.txt
//   - extracted/DerivedNumericValues.txt

export * from "./ArabicShaping";
export * from "./BidiBrackets";
export * from "./BidiMirroring";
export * from "./Blocks";
export * from "./CJKRadicals";
export * from "./CaseFolding";
export * from "./CompositionExclusions";
export * from "./DerivedAge";
export * from "./DerivedCoreProperties";
export * from "./DerivedNormalizationProps";
export * from "./EmojiSources";
export * from "./_Index";
export * from "./IndicPositionalCategory";
export * from "./IndicSyllabicCategory";
export * from "./Jamo";
export * from "./LineBreak";
export * from "./NamedSequences";
export * from "./NamedSequencesProv";
export * from "./auxiliary/GraphemeBreakProperty";
export * from "./auxiliary/SentenceBreakProperty";
export * from "./auxiliary/WordBreakProperty";
export * from "./extracted/DerivedBidiClass";
export * from "./extracted/DerivedBinaryProperties";
export * from "./extracted/DerivedCombiningClass";
export * from "./extracted/DerivedDecompositionType";
export * from "./extracted/DerivedEastAsianWidth";
export * from "./extracted/DerivedGeneralCategory";
export * from "./extracted/DerivedJoiningGroup";
export * from "./extracted/DerivedJoiningType";
export * from "./extracted/DerivedLineBreak";
export * from "./extracted/DerivedName";
export * from "./extracted/DerivedNumericValues";
