// This file is generated by scripts/codegen/generate-fields.ts. Do not edit directly.
// Unicode Version: 2.1.9
// Files: 10
//   - Blocks-2.txt
//   - diff218v219d2.txt
//   - diff219d2v219d3.txt
//   - diff219d3v219d4.txt
//   - diff219d4v219d5.txt
//   - diff219d5v219d9.txt
//   - Jamo-2.txt
//   - PropList-2.1.9.txt
//   - SpecialCasing-2.txt
//   - UnicodeData-2.1.9.txt

export * from "./Blocks-2";
export * from "./diff218v219d2";
export * from "./diff219d2v219d3";
export * from "./diff219d3v219d4";
export * from "./diff219d4v219d5";
export * from "./diff219d5v219d9";
export * from "./Jamo-2";
export * from "./PropList-2.1.9";
export * from "./SpecialCasing-2";
export * from "./UnicodeData-2.1.9";
