# See https://github.com/actions/labeler

"pkg: metadata":
  - changed-files:
      - any-glob-to-any-file: packages/metadata/**

"pkg: core":
  - changed-files:
      - any-glob-to-any-file: packages/core/**

"🚨 ci":
  - changed-files:
      - any-glob-to-any-file: .github/workflows/**
