packages:
  - "packages/*"
  - "tooling/*"

catalogs:
  types:
    "@types/node": 24.9.1
    "@types/picomatch": 4.0.2

  build:
    picomatch: 4.0.3
    zod: 4.2.1
    "@luxass/utils": 2.7.2
    defu: 6.1.4

  linting:
    eslint: 9.39.2
    "@luxass/eslint-config": 6.0.3
    eslint-plugin-format: 1.1.0

  testing:
    "@vitest/coverage-v8": 4.0.16
    msw: 2.12.7
    vitest: 4.0.16
    vitest-package-exports: 1.1.1

  dev:
    tsx: 4.21.0
    typescript: 5.9.3
    tsdown: 0.18.3
    publint: 0.3.16
    turbo: 2.7.2
    rolldown: 1.0.0-beta.57

overrides:
  rolldown: catalog:dev
