// This file is generated by scripts/codegen/generate-fields.ts. Do not edit directly.
// Unicode Version: 11
// Generated At: 2026-04-23T16:44:43.843Z
// Files: 51
//   - ArabicShaping.txt
//   - auxiliary/GraphemeBreakProperty.txt
//   - auxiliary/SentenceBreakProperty.txt
//   - auxiliary/WordBreakProperty.txt
//   - BidiBrackets.txt
//   - BidiMirroring.txt
//   - Blocks.txt
//   - CaseFolding.txt
//   - CJKRadicals.txt
//   - CompositionExclusions.txt
//   - DerivedAge.txt
//   - DerivedCoreProperties.txt
//   - DerivedNormalizationProps.txt
//   - EastAsianWidth.txt
//   - EmojiSources.txt
//   - EquivalentUnifiedIdeograph.txt
//   - extracted/DerivedBidiClass.txt
//   - extracted/DerivedBinaryProperties.txt
//   - extracted/DerivedCombiningClass.txt
//   - extracted/DerivedDecompositionType.txt
//   - extracted/DerivedEastAsianWidth.txt
//   - extracted/DerivedGeneralCategory.txt
//   - extracted/DerivedJoiningGroup.txt
//   - extracted/DerivedJoiningType.txt
//   - extracted/DerivedLineBreak.txt
//   - extracted/DerivedName.txt
//   - extracted/DerivedNumericType.txt
//   - extracted/DerivedNumericValues.txt
//   - HangulSyllableType.txt
//   - Index.txt
//   - IndicPositionalCategory.txt
//   - IndicSyllabicCategory.txt
//   - Jamo.txt
//   - LineBreak.txt
//   - NameAliases.txt
//   - NamedSequences.txt
//   - NamedSequencesProv.txt
//   - NamesList.txt
//   - NormalizationCorrections.txt
//   - NushuSources.txt
//   - PropertyAliases.txt
//   - PropertyValueAliases.txt
//   - PropList.txt
//   - ScriptExtensions.txt
//   - Scripts.txt
//   - SpecialCasing.txt
//   - StandardizedVariants.txt
//   - TangutSources.txt
//   - UnicodeData.txt
//   - USourceData.txt
//   - VerticalOrientation.txt

// #region ArabicShaping.txt
/**
 * Parsed row from `ArabicShaping.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/ArabicShaping.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/ArabicShaping.txt#L25-L28
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/ArabicShaping.txt#L30-L35
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/ArabicShaping.txt#L37-L43
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/ArabicShaping.txt#L52
 *
 * @unicodeVersion 11
 * @fields 4
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:15.273Z
 */
export interface ArabicShaping {
  /**
   * the code point, in 4-digit hexadecimal form, of an Arabic, Syriac, N'Ko, Mandaic, Mongolian, Phags-pa, Manichaean, Psalter Pahlavi, Hanifi Rohingya, Sogdian, or other character.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/ArabicShaping.txt#L25-L28
   */
  code_point: string;

  /**
   * gives a short schematic name for that character. The schematic name is descriptive of the shape, based as consistently as possible on a name for the skeleton and then the diacritic marks applied to the skeleton, if any. Note that this schematic name is considered a comment, and does not constitute a formal property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/ArabicShaping.txt#L30-L35
   */
  schematic_name: string;

  /**
   * defines the joining type (property name: Joining_Type) R Right_Joining L Left_Joining D Dual_Joining C Join_Causing U Non_Joining T Transparent
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/ArabicShaping.txt#L37-L43
   */
  joining_type: "R" | "L" | "D" | "C" | "U" | "T";

  /**
   * defines the joining group (property name: Joining_Group)
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/ArabicShaping.txt#L52
   */
  joining_group: string;
}

export const ARABIC_SHAPING_FIELDS = ["code_point", "schematic_name", "joining_type", "joining_group"];

// #endregion

// #region auxiliary/GraphemeBreakProperty.txt
/**
 * Parsed row from `auxiliary/GraphemeBreakProperty.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/auxiliary/GraphemeBreakProperty.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr29/
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:17.741Z
 */
export interface AuxiliaryGraphemeBreakProperty {
  /**
   * Unicode code point or range.
   *
   * @source https://ucdjs.dev/reports/tr29/
   */
  code_point: string;

  /**
   * Grapheme_Cluster_Break property value; defaults to Other (XX) for unlisted code points.
   *
   * @source https://ucdjs.dev/reports/tr29/
   */
  grapheme_cluster_break: "Other" | (string & {});
}

export const AUXILIARY_GRAPHEME_BREAK_PROPERTY_FIELDS = ["code_point", "grapheme_cluster_break"];

// #endregion

// #region auxiliary/SentenceBreakProperty.txt
/**
 * Parsed row from `auxiliary/SentenceBreakProperty.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/auxiliary/SentenceBreakProperty.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/auxiliary/SentenceBreakProperty.txt#L14
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/auxiliary/SentenceBreakProperty.txt#L12
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:19.892Z
 */
export interface AuxiliarySentenceBreakProperty {
  /**
   * Unicode code point or range explicitly listed for Sentence_Break.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/auxiliary/SentenceBreakProperty.txt#L14
   */
  code_point: string;

  /**
   * Sentence_Break property value; unlisted code points have value Other (XX).
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/auxiliary/SentenceBreakProperty.txt#L12
   */
  sentence_break: "CR" | "LF" | "Extend" | "Sep" | "Format" | "Sp" | "Lower" | "STerm" | "Upper" | "OLetter" | "Numeric" | "ATerm" | "SContinue" | "Close" | "ATerm | numeric" | (string & {});
}

export const AUXILIARY_SENTENCE_BREAK_PROPERTY_FIELDS = ["code_point", "sentence_break"];

// #endregion

// #region auxiliary/WordBreakProperty.txt
/**
 * Parsed row from `auxiliary/WordBreakProperty.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/auxiliary/WordBreakProperty.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/auxiliary/WordBreakProperty.txt#L14
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/auxiliary/WordBreakProperty.txt#L12
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:20.142Z
 */
export interface AuxiliaryWordBreakProperty {
  /**
   * Unicode code point or range explicitly listed for Word_Break.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/auxiliary/WordBreakProperty.txt#L14
   */
  code_point: string;

  /**
   * Word_Break property value; defaults to Other (XX) for unlisted code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/auxiliary/WordBreakProperty.txt#L12
   */
  word_break: "AL" | "CR" | "Double_Quote" | "E_Base" | "E_Base_GAZ" | "E_Modifier" | "Extend" | "ExtendNumLet" | "FO" | "Format" | "GLue_After_Zwj" | "Hebrew_Letter" | "HT" | "Katakana" | "LF" | "LE" | "Letter" | "MidLetter" | "MidNum" | "MidNumLet" | "Newline" | "Numeric" | "Other" | "Perl" | "RI" | "Regional_Indicator" | "Single_Quote" | "SP" | "WSeg_Space" | "ZWJ" | (string & {});
}

export const AUXILIARY_WORD_BREAK_PROPERTY_FIELDS = ["code_point", "word_break"];

// #endregion

// #region BidiBrackets.txt
/**
 * Parsed row from `BidiBrackets.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/BidiBrackets.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/BidiBrackets.txt#L49
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/BidiBrackets.txt#L50
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/BidiBrackets.txt#L51-L54
 *
 * @unicodeVersion 11
 * @fields 3
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:15.380Z
 */
export interface BidiBrackets {
  /**
   * Unicode code point value, represented as a hexadecimal value.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/BidiBrackets.txt#L49
   */
  code_point: string;

  /**
   * Bidi_Paired_Bracket property value, a code point value or <none>.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/BidiBrackets.txt#L50
   */
  bidi_paired_bracket: string;

  /**
   * Bidi_Paired_Bracket_Type property value: o=Open, c=Close, n=None.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/BidiBrackets.txt#L51-L54
   */
  bidi_paired_bracket_type: "o" | "c" | "n";
}

export const BIDI_BRACKETS_FIELDS = ["code_point", "bidi_paired_bracket", "bidi_paired_bracket_type"];

// #endregion

// #region BidiMirroring.txt
/**
 * Parsed row from `BidiMirroring.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/BidiMirroring.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/BidiMirroring.txt#L14-L28
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:18.950Z
 */
export interface BidiMirroring {
  /**
   * Code point represented as a variable-length hexadecimal value with 4 to 6 digits that has the Bidi_Mirrored=Yes property.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/BidiMirroring.txt#L14-L28
   */
  source_code_point: string;

  /**
   * Code point represented as a variable-length hexadecimal value with 4 to 6 digits that typically has a glyph that is the mirror image of the source code point's glyph.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/BidiMirroring.txt#L14-L28
   */
  mirrored_code_point: string;
}

export const BIDI_MIRRORING_FIELDS = ["source_code_point", "mirrored_code_point"];

// #endregion

// #region Blocks.txt
/**
 * Parsed row from `Blocks.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/Blocks.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/Blocks.txt#L10
 *
 * @unicodeVersion 11
 * @fields 3
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:17.292Z
 */
export interface Blocks {
  /**
   * Start of the code point range in hexadecimal notation.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/Blocks.txt#L10
   */
  start_code: string;

  /**
   * End of the code point range in hexadecimal notation.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/Blocks.txt#L10
   */
  end_code: string;

  /**
   * Name of the Unicode block.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/Blocks.txt#L10
   */
  block_name: string;
}

export const BLOCKS_FIELDS = ["start_code", "end_code", "block_name"];

// #endregion

// #region CaseFolding.txt
/**
 * Parsed row from `CaseFolding.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/CaseFolding.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/CaseFolding.txt#L36
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/CaseFolding.txt#L36-L46
 *
 * @unicodeVersion 11
 * @fields 4
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:17.699Z
 */
export interface CaseFolding {
  /**
   * Unicode code point.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/CaseFolding.txt#L36
   */
  code: string;

  /**
   * Status field indicating the type of case folding: C (common), F (full), S (simple), T (special Turkic).
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/CaseFolding.txt#L36-L46
   */
  status: "C" | "F" | "S" | "T";

  /**
   * Case folding mapping; multiple characters separated by spaces for full mappings.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/CaseFolding.txt#L36
   */
  mapping: string;

  /**
   * Character name.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/CaseFolding.txt#L36
   */
  name: string;
}

export const CASE_FOLDING_FIELDS = ["code", "status", "mapping", "name"];

// #endregion

// #region CJKRadicals.txt
/**
 * Parsed row from `CJKRadicals.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/CJKRadicals.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/CJKRadicals.txt#L18-L22
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/CJKRadicals.txt#L13-L19
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/CJKRadicals.txt#L14-L20
 *
 * @unicodeVersion 11
 * @fields 3
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:29.639Z
 */
export interface CjkRadicals {
  /**
   * CJK radical number matching the regular expression [1-9][0-9]{0,2}'?.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/CJKRadicals.txt#L18-L22
   */
  cjk_radical_number: string;

  /**
   * Corresponding character in the Kangxi Radicals block or the CJK Radicals Supplement block.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/CJKRadicals.txt#L13-L19
   */
  cjk_radical_character: string;

  /**
   * CJK unified ideograph which is formed from that radical only.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/CJKRadicals.txt#L14-L20
   */
  cjk_unified_ideograph: string;
}

export const CJK_RADICALS_FIELDS = ["cjk_radical_number", "cjk_radical_character", "cjk_unified_ideograph"];

// #endregion

// #region CompositionExclusions.txt
/**
 * Parsed row from `CompositionExclusions.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/CompositionExclusions.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr15/
 *
 * @unicodeVersion 11
 * @fields 1
 * @confidence 0.80
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:43:18.659Z
 */
export interface CompositionExclusions {
  /**
   * Unicode code point that is a primary composition exclusion.
   *
   * @source https://ucdjs.dev/reports/tr15/
   */
  code_point: string;
}

export const COMPOSITION_EXCLUSIONS_FIELDS = ["code_point"];

// #endregion

// #region DerivedAge.txt
/**
 * Parsed row from `DerivedAge.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/DerivedAge.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/DerivedAge.txt#L52
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/DerivedAge.txt#L37
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:34.301Z
 */
export interface DerivedAge {
  /**
   * Unicode code point or range first assigned in the specified version.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/DerivedAge.txt#L52
   */
  code_point_range: string;

  /**
   * Age property value indicating Unicode version when code point was first assigned.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/DerivedAge.txt#L37
   */
  age: "V1_1" | "V1_1_5" | "V2_0" | "V2_1" | "V3_0" | "V3_1" | "V3_2" | "V4_0" | "V4_1" | "V5_0" | "V5_1" | "V5_2" | "V6_0" | "V6_1" | "V6_2" | "V6_3" | "V7_0" | "V8_0" | "V9_0" | "V10_0" | "V11_0" | "V12_0" | "V13_0" | "V14_0" | "V15_0" | "V15_1" | "V16_0" | "V17_0" | (string & {});
}

export const DERIVED_AGE_FIELDS = ["code_point_range", "age"];

// #endregion

// #region DerivedCoreProperties.txt
/**
 * Parsed row from `DerivedCoreProperties.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/DerivedCoreProperties.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:32.908Z
 */
export interface DerivedCoreProperties {
  /**
   * Unicode code point or range in standard UCD format.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point_range: string;

  /**
   * Derived Property: Math, generated from Sm + Other_Math.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  math: "Y" | "N";
}

export const DERIVED_CORE_PROPERTIES_FIELDS = ["code_point_range", "math"];

// #endregion

// #region DerivedNormalizationProps.txt
/**
 * Parsed row from `DerivedNormalizationProps.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/DerivedNormalizationProps.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 11
 * @fields 3
 * @confidence 0.50
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:43:15.226Z
 */
export interface DerivedNormalizationProps {
  /**
   * Unicode code point or range to which the derived normalization property applies.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point_range: string;

  /**
   * Name of the derived normalization property.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property_name: "NFKC_CF" | "Changes_When_NFKC_Casefold" | "FC_NFKC_Closure";

  /**
   * Value for the property, such as 'Y' for binary or space-separated code points for string mappings.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property_value: string;
}

export const DERIVED_NORMALIZATION_PROPS_FIELDS = ["code_point_range", "property_name", "property_value"];

// #endregion

// #region EastAsianWidth.txt
/**
 * Parsed row from `EastAsianWidth.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/EastAsianWidth.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/EastAsianWidth.txt#L16
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/EastAsianWidth.txt#L17-L18
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:32.852Z
 */
export interface EastAsianWidth {
  /**
   * Unicode code point value or range of code point values.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/EastAsianWidth.txt#L16
   */
  codepoints: string;

  /**
   * East_Asian_Width property, consisting of one of the following values: "A", "F", "H", "N", "Na", "W".
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/EastAsianWidth.txt#L17-L18
   */
  east_asian_width: "A" | "F" | "H" | "N" | "Na" | "W";
}

export const EAST_ASIAN_WIDTH_FIELDS = ["codepoints", "east_asian_width"];

// #endregion

// #region EmojiSources.txt
/**
 * Parsed row from `EmojiSources.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/EmojiSources.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/EmojiSources.txt#L22
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/EmojiSources.txt#L23
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/EmojiSources.txt#L24
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/EmojiSources.txt#L25
 *
 * @unicodeVersion 11
 * @fields 4
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:27.813Z
 */
export interface EmojiSources {
  /**
   * Unicode code point or sequence.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/EmojiSources.txt#L22
   */
  unicode: string;

  /**
   * DoCoMo Shift-JIS code.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/EmojiSources.txt#L23
   */
  docomo_shift_jis: string;

  /**
   * KDDI Shift-JIS code.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/EmojiSources.txt#L24
   */
  kddi_shift_jis: string;

  /**
   * SoftBank Shift-JIS code.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/EmojiSources.txt#L25
   */
  softbank_shift_jis: string;
}

export const EMOJI_SOURCES_FIELDS = ["unicode", "docomo_shift_jis", "kddi_shift_jis", "softbank_shift_jis"];

// #endregion

// #region EquivalentUnifiedIdeograph.txt
/**
 * Parsed row from `EquivalentUnifiedIdeograph.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/EquivalentUnifiedIdeograph.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/EquivalentUnifiedIdeograph.txt#L23-L26
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:31.613Z
 */
export interface EquivalentUnifiedIdeograph {
  /**
   * Code point or code point range represented as a variable-length hexadecimal value with 4 to 6 digits.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/EquivalentUnifiedIdeograph.txt#L23-L26
   */
  source_codepoint: string;

  /**
   * Equivalent CJK unified ideograph code point represented as a variable-length hexadecimal value with 4 to 6 digits.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/EquivalentUnifiedIdeograph.txt#L23-L26
   */
  equivalent_ideograph: string;
}

export const EQUIVALENT_UNIFIED_IDEOGRAPH_FIELDS = ["source_codepoint", "equivalent_ideograph"];

// #endregion

// #region extracted/DerivedBidiClass.txt
/**
 * Parsed row from `extracted/DerivedBidiClass.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/extracted/DerivedBidiClass.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedBidiClass.txt#L12
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:46.549Z
 */
export interface ExtractedDerivedBidiClass {
  /**
   * Unicode code point or range explicitly listed for Bidi_Class.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedBidiClass.txt#L12
   */
  code_point: string;

  /**
   * Bidi Class property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedBidiClass.txt#L12
   */
  bidi_class: "L" | "R" | "AL" | "ET" | "BN" | (string & {});
}

export const EXTRACTED_DERIVED_BIDI_CLASS_FIELDS = ["code_point", "bidi_class"];

// #endregion

// #region extracted/DerivedBinaryProperties.txt
/**
 * Parsed row from `extracted/DerivedBinaryProperties.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/extracted/DerivedBinaryProperties.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 11
 * @fields 3
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:44:14.547Z
 */
export interface ExtractedDerivedBinaryProperties {
  /**
   * Unicode code point or range in hexadecimal notation.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Name of the derived binary property (Yes values listed).
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property: string;

  /**
   * Optional comment including age or source.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  comment: string;
}

export const EXTRACTED_DERIVED_BINARY_PROPERTIES_FIELDS = ["code_point", "property", "comment"];

// #endregion

// #region extracted/DerivedCombiningClass.txt
/**
 * Parsed row from `extracted/DerivedCombiningClass.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/extracted/DerivedCombiningClass.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedCombiningClass.txt#L12-L21
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:52.329Z
 */
export interface ExtractedDerivedCombiningClass {
  /**
   * Unicode code point or range explicitly listed with a Canonical_Combining_Class value other than Not_Reordered (0).
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedCombiningClass.txt#L12-L21
   */
  code_point: string;

  /**
   * Canonical_Combining_Class value; defaults to Not_Reordered (0) for unlisted code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedCombiningClass.txt#L12-L21
   */
  combining_class: "Not_Reordered" | number;
}

export const EXTRACTED_DERIVED_COMBINING_CLASS_FIELDS = ["code_point", "combining_class"];

// #endregion

// #region extracted/DerivedDecompositionType.txt
/**
 * Parsed row from `extracted/DerivedDecompositionType.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/extracted/DerivedDecompositionType.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedDecompositionType.txt#L12
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:48.291Z
 */
export interface ExtractedDerivedDecompositionType {
  /**
   * Unicode code point or range explicitly listed with a Decomposition_Type value other than the default None.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedDecompositionType.txt#L12
   */
  code_point_range: string;

  /**
   * Decomposition_Type values from UnicodeData.txt field 5.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedDecompositionType.txt#L12
   */
  decomposition_type: "Canonical" | "Font" | "NoBreak" | "Initial" | "Medial" | "Final" | "Isolated" | "Circle" | "Super" | "Sub" | "Vertical" | "Wide" | "Narrow" | "Small" | "Square" | "Fraction" | "Compat" | (string & {});
}

export const EXTRACTED_DERIVED_DECOMPOSITION_TYPE_FIELDS = ["code_point_range", "decomposition_type"];

// #endregion

// #region extracted/DerivedEastAsianWidth.txt
/**
 * Parsed row from `extracted/DerivedEastAsianWidth.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/extracted/DerivedEastAsianWidth.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedEastAsianWidth.txt#L12
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:31.173Z
 */
export interface ExtractedDerivedEastAsianWidth {
  /**
   * Unicode code point range or single code point.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point_range: string;

  /**
   * East_Asian_Width property value (Neutral for unlisted code points).
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedEastAsianWidth.txt#L12
   */
  east_asian_width: "Neutral";
}

export const EXTRACTED_DERIVED_EAST_ASIAN_WIDTH_FIELDS = ["code_point_range", "east_asian_width"];

// #endregion

// #region extracted/DerivedGeneralCategory.txt
/**
 * Parsed row from `extracted/DerivedGeneralCategory.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/extracted/DerivedGeneralCategory.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedGeneralCategory.txt#L16
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedGeneralCategory.txt#L12
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:46.569Z
 */
export interface ExtractedDerivedGeneralCategory {
  /**
   * Unicode code point range with General_Category=Unassigned.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedGeneralCategory.txt#L16
   */
  code_point_range: string;

  /**
   * General_Category property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedGeneralCategory.txt#L12
   */
  general_category: "Unassigned";
}

export const EXTRACTED_DERIVED_GENERAL_CATEGORY_FIELDS = ["code_point_range", "general_category"];

// #endregion

// #region extracted/DerivedJoiningGroup.txt
/**
 * Parsed row from `extracted/DerivedJoiningGroup.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/extracted/DerivedJoiningGroup.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 11
 * @fields 3
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:43:22.711Z
 */
export interface ExtractedDerivedJoiningGroup {
  /**
   * Unicode code point or range listed with explicit Joining_Group values.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Joining_Group property value derived from ArabicShaping.txt field 3; unlisted code points default to No_Joining_Group.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  joining_group: string;

  /**
   * Optional comment providing additional context.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  comment: string;
}

export const EXTRACTED_DERIVED_JOINING_GROUP_FIELDS = ["code_point", "joining_group", "comment"];

// #endregion

// #region extracted/DerivedJoiningType.txt
/**
 * Parsed row from `extracted/DerivedJoiningType.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/extracted/DerivedJoiningType.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedJoiningType.txt#L14-L17
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedJoiningType.txt#L12-L21
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:46.875Z
 */
export interface ExtractedDerivedJoiningType {
  /**
   * Code point or range explicitly listed with a Joining_Type value other than the default Non_Joining.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedJoiningType.txt#L14-L17
   */
  code_point_range: string;

  /**
   * Joining_Type property value, such as Join_Causing, with default Non_Joining (U) for unlisted code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedJoiningType.txt#L12-L21
   */
  joining_type: "Join_Causing" | (string & {});
}

export const EXTRACTED_DERIVED_JOINING_TYPE_FIELDS = ["code_point_range", "joining_type"];

// #endregion

// #region extracted/DerivedLineBreak.txt
/**
 * Parsed row from `extracted/DerivedLineBreak.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/extracted/DerivedLineBreak.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr14/
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedLineBreak.txt#L12
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:01.570Z
 */
export interface ExtractedDerivedLineBreak {
  /**
   * Unicode code point or range explicitly listed for Line_Break.
   *
   * @source https://ucdjs.dev/reports/tr14/
   */
  code_point_range: string;

  /**
   * Line_Break property value for the code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedLineBreak.txt#L12
   */
  line_break: "Unknown";
}

export const EXTRACTED_DERIVED_LINE_BREAK_FIELDS = ["code_point_range", "line_break"];

// #endregion

// #region extracted/DerivedName.txt
/**
 * Parsed row from `extracted/DerivedName.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/extracted/DerivedName.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedName.txt#L22
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedName.txt#L23
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:21.871Z
 */
export interface ExtractedDerivedName {
  /**
   * Unicode code point value or range of code point values.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedName.txt#L22
   */
  code_point_or_range: string;

  /**
   * Name property value or pattern.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedName.txt#L23
   */
  name_or_pattern: string;
}

export const EXTRACTED_DERIVED_NAME_FIELDS = ["code_point_or_range", "name_or_pattern"];

// #endregion

// #region extracted/DerivedNumericType.txt
/**
 * Parsed row from `extracted/DerivedNumericType.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/extracted/DerivedNumericType.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedNumericType.txt#L12-L20
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:08.055Z
 */
export interface ExtractedDerivedNumericType {
  /**
   * Unicode code point or range explicitly listed with a Numeric_Type value.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedNumericType.txt#L12-L20
   */
  code_point: string;

  /**
   * Derived Numeric_Type property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedNumericType.txt#L12-L20
   */
  numeric_type: "Decimal" | "Digit" | "Numeric" | "None";
}

export const EXTRACTED_DERIVED_NUMERIC_TYPE_FIELDS = ["code_point", "numeric_type"];

// #endregion

// #region extracted/DerivedNumericValues.txt
/**
 * Parsed row from `extracted/DerivedNumericValues.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/extracted/DerivedNumericValues.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedNumericValues.txt#L13-L19
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedNumericValues.txt#L20-L21
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedNumericValues.txt#L23-L31
 *
 * @unicodeVersion 11
 * @fields 3
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:02.470Z
 */
export interface ExtractedDerivedNumericValues {
  /**
   * The values are based on field 8 of UnicodeData.txt, plus the fields kAccountingNumeric, kOtherNumeric, kPrimaryNumeric in the Unicode Han Database (Unihan).
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedNumericValues.txt#L13-L19
   */
  numeric_value: string;

  /**
   * This field is empty; it used to be a copy of the numeric type.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedNumericValues.txt#L20-L21
   */
  unused_numeric_type: string;

  /**
   * Expressing the same numeric value either as a whole integer where possible, or as a rational fraction such as "1/6".
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/extracted/DerivedNumericValues.txt#L23-L31
   */
  numeric_value_fraction: string;
}

export const EXTRACTED_DERIVED_NUMERIC_VALUES_FIELDS = ["numeric_value", "unused_numeric_type", "numeric_value_fraction"];

// #endregion

// #region HangulSyllableType.txt
/**
 * Parsed row from `HangulSyllableType.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/HangulSyllableType.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.50
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:44:13.638Z
 */
export interface HangulSyllableType {
  /**
   * Unicode code point or range in hexadecimal format (e.g. '0000..10FFFF').
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point_range: string;

  /**
   * Value of the Hangul_Syllable_Type property (default: Not_Applicable).
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  hangul_syllable_type: string;
}

export const HANGUL_SYLLABLE_TYPE_FIELDS = ["code_point_range", "hangul_syllable_type"];

// #endregion

// #region Index.txt
/**
 * Parsed row from `Index.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/Index.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 11
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:43:15.222Z
 */
export interface Index {

}

export const INDEX_FIELDS = [];

// #endregion

// #region IndicPositionalCategory.txt
/**
 * Parsed row from `IndicPositionalCategory.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/IndicPositionalCategory.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/IndicPositionalCategory.txt#L47
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/IndicPositionalCategory.txt#L48
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:33.957Z
 */
export interface IndicPositionalCategory {
  /**
   * Unicode code point value or range of code point values.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/IndicPositionalCategory.txt#L47
   */
  code_point: string;

  /**
   * Indic_Positional_Category property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/IndicPositionalCategory.txt#L48
   */
  indic_positional_category: string;
}

export const INDIC_POSITIONAL_CATEGORY_FIELDS = ["code_point", "indic_positional_category"];

// #endregion

// #region IndicSyllabicCategory.txt
/**
 * Parsed row from `IndicSyllabicCategory.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/IndicSyllabicCategory.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/IndicSyllabicCategory.txt#L27
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/IndicSyllabicCategory.txt#L28
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:01.266Z
 */
export interface IndicSyllabicCategory {
  /**
   * Unicode code point value or range of code point values
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/IndicSyllabicCategory.txt#L27
   */
  code_point: string;

  /**
   * Indic_Syllabic_Category property value
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/IndicSyllabicCategory.txt#L28
   */
  indic_syllabic_category: string;
}

export const INDIC_SYLLABIC_CATEGORY_FIELDS = ["code_point", "indic_syllabic_category"];

// #endregion

// #region Jamo.txt
/**
 * Parsed row from `Jamo.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/Jamo.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/Jamo.txt#L16-L18
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/Jamo.txt#L19-L21
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:19.557Z
 */
export interface Jamo {
  /**
   * 4-digit hexadecimal form of a conjoining jamo character that participates in the algorithmic determination of Hangul syllable character names.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/Jamo.txt#L16-L18
   */
  code_point: string;

  /**
   * Jamo_Short_Name as a one-, two-, or three-character ASCII string (or the null string).
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/Jamo.txt#L19-L21
   */
  jamo_short_name: string;
}

export const JAMO_FIELDS = ["code_point", "jamo_short_name"];

// #endregion

// #region LineBreak.txt
/**
 * Parsed row from `LineBreak.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/LineBreak.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/LineBreak.txt#L16
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/LineBreak.txt#L15-L24
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:27.830Z
 */
export interface LineBreak {
  /**
   * Unicode code point value or range of code point values.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/LineBreak.txt#L16
   */
  code_point_or_range: string;

  /**
   * Line_Break property, consisting of one of the following values: Non-tailorable: "BK", "CM", "CR", "GL", "LF", "NL", "SP", "WJ", "ZW", "ZWJ"; Tailorable: "AI", "AL", "B2", "BA", "BB", "CB", "CJ", "CL", "CP", "EB", "EM", "EX", "H2", "H3", "HL", "HY", "ID", "IN", "IS", "JL", "JT", "JV", "NS", "NU", "OP", "PO", "PR", "QU", "RI", "SA", "SG", "SY", "XX".
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/LineBreak.txt#L15-L24
   */
  line_break: "BK" | "CM" | "CR" | "GL" | "LF" | "NL" | "SP" | "WJ" | "ZW" | "ZWJ" | "AI" | "AL" | "B2" | "BA" | "BB" | "CB" | "CJ" | "CL" | "CP" | "EB" | "EM" | "EX" | "H2" | "H3" | "HL" | "HY" | "ID" | "IN" | "IS" | "JL" | "JT" | "JV" | "NS" | "NU" | "OP" | "PO" | "PR" | "QU" | "RI" | "SA" | "SG" | "SY" | "XX";
}

export const LINE_BREAK_FIELDS = ["code_point_or_range", "line_break"];

// #endregion

// #region NamedSequences.txt
/**
 * Parsed row from `NamedSequences.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/NamedSequences.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NamedSequences.txt#L15
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:17.408Z
 */
export interface NamedSequences {
  /**
   * Name of Sequence.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NamedSequences.txt#L15
   */
  name: string;

  /**
   * Code Point Sequence for USI.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NamedSequences.txt#L15
   */
  code_point_sequence: string;
}

export const NAMED_SEQUENCES_FIELDS = ["name", "code_point_sequence"];

// #endregion

// #region NamedSequencesProv.txt
/**
 * Parsed row from `NamedSequencesProv.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/NamedSequencesProv.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NamedSequencesProv.txt#L16
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:21.376Z
 */
export interface NamedSequencesProv {
  /**
   * Name of Sequence
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NamedSequencesProv.txt#L16
   */
  name_of_sequence: string;

  /**
   * Code Point Sequence for USI
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NamedSequencesProv.txt#L16
   */
  code_point_sequence: string;
}

export const NAMED_SEQUENCES_PROV_FIELDS = ["name_of_sequence", "code_point_sequence"];

// #endregion

// #region NamesList.txt
/**
 * Parsed row from `NamesList.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/NamesList.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 11
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:43:44.679Z
 */
export interface NamesList {

}

export const NAMES_LIST_FIELDS = [];

// #endregion

// #region NormalizationCorrections.txt
/**
 * Parsed row from `NormalizationCorrections.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/NormalizationCorrections.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NormalizationCorrections.txt#L35
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NormalizationCorrections.txt#L36
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NormalizationCorrections.txt#L37
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NormalizationCorrections.txt#L38-L39
 *
 * @unicodeVersion 11
 * @fields 4
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:46.455Z
 */
export interface NormalizationCorrections {
  /**
   * Unicode code point.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NormalizationCorrections.txt#L35
   */
  code_point: string;

  /**
   * Original (erroneous) decomposition.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NormalizationCorrections.txt#L36
   */
  original_decomposition: string;

  /**
   * Corrected decomposition.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NormalizationCorrections.txt#L37
   */
  corrected_decomposition: string;

  /**
   * Version of Unicode for which the correction was entered into UnicodeData.txt, in n.n.n format.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NormalizationCorrections.txt#L38-L39
   */
  version: string;
}

export const NORMALIZATION_CORRECTIONS_FIELDS = ["code_point", "original_decomposition", "corrected_decomposition", "version"];

// #endregion

// #region NushuSources.txt
/**
 * Parsed row from `NushuSources.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/NushuSources.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NushuSources.txt#L17
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NushuSources.txt#L18
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NushuSources.txt#L19
 *
 * @unicodeVersion 11
 * @fields 3
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:17.473Z
 */
export interface NushuSources {
  /**
   * The code point value in U+xxxxx format.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NushuSources.txt#L17
   */
  code_point: string;

  /**
   * A tag indicating the type of information in the third field.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NushuSources.txt#L18
   */
  tag: string;

  /**
   * The value of the tag (in UTF-8).
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/NushuSources.txt#L19
   */
  value: string;
}

export const NUSHU_SOURCES_FIELDS = ["code_point", "tag", "value"];

// #endregion

// #region PropertyAliases.txt
/**
 * Parsed row from `PropertyAliases.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/PropertyAliases.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/PropertyAliases.txt#L21-L23
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/PropertyAliases.txt#L23
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:33.284Z
 */
export interface PropertyAliases {
  /**
   * The first field is an abbreviated name for the property.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/PropertyAliases.txt#L21-L23
   */
  abbreviated_name: string;

  /**
   * The second field is a long name.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/PropertyAliases.txt#L23
   */
  long_name: string;
}

export const PROPERTY_ALIASES_FIELDS = ["abbreviated_name", "long_name"];

// #endregion

// #region PropertyValueAliases.txt
/**
 * Parsed row from `PropertyValueAliases.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/PropertyValueAliases.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/PropertyValueAliases.txt#L22-L24
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/PropertyValueAliases.txt#L25
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/PropertyValueAliases.txt#L27
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/PropertyValueAliases.txt#L29-L30
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/PropertyValueAliases.txt#L30
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/PropertyValueAliases.txt#L32
 *
 * @unicodeVersion 11
 * @fields 6
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:36.540Z
 */
export interface PropertyValueAliases {
  /**
   * The property for which the property value name is used.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/PropertyValueAliases.txt#L22-L24
   */
  property: string;

  /**
   * An abbreviated name.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/PropertyValueAliases.txt#L25
   */
  abbrev: string;

  /**
   * A long name.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/PropertyValueAliases.txt#L27
   */
  long: string;

  /**
   * Numeric for ccc, otherwise abbreviated name.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/PropertyValueAliases.txt#L29-L30
   */
  abbrev_ccc: string | number;

  /**
   * Long name for ccc.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/PropertyValueAliases.txt#L30
   */
  long_ccc: string;

  /**
   * Other aliases may be listed in additional fields.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/PropertyValueAliases.txt#L32
   */
  alias: string;
}

export const PROPERTY_VALUE_ALIASES_FIELDS = ["property", "abbrev", "long", "abbrev_ccc", "long_ccc", "alias"];

// #endregion

// #region PropList.txt
/**
 * Parsed row from `PropList.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/PropList.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:37.648Z
 */
export interface PropList {
  /**
   * Unicode code point or code point range.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point_range: string;

  /**
   * Binary property value (Yes or No).
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property_name: "Y" | "N";
}

export const PROP_LIST_FIELDS = ["code_point_range", "property_name"];

// #endregion

// #region ScriptExtensions.txt
/**
 * Parsed row from `ScriptExtensions.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/ScriptExtensions.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/ScriptExtensions.txt#L38
 *
 * @unicodeVersion 11
 * @fields 1
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:31.835Z
 */
export interface ScriptExtensions {
  /**
   * Set of one or more abbreviated Script property values indicating characters commonly used with more than one script.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/ScriptExtensions.txt#L38
   */
  script_extensions: "Beng" | (string & {});
}

export const SCRIPT_EXTENSIONS_FIELDS = ["script_extensions"];

// #endregion

// #region Scripts.txt
/**
 * Parsed row from `Scripts.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/Scripts.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr24/
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/Scripts.txt#L18-L23
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:28.181Z
 */
export interface Scripts {
  /**
   * Code point range in standard UCD format (e.g. '0041' or '1F600..1F64F').
   *
   * @source https://ucdjs.dev/reports/tr24/
   */
  range: string;

  /**
   * Script property value; all code points not explicitly listed have the value Unknown (Zzzz).
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/Scripts.txt#L18-L23
   */
  script: "Zzzz" | string;
}

export const SCRIPTS_FIELDS = ["range", "script"];

// #endregion

// #region SpecialCasing.txt
/**
 * Parsed row from `SpecialCasing.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/SpecialCasing.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/SpecialCasing.txt#L32
 *
 * @unicodeVersion 11
 * @fields 6
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:56.044Z
 */
export interface SpecialCasing {
  /**
   * Unicode code point in hexadecimal.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/SpecialCasing.txt#L32
   */
  code: string;

  /**
   * Full lowercase case mapping, expressed as one or more character values in hex separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/SpecialCasing.txt#L32
   */
  lower: string;

  /**
   * Full titlecase case mapping, expressed as one or more character values in hex separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/SpecialCasing.txt#L32
   */
  title: string;

  /**
   * Full uppercase case mapping, expressed as one or more character values in hex separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/SpecialCasing.txt#L32
   */
  upper: string;

  /**
   * Optional list of one or more language IDs or casing contexts separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/SpecialCasing.txt#L32
   */
  condition_list: string;

  /**
   * Informational comment.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/SpecialCasing.txt#L32
   */
  comment: string;
}

export const SPECIAL_CASING_FIELDS = ["code", "lower", "title", "upper", "condition_list", "comment"];

// #endregion

// #region StandardizedVariants.txt
/**
 * Parsed row from `StandardizedVariants.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/StandardizedVariants.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/StandardizedVariants.txt#L38
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/StandardizedVariants.txt#L39
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/StandardizedVariants.txt#L40-L42
 *
 * @unicodeVersion 11
 * @fields 3
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:55.818Z
 */
export interface StandardizedVariants {
  /**
   * the variation sequence
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/StandardizedVariants.txt#L38
   */
  variation_sequence: string;

  /**
   * the description of the desired appearance
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/StandardizedVariants.txt#L39
   */
  description: string;

  /**
   * where the appearance is only different in particular shaping environments; possible values are: isolate, initial, medial, final. If more than one is present, there are spaces between them.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/StandardizedVariants.txt#L40-L42
   */
  shaping_environments: "isolate" | "initial" | "medial" | "final" | (string & {});
}

export const STANDARDIZED_VARIANTS_FIELDS = ["variation_sequence", "description", "shaping_environments"];

// #endregion

// #region TangutSources.txt
/**
 * Parsed row from `TangutSources.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/TangutSources.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/TangutSources.txt#L20
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/TangutSources.txt#L21-L32
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/TangutSources.txt#L22
 *
 * @unicodeVersion 11
 * @fields 3
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:30.580Z
 */
export interface TangutSources {
  /**
   * the Tangut code point value in U+ format
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/TangutSources.txt#L20
   */
  tangut_code_point: string;

  /**
   * a tag indicating the type of information in the third field
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/TangutSources.txt#L21-L32
   */
  tag: "kTGT_MergedSrc" | "kRSTUnicode";

  /**
   * the value (in UTF-8)
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/TangutSources.txt#L22
   */
  value: string;
}

export const TANGUT_SOURCES_FIELDS = ["tangut_code_point", "tag", "value"];

// #endregion

// #region UnicodeData.txt
/**
 * Parsed row from `UnicodeData.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/UnicodeData.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 11
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:43:54.285Z
 */
export interface UnicodeData {

}

export const UNICODE_DATA_FIELDS = [];

// #endregion

// #region USourceData.txt
/**
 * Parsed row from `USourceData.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/USourceData.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/USourceData.txt#L12
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/USourceData.txt#L13-L28
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/USourceData.txt#L29-L32
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/USourceData.txt#L33
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/USourceData.txt#L34
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/USourceData.txt#L35
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/USourceData.txt#L36
 *
 * @unicodeVersion 11
 * @fields 7
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:43.843Z
 */
export interface USourceData {
  /**
   * The U-source ID
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/USourceData.txt#L12
   */
  u_source_id: string;

  /**
   * Text indicating the ideograph's status: C=Encoded in Extension C, D=Encoded in Extension D, E=Encoded in Extension E, F=Encoded in Extension F, G=Submitted by the UTC for IRG Working Set 2015, N=Planned to be submitted for a future extension, U=Encoded, UNC-2013=Included in the UTC's 2013 "Urgently Needed Characters" proposal, UNC-2015=Included in the UTC's 2015 "Urgently Needed Characters" proposal, UK-2015=Submitted by the UK for IRG Working Set 2015, V=Variant of an encoded character, W=Not suitable for encoding as a CJK Unified Ideograph, WS-2017=Submitted by the UTC for IRG Working Set 2017, X=No action taken, (UTC-\d{5})|(UCI-\d{5})=Duplicate entries deprecated in favor of other entries; the status value is the identifier of the non-deprecated character.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/USourceData.txt#L13-L28
   */
  status: "C" | "D" | "E" | "F" | "G" | "N" | "U" | "UNC-2013" | "UNC-2015" | "UK-2015" | "V" | "W" | "WS-2017" | "X" | (string & {});

  /**
   * A Unicode code point. If the status is V (Field 1), the code point in Field 2 specifies the encoded character for which this entry is a variant. Otherwise, the code point specifies the encoded character for this entry.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/USourceData.txt#L29-L32
   */
  code_point: string;

  /**
   * Radical-stroke count
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/USourceData.txt#L33
   */
  radical_stroke_count: string;

  /**
   * Virtual KangXi dictionary position
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/USourceData.txt#L34
   */
  virtual_kang_xi_position: string;

  /**
   * Ideographic Description Sequence (IDS), if possible
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/USourceData.txt#L35
   */
  ids: string;

  /**
   * Source(s)
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/USourceData.txt#L36
   */
  sources: string;
}

export const U_SOURCE_DATA_FIELDS = ["u_source_id", "status", "code_point", "radical_stroke_count", "virtual_kang_xi_position", "ids", "sources"];

// #endregion

// #region VerticalOrientation.txt
/**
 * Parsed row from `VerticalOrientation.txt` (Unicode 11).
 *
 * @see https://unicode.org/Public/11.0.0/ucd/VerticalOrientation.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/VerticalOrientation.txt#L16-L17
 * - https://ucdjs.dev/file-explorer/v/11.0.0/ucd/VerticalOrientation.txt#L18-L22
 *
 * @unicodeVersion 11
 * @fields 2
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:50.733Z
 */
export interface VerticalOrientation {
  /**
   * Unicode code point value or range of code point values in hexadecimal form.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/VerticalOrientation.txt#L16-L17
   */
  codepoints: string;

  /**
   * Vertical_Orientation property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/11.0.0/ucd/VerticalOrientation.txt#L18-L22
   */
  vertical_orientation: "U" | "R" | "Tu" | "Tr";
}

export const VERTICAL_ORIENTATION_FIELDS = ["codepoints", "vertical_orientation"];

// #endregion

