// This file is generated by scripts/codegen/generate-fields.ts. Do not edit directly.
// Unicode Version: 15
// Generated At: 2026-04-23T16:42:23.352Z
// Files: 53
//   - ArabicShaping.txt
//   - auxiliary/GraphemeBreakProperty.txt
//   - auxiliary/SentenceBreakProperty.txt
//   - auxiliary/WordBreakProperty.txt
//   - BidiBrackets.txt
//   - BidiMirroring.txt
//   - Blocks.txt
//   - CaseFolding.txt
//   - CJKRadicals.txt
//   - CompositionExclusions.txt
//   - DerivedAge.txt
//   - DerivedCoreProperties.txt
//   - DerivedNormalizationProps.txt
//   - EastAsianWidth.txt
//   - emoji/emoji-data.txt
//   - emoji/emoji-variation-sequences.txt
//   - EmojiSources.txt
//   - EquivalentUnifiedIdeograph.txt
//   - extracted/DerivedBidiClass.txt
//   - extracted/DerivedBinaryProperties.txt
//   - extracted/DerivedCombiningClass.txt
//   - extracted/DerivedDecompositionType.txt
//   - extracted/DerivedEastAsianWidth.txt
//   - extracted/DerivedGeneralCategory.txt
//   - extracted/DerivedJoiningGroup.txt
//   - extracted/DerivedJoiningType.txt
//   - extracted/DerivedLineBreak.txt
//   - extracted/DerivedName.txt
//   - extracted/DerivedNumericType.txt
//   - extracted/DerivedNumericValues.txt
//   - HangulSyllableType.txt
//   - Index.txt
//   - IndicPositionalCategory.txt
//   - IndicSyllabicCategory.txt
//   - Jamo.txt
//   - LineBreak.txt
//   - NameAliases.txt
//   - NamedSequences.txt
//   - NamedSequencesProv.txt
//   - NamesList.txt
//   - NormalizationCorrections.txt
//   - NushuSources.txt
//   - PropertyAliases.txt
//   - PropertyValueAliases.txt
//   - PropList.txt
//   - ScriptExtensions.txt
//   - Scripts.txt
//   - SpecialCasing.txt
//   - StandardizedVariants.txt
//   - TangutSources.txt
//   - UnicodeData.txt
//   - USourceData.txt
//   - VerticalOrientation.txt

// #region ArabicShaping.txt
/**
 * Parsed row from `ArabicShaping.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/ArabicShaping.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/ArabicShaping.txt#L26-L27
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/ArabicShaping.txt#L29-L34
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/ArabicShaping.txt#L36-L42
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/ArabicShaping.txt#L51-L61
 *
 * @unicodeVersion 15
 * @fields 4
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:40:28.111Z
 */
export interface ArabicShaping {
  /**
   * The code point, in 4-digit hexadecimal form, of a character.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/ArabicShaping.txt#L26-L27
   */
  code_point: string;

  /**
   * A short schematic name for that character. The schematic name is descriptive of the shape, based as consistently as possible on a name for the skeleton and then the diacritic marks applied to the skeleton, if any. Note that this schematic name is considered a comment, and does not constitute a formal property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/ArabicShaping.txt#L29-L34
   */
  schematic_name: string;

  /**
   * Defines the joining type (property name: Joining_Type) R Right_Joining L Left_Joining D Dual_Joining C Join_Causing U Non_Joining T Transparent.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/ArabicShaping.txt#L36-L42
   */
  joining_type: "R" | "L" | "D" | "C" | "U" | "T";

  /**
   * Defines the joining group (property name: Joining_Group). The values of the joining group are based schematically on character names. Where a schematic character name consists of two or more parts separated by spaces, the formal Joining_Group property value, as specified in PropertyValueAliases.txt, consists of the same name parts joined by underscores.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/ArabicShaping.txt#L51-L61
   */
  joining_group: string;
}

export const ARABIC_SHAPING_FIELDS = ["code_point", "schematic_name", "joining_type", "joining_group"];

// #endregion

// #region auxiliary/GraphemeBreakProperty.txt
/**
 * Parsed row from `auxiliary/GraphemeBreakProperty.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/auxiliary/GraphemeBreakProperty.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/auxiliary/GraphemeBreakProperty.txt#L14
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/auxiliary/GraphemeBreakProperty.txt#L12-L15
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:40:29.481Z
 */
export interface AuxiliaryGraphemeBreakProperty {
  /**
   * Unicode code point or range explicitly listed for Grapheme_Cluster_Break.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/auxiliary/GraphemeBreakProperty.txt#L14
   */
  code_point: string;

  /**
   * Grapheme_Cluster_Break property value; unlisted code points have default value Other (XX).
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/auxiliary/GraphemeBreakProperty.txt#L12-L15
   */
  grapheme_cluster_break: "Other" | (string & {});
}

export const AUXILIARY_GRAPHEME_BREAK_PROPERTY_FIELDS = ["code_point", "grapheme_cluster_break"];

// #endregion

// #region auxiliary/SentenceBreakProperty.txt
/**
 * Parsed row from `auxiliary/SentenceBreakProperty.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/auxiliary/SentenceBreakProperty.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/auxiliary/SentenceBreakProperty.txt#L12-L15
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:40:35.328Z
 */
export interface AuxiliarySentenceBreakProperty {
  /**
   * Unicode code point or range.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Sentence_Break property value; unlisted code points have the value Other (XX).
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/auxiliary/SentenceBreakProperty.txt#L12-L15
   */
  sentence_break: "CR" | "LF" | "Sep" | "STerm" | "ATerm" | "Lower" | "OLetter" | "Upper" | "Numeric" | "Extend" | "Sp" | "SA" | "SC" | "XX";
}

export const AUXILIARY_SENTENCE_BREAK_PROPERTY_FIELDS = ["code_point", "sentence_break"];

// #endregion

// #region auxiliary/WordBreakProperty.txt
/**
 * Parsed row from `auxiliary/WordBreakProperty.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/auxiliary/WordBreakProperty.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/auxiliary/WordBreakProperty.txt#L14
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/auxiliary/WordBreakProperty.txt#L12-L15
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:40:33.892Z
 */
export interface AuxiliaryWordBreakProperty {
  /**
   * Unicode code point or range explicitly listed for Word_Break.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/auxiliary/WordBreakProperty.txt#L14
   */
  code_point: string;

  /**
   * Word_Break property value; unlisted code points have value Other (XX).
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/auxiliary/WordBreakProperty.txt#L12-L15
   */
  word_break: string;
}

export const AUXILIARY_WORD_BREAK_PROPERTY_FIELDS = ["code_point", "word_break"];

// #endregion

// #region BidiBrackets.txt
/**
 * Parsed row from `BidiBrackets.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/BidiBrackets.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/BidiBrackets.txt#L49
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/BidiBrackets.txt#L50
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/BidiBrackets.txt#L51-L54
 *
 * @unicodeVersion 15
 * @fields 3
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:40:30.719Z
 */
export interface BidiBrackets {
  /**
   * Unicode code point value, represented as a hexadecimal value.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/BidiBrackets.txt#L49
   */
  code_point: string;

  /**
   * Bidi_Paired_Bracket property value, a code point value or <none>.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/BidiBrackets.txt#L50
   */
  bidi_paired_bracket: string;

  /**
   * Bidi_Paired_Bracket_Type property value: o=Open, c=Close, n=None.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/BidiBrackets.txt#L51-L54
   */
  bidi_paired_bracket_type: "o" | "c" | "n";
}

export const BIDI_BRACKETS_FIELDS = ["code_point", "bidi_paired_bracket", "bidi_paired_bracket_type"];

// #endregion

// #region BidiMirroring.txt
/**
 * Parsed row from `BidiMirroring.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/BidiMirroring.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/BidiMirroring.txt#L26-L28
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:40:32.658Z
 */
export interface BidiMirroring {
  /**
   * Code point with Bidi_Mirrored=Yes for which there is a mirror image Unicode character.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/BidiMirroring.txt#L26-L28
   */
  source_code_point: string;

  /**
   * Code point whose glyph is the mirror image of the source code point's glyph.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/BidiMirroring.txt#L26-L28
   */
  mirror_code_point: string;
}

export const BIDI_MIRRORING_FIELDS = ["source_code_point", "mirror_code_point"];

// #endregion

// #region Blocks.txt
/**
 * Parsed row from `Blocks.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/Blocks.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/Blocks.txt#L10
 *
 * @unicodeVersion 15
 * @fields 3
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:40:31.081Z
 */
export interface Blocks {
  /**
   * Start of the code point range.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/Blocks.txt#L10
   */
  start_code: string;

  /**
   * End of the code point range.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/Blocks.txt#L10
   */
  end_code: string;

  /**
   * Name of the Unicode block.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/Blocks.txt#L10
   */
  block_name: string;
}

export const BLOCKS_FIELDS = ["start_code", "end_code", "block_name"];

// #endregion

// #region CaseFolding.txt
/**
 * Parsed row from `CaseFolding.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/CaseFolding.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/CaseFolding.txt#L36
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/CaseFolding.txt#L36-L54
 *
 * @unicodeVersion 15
 * @fields 4
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:40:30.448Z
 */
export interface CaseFolding {
  /**
   * Unicode code point in hexadecimal notation.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/CaseFolding.txt#L36
   */
  code: string;

  /**
   * Status field indicating the type of case folding: C (common), F (full), S (simple), T (special Turkic).
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/CaseFolding.txt#L36-L54
   */
  status: "C" | "F" | "S" | "T";

  /**
   * Case folding mapping, which may be a single code point or multiple separated by spaces for full mappings.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/CaseFolding.txt#L36
   */
  mapping: string;

  /**
   * Name of the code point.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/CaseFolding.txt#L36
   */
  name: string;
}

export const CASE_FOLDING_FIELDS = ["code", "status", "mapping", "name"];

// #endregion

// #region CJKRadicals.txt
/**
 * Parsed row from `CJKRadicals.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/CJKRadicals.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/CJKRadicals.txt#L18-L22
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/CJKRadicals.txt#L19-L13
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/CJKRadicals.txt#L20-L15
 *
 * @unicodeVersion 15
 * @fields 3
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:40:44.221Z
 */
export interface CjkRadicals {
  /**
   * CJK radical number matching the regular expression [1-9][0-9]{0,2}'?.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/CJKRadicals.txt#L18-L22
   */
  cjk_radical_number: string;

  /**
   * CJK radical character in the Kangxi Radicals block or the CJK Radicals Supplement block.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/CJKRadicals.txt#L19-L13
   */
  cjk_radical_character: string;

  /**
   * CJK unified ideograph which is formed from that radical only.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/CJKRadicals.txt#L20-L15
   */
  cjk_unified_ideograph: string;
}

export const CJK_RADICALS_FIELDS = ["cjk_radical_number", "cjk_radical_character", "cjk_unified_ideograph"];

// #endregion

// #region CompositionExclusions.txt
/**
 * Parsed row from `CompositionExclusions.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/CompositionExclusions.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr15/
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:41:33.949Z
 */
export interface CompositionExclusions {
  /**
   * Unicode code point or range listed as a composition exclusion.
   *
   * @source https://ucdjs.dev/reports/tr15/
   */
  code_point: string;

  /**
   * Type of composition exclusion such as Script Specifics.
   *
   * @source https://ucdjs.dev/reports/tr15/
   */
  exclusion_type: string;
}

export const COMPOSITION_EXCLUSIONS_FIELDS = ["code_point", "exclusion_type"];

// #endregion

// #region DerivedAge.txt
/**
 * Parsed row from `DerivedAge.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/DerivedAge.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/DerivedAge.txt#L52
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/DerivedAge.txt#L37
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:40:51.847Z
 */
export interface DerivedAge {
  /**
   * Unicode code point range assigned in the specified version.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/DerivedAge.txt#L52
   */
  codepoint_range: string;

  /**
   * Age property value indicating the Unicode version when the code points were first assigned.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/DerivedAge.txt#L37
   */
  age: "V1_1" | "V1_1_5" | "V2_0" | "V2_1" | "V3_0" | "V3_1" | "V3_2" | "V4_0" | "V4_1" | "V5_0" | "V5_1" | "V5_2" | "V6_0" | "V6_1" | "V6_2" | "V6_3" | "V7_0" | "V8_0" | "V9_0" | "V10_0" | "V11_0" | "V12_0" | "V12_1" | "V13_0" | "V13_1" | "V14_0" | "V15_0" | "V15_1" | "V16_0" | "V17_0" | (string & {});
}

export const DERIVED_AGE_FIELDS = ["codepoint_range", "age"];

// #endregion

// #region DerivedCoreProperties.txt
/**
 * Parsed row from `DerivedCoreProperties.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/DerivedCoreProperties.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:41:20.794Z
 */
export interface DerivedCoreProperties {
  /**
   * Field for a code point range.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  codepoint_range: string;

  /**
   * The property alias for characters with binary property value Yes.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property: string;
}

export const DERIVED_CORE_PROPERTIES_FIELDS = ["codepoint_range", "property"];

// #endregion

// #region DerivedNormalizationProps.txt
/**
 * Parsed row from `DerivedNormalizationProps.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/DerivedNormalizationProps.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:41:17.237Z
 */
export interface DerivedNormalizationProps {
  /**
   * Hex value or range of hex values denoting codepoints having a particular closure.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point_range: string;

  /**
   * One or more hex values denoting codepoints in the FC_NFKC_Closure.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  fc_nfkc_closure: string[];
}

export const DERIVED_NORMALIZATION_PROPS_FIELDS = ["code_point_range", "fc_nfkc_closure"];

// #endregion

// #region EastAsianWidth.txt
/**
 * Parsed row from `EastAsianWidth.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/EastAsianWidth.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/EastAsianWidth.txt#L16
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/EastAsianWidth.txt#L15-L20
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:40:46.388Z
 */
export interface EastAsianWidth {
  /**
   * Unicode code point value or range of code point values.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/EastAsianWidth.txt#L16
   */
  code_point_or_range: string;

  /**
   * East_Asian_Width property, consisting of one of the following values: "A", "F", "H", "N", "Na", "W".
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/EastAsianWidth.txt#L15-L20
   */
  east_asian_width: "A" | "F" | "H" | "N" | "Na" | "W";
}

export const EAST_ASIAN_WIDTH_FIELDS = ["code_point_or_range", "east_asian_width"];

// #endregion

// #region emoji/emoji-data.txt
/**
 * Parsed row from `emoji/emoji-data.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/emoji/emoji-data.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/emoji/emoji-data.txt#L13
 *
 * @unicodeVersion 15
 * @fields 3
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:40:47.289Z
 */
export interface EmojiEmojiData {
  /**
   * Unicode codepoint(s).
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/emoji/emoji-data.txt#L13
   */
  codepoints: string;

  /**
   * Emoji property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/emoji/emoji-data.txt#L13
   */
  property: string;

  /**
   * Comments.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/emoji/emoji-data.txt#L13
   */
  comments: string;
}

export const EMOJI_EMOJI_DATA_FIELDS = ["codepoints", "property", "comments"];

// #endregion

// #region emoji/emoji-variation-sequences.txt
/**
 * Parsed row from `emoji/emoji-variation-sequences.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/emoji/emoji-variation-sequences.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr51/
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:41:07.145Z
 */
export interface EmojiEmojiVariationSequences {
  /**
   * Code point or code point range of the emoji base in the variation sequence.
   *
   * @source https://ucdjs.dev/reports/tr51/
   */
  code_point_range: string;

  /**
   * Hex value of the variation selector (VS15 or VS16) used in the emoji variation sequence.
   *
   * @source https://ucdjs.dev/reports/tr51/
   */
  variation_selector: "FE0E" | "FE0F";
}

export const EMOJI_EMOJI_VARIATION_SEQUENCES_FIELDS = ["code_point_range", "variation_selector"];

// #endregion

// #region EmojiSources.txt
/**
 * Parsed row from `EmojiSources.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/EmojiSources.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/EmojiSources.txt#L22
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/EmojiSources.txt#L23
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/EmojiSources.txt#L24
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/EmojiSources.txt#L25
 *
 * @unicodeVersion 15
 * @fields 4
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:40:55.311Z
 */
export interface EmojiSources {
  /**
   * Unicode code point or sequence.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/EmojiSources.txt#L22
   */
  unicode: string;

  /**
   * DoCoMo Shift-JIS code.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/EmojiSources.txt#L23
   */
  docomo_shift_jis: string;

  /**
   * KDDI Shift-JIS code.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/EmojiSources.txt#L24
   */
  kddi_shift_jis: string;

  /**
   * SoftBank Shift-JIS code.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/EmojiSources.txt#L25
   */
  softbank_shift_jis: string;
}

export const EMOJI_SOURCES_FIELDS = ["unicode", "docomo_shift_jis", "kddi_shift_jis", "softbank_shift_jis"];

// #endregion

// #region EquivalentUnifiedIdeograph.txt
/**
 * Parsed row from `EquivalentUnifiedIdeograph.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/EquivalentUnifiedIdeograph.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/EquivalentUnifiedIdeograph.txt#L23-L26
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:42.625Z
 */
export interface EquivalentUnifiedIdeograph {
  /**
   * Code point or code point range represented as a variable-length hexadecimal value with 4 to 6 digits.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/EquivalentUnifiedIdeograph.txt#L23-L26
   */
  source_codepoint: string;

  /**
   * Equivalent CJK unified ideograph code point represented as a variable-length hexadecimal value with 4 to 6 digits.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/EquivalentUnifiedIdeograph.txt#L23-L26
   */
  equivalent_codepoint: string;
}

export const EQUIVALENT_UNIFIED_IDEOGRAPH_FIELDS = ["source_codepoint", "equivalent_codepoint"];

// #endregion

// #region extracted/DerivedBidiClass.txt
/**
 * Parsed row from `extracted/DerivedBidiClass.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/extracted/DerivedBidiClass.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedBidiClass.txt#L12
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:08.704Z
 */
export interface ExtractedDerivedBidiClass {
  /**
   * Unicode code point or range explicitly listed for Bidi_Class.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedBidiClass.txt#L12
   */
  code_point_range: string;

  /**
   * Bidi Class value assigned to the code points (see UAX #44).
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedBidiClass.txt#L12
   */
  bidi_class: "Left_To_Right" | "Right_To_Left" | "Arabic_Letter" | "European_Terminator";
}

export const EXTRACTED_DERIVED_BIDI_CLASS_FIELDS = ["code_point_range", "bidi_class"];

// #endregion

// #region extracted/DerivedBinaryProperties.txt
/**
 * Parsed row from `extracted/DerivedBinaryProperties.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/extracted/DerivedBinaryProperties.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 15
 * @fields 3
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:41:55.043Z
 */
export interface ExtractedDerivedBinaryProperties {
  /**
   * Unicode code point or range in hexadecimal notation.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Binary property name, listing characters with value 'Y' from UnicodeData.txt field 9.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property: "Bidi_Mirrored";

  /**
   * Comment including property status (Y/N) and character name.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  comment: string;
}

export const EXTRACTED_DERIVED_BINARY_PROPERTIES_FIELDS = ["code_point", "property", "comment"];

// #endregion

// #region extracted/DerivedCombiningClass.txt
/**
 * Parsed row from `extracted/DerivedCombiningClass.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/extracted/DerivedCombiningClass.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedCombiningClass.txt#L17
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedCombiningClass.txt#L12-L15
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:28.072Z
 */
export interface ExtractedDerivedCombiningClass {
  /**
   * Unicode code point or range with Canonical_Combining_Class value.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedCombiningClass.txt#L17
   */
  code_point_range: string;

  /**
   * Canonical Combining Class value (defaults to Not_Reordered (0) for unlisted code points).
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedCombiningClass.txt#L12-L15
   */
  combining_class: "Not_Reordered" | (string & {});
}

export const EXTRACTED_DERIVED_COMBINING_CLASS_FIELDS = ["code_point_range", "combining_class"];

// #endregion

// #region extracted/DerivedDecompositionType.txt
/**
 * Parsed row from `extracted/DerivedDecompositionType.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/extracted/DerivedDecompositionType.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedDecompositionType.txt#L14-L15
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedDecompositionType.txt#L12
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:02.411Z
 */
export interface ExtractedDerivedDecompositionType {
  /**
   * Unicode code point or range explicitly listed with a Decomposition_Type value other than the default None.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedDecompositionType.txt#L14-L15
   */
  code_point_range: string;

  /**
   * Decomposition_Type (from UnicodeData.txt, field 5).
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedDecompositionType.txt#L12
   */
  decomposition_type: string;
}

export const EXTRACTED_DERIVED_DECOMPOSITION_TYPE_FIELDS = ["code_point_range", "decomposition_type"];

// #endregion

// #region extracted/DerivedEastAsianWidth.txt
/**
 * Parsed row from `extracted/DerivedEastAsianWidth.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/extracted/DerivedEastAsianWidth.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedEastAsianWidth.txt#L12
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedEastAsianWidth.txt#L14-L15
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:01.851Z
 */
export interface ExtractedDerivedEastAsianWidth {
  /**
   * Unicode code point range or single code point with East_Asian_Width property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedEastAsianWidth.txt#L12
   */
  code_point_range: string;

  /**
   * East Asian Width property value, with default Neutral (N) for unlisted code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedEastAsianWidth.txt#L14-L15
   */
  east_asian_width: "F" | "H" | "W" | "Na" | "A" | "N";
}

export const EXTRACTED_DERIVED_EAST_ASIAN_WIDTH_FIELDS = ["code_point_range", "east_asian_width"];

// #endregion

// #region extracted/DerivedGeneralCategory.txt
/**
 * Parsed row from `extracted/DerivedGeneralCategory.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/extracted/DerivedGeneralCategory.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedGeneralCategory.txt#L16
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedGeneralCategory.txt#L12
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:20.486Z
 */
export interface ExtractedDerivedGeneralCategory {
  /**
   * Unicode code point range with General_Category=Unassigned.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedGeneralCategory.txt#L16
   */
  code_point_range: string;

  /**
   * General_Category property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedGeneralCategory.txt#L12
   */
  general_category: "Unassigned";
}

export const EXTRACTED_DERIVED_GENERAL_CATEGORY_FIELDS = ["code_point_range", "general_category"];

// #endregion

// #region extracted/DerivedJoiningGroup.txt
/**
 * Parsed row from `extracted/DerivedJoiningGroup.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/extracted/DerivedJoiningGroup.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedJoiningGroup.txt#L12
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedJoiningGroup.txt#L14-L17
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:12.561Z
 */
export interface ExtractedDerivedJoiningGroup {
  /**
   * Unicode code point or range with Joining_Group value.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedJoiningGroup.txt#L12
   */
  code_point: string;

  /**
   * Default value for all code points not explicitly listed.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedJoiningGroup.txt#L14-L17
   */
  joining_group: "No_Joining_Group";
}

export const EXTRACTED_DERIVED_JOINING_GROUP_FIELDS = ["code_point", "joining_group"];

// #endregion

// #region extracted/DerivedJoiningType.txt
/**
 * Parsed row from `extracted/DerivedJoiningType.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/extracted/DerivedJoiningType.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedJoiningType.txt#L14-L17
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedJoiningType.txt#L12-L21
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:52.006Z
 */
export interface ExtractedDerivedJoiningType {
  /**
   * Code point or range explicitly listed with a Joining_Type value other than the default Non_Joining.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedJoiningType.txt#L14-L17
   */
  code_point_range: string;

  /**
   * Joining_Type property value, with default Non_Joining (U) for all unlisted code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedJoiningType.txt#L12-L21
   */
  joining_type: "Join_Causing" | (string & {});
}

export const EXTRACTED_DERIVED_JOINING_TYPE_FIELDS = ["code_point_range", "joining_type"];

// #endregion

// #region extracted/DerivedLineBreak.txt
/**
 * Parsed row from `extracted/DerivedLineBreak.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/extracted/DerivedLineBreak.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr14/
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedLineBreak.txt#L12-L15
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:22.702Z
 */
export interface ExtractedDerivedLineBreak {
  /**
   * Unicode code point range or single code point.
   *
   * @source https://ucdjs.dev/reports/tr14/
   */
  code_point_range: string;

  /**
   * Line_Break property value; defaults to Unknown (XX) for unlisted code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedLineBreak.txt#L12-L15
   */
  line_break: "Unknown" | "Prefix_Numeric" | "Ideographic" | (string & {});
}

export const EXTRACTED_DERIVED_LINE_BREAK_FIELDS = ["code_point_range", "line_break"];

// #endregion

// #region extracted/DerivedName.txt
/**
 * Parsed row from `extracted/DerivedName.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/extracted/DerivedName.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedName.txt#L22
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedName.txt#L23
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:57.295Z
 */
export interface ExtractedDerivedName {
  /**
   * Unicode code point value or range of code point values.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedName.txt#L22
   */
  code_point_or_range: string;

  /**
   * Name property value or pattern.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedName.txt#L23
   */
  name_or_pattern: string;
}

export const EXTRACTED_DERIVED_NAME_FIELDS = ["code_point_or_range", "name_or_pattern"];

// #endregion

// #region extracted/DerivedNumericType.txt
/**
 * Parsed row from `extracted/DerivedNumericType.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/extracted/DerivedNumericType.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedNumericType.txt#L12-L23
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:37.040Z
 */
export interface ExtractedDerivedNumericType {
  /**
   * Unicode code point or range explicitly listed with a Numeric_Type value other than the default None.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedNumericType.txt#L12-L23
   */
  code_point: string;

  /**
   * Derived Numeric_Type property value: Decimal, Digit, Numeric, or None (default for unlisted code points).
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedNumericType.txt#L12-L23
   */
  numeric_type: "Decimal" | "Digit" | "Numeric" | (string & {});
}

export const EXTRACTED_DERIVED_NUMERIC_TYPE_FIELDS = ["code_point", "numeric_type"];

// #endregion

// #region extracted/DerivedNumericValues.txt
/**
 * Parsed row from `extracted/DerivedNumericValues.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/extracted/DerivedNumericValues.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedNumericValues.txt#L13-L19
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedNumericValues.txt#L20-L21
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedNumericValues.txt#L23-L31
 *
 * @unicodeVersion 15
 * @fields 3
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:13.431Z
 */
export interface ExtractedDerivedNumericValues {
  /**
   * The values are based on field 8 of UnicodeData.txt, plus the fields kAccountingNumeric, kOtherNumeric, kPrimaryNumeric in the Unicode Han Database (Unihan).
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedNumericValues.txt#L13-L19
   */
  numeric_value: string;

  /**
   * This field is empty; it used to be a copy of the numeric type.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedNumericValues.txt#L20-L21
   */
  unused_field: string;

  /**
   * Expressing the same numeric value either as a whole integer where possible, or as a rational fraction such as "1/6".
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/extracted/DerivedNumericValues.txt#L23-L31
   */
  numeric_value_fraction: string;
}

export const EXTRACTED_DERIVED_NUMERIC_VALUES_FIELDS = ["numeric_value", "unused_field", "numeric_value_fraction"];

// #endregion

// #region HangulSyllableType.txt
/**
 * Parsed row from `HangulSyllableType.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/HangulSyllableType.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/HangulSyllableType.txt#L21
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/HangulSyllableType.txt#L12-L15
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:14.284Z
 */
export interface HangulSyllableType {
  /**
   * Unicode code point or range explicitly listed for a specific Hangul_Syllable_Type value.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/HangulSyllableType.txt#L21
   */
  code_point_range: string;

  /**
   * Value of the Hangul_Syllable_Type property; all unlisted code points have value Not_Applicable (NA).
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/HangulSyllableType.txt#L12-L15
   */
  hangul_syllable_type: "Leading_Jamo" | (string & {});
}

export const HANGUL_SYLLABLE_TYPE_FIELDS = ["code_point_range", "hangul_syllable_type"];

// #endregion

// #region Index.txt
/**
 * Parsed row from `Index.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/Index.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 15
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:41:35.812Z
 */
export interface Index {

}

export const INDEX_FIELDS = [];

// #endregion

// #region IndicPositionalCategory.txt
/**
 * Parsed row from `IndicPositionalCategory.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/IndicPositionalCategory.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/IndicPositionalCategory.txt#L57
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/IndicPositionalCategory.txt#L58
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:24.863Z
 */
export interface IndicPositionalCategory {
  /**
   * Unicode code point value or range of code point values
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/IndicPositionalCategory.txt#L57
   */
  code_point: string;

  /**
   * Indic_Positional_Category property value
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/IndicPositionalCategory.txt#L58
   */
  indic_positional_category: string;
}

export const INDIC_POSITIONAL_CATEGORY_FIELDS = ["code_point", "indic_positional_category"];

// #endregion

// #region IndicSyllabicCategory.txt
/**
 * Parsed row from `IndicSyllabicCategory.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/IndicSyllabicCategory.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/IndicSyllabicCategory.txt#L27
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/IndicSyllabicCategory.txt#L28
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:55.977Z
 */
export interface IndicSyllabicCategory {
  /**
   * Unicode code point value or range of code point values
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/IndicSyllabicCategory.txt#L27
   */
  code_point: string;

  /**
   * Indic_Syllabic_Category property value
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/IndicSyllabicCategory.txt#L28
   */
  indic_syllabic_category: string;
}

export const INDIC_SYLLABIC_CATEGORY_FIELDS = ["code_point", "indic_syllabic_category"];

// #endregion

// #region Jamo.txt
/**
 * Parsed row from `Jamo.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/Jamo.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/Jamo.txt#L16-L18
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/Jamo.txt#L19-L21
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:32.749Z
 */
export interface Jamo {
  /**
   * 4-digit hexadecimal form of a conjoining jamo character that participates in the algorithmic determination of Hangul syllable character names.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/Jamo.txt#L16-L18
   */
  code_point: string;

  /**
   * Jamo_Short_Name as a one-, two-, or three-character ASCII string (or the null string for U+110B).
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/Jamo.txt#L19-L21
   */
  jamo_short_name: string;
}

export const JAMO_FIELDS = ["code_point", "jamo_short_name"];

// #endregion

// #region LineBreak.txt
/**
 * Parsed row from `LineBreak.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/LineBreak.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/LineBreak.txt#L16
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/LineBreak.txt#L15-L24
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:02.889Z
 */
export interface LineBreak {
  /**
   * Unicode code point value or range of code point values.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/LineBreak.txt#L16
   */
  code_point_range: string;

  /**
   * Line_Break property, consisting of one of the following values: Non-tailorable: "BK", "CM", "CR", "GL", "LF", "NL", "SP", "WJ", "ZW", "ZWJ"; Tailorable: "AI", "AL", "B2", "BA", "BB", "CB", "CJ", "CL", "CP", "EB", "EM", "EX", "H2", "H3", "HL", "HY", "ID", "IN", "IS", "JL", "JT", "JV", "NS", "NU", "OP", "PO", "PR", "QU", "RI", "SA", "SG", "SY", "XX".
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/LineBreak.txt#L15-L24
   */
  line_break: "BK" | "CM" | "CR" | "GL" | "LF" | "NL" | "SP" | "WJ" | "ZW" | "ZWJ" | "AI" | "AL" | "B2" | "BA" | "BB" | "CB" | "CJ" | "CL" | "CP" | "EB" | "EM" | "EX" | "H2" | "H3" | "HL" | "HY" | "ID" | "IN" | "IS" | "JL" | "JT" | "JV" | "NS" | "NU" | "OP" | "PO" | "PR" | "QU" | "RI" | "SA" | "SG" | "SY" | "XX";
}

export const LINE_BREAK_FIELDS = ["code_point_range", "line_break"];

// #endregion

// #region NameAliases.txt
/**
 * Parsed row from `NameAliases.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/NameAliases.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NameAliases.txt#L47-L51
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NameAliases.txt#L16-L32
 *
 * @unicodeVersion 15
 * @fields 3
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:39.900Z
 */
export interface NameAliases {
  /**
   * Unicode code point in hexadecimal notation.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NameAliases.txt#L47-L51
   */
  code_point: string;

  /**
   * Formal name alias for the character.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NameAliases.txt#L47-L51
   */
  alias: string;

  /**
   * Type label of the formal name alias (case-insensitive).
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NameAliases.txt#L16-L32
   */
  type: "correction" | "control" | "alternate" | "figment" | "abbreviation" | (string & {});
}

export const NAME_ALIASES_FIELDS = ["code_point", "alias", "type"];

// #endregion

// #region NamedSequences.txt
/**
 * Parsed row from `NamedSequences.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/NamedSequences.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NamedSequences.txt#L15
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:26.063Z
 */
export interface NamedSequences {
  /**
   * Name of Sequence.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NamedSequences.txt#L15
   */
  name: string;

  /**
   * Code Point Sequence for USI.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NamedSequences.txt#L15
   */
  code_point_sequence: string;
}

export const NAMED_SEQUENCES_FIELDS = ["name", "code_point_sequence"];

// #endregion

// #region NamedSequencesProv.txt
/**
 * Parsed row from `NamedSequencesProv.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/NamedSequencesProv.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NamedSequencesProv.txt#L16
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:26.317Z
 */
export interface NamedSequencesProv {
  /**
   * Name of Sequence.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NamedSequencesProv.txt#L16
   */
  name: string;

  /**
   * Code Point Sequence for USI.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NamedSequencesProv.txt#L16
   */
  code_point_sequence: string;
}

export const NAMED_SEQUENCES_PROV_FIELDS = ["name", "code_point_sequence"];

// #endregion

// #region NamesList.txt
/**
 * Parsed row from `NamesList.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/NamesList.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 15
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:41:48.060Z
 */
export interface NamesList {

}

export const NAMES_LIST_FIELDS = [];

// #endregion

// #region NormalizationCorrections.txt
/**
 * Parsed row from `NormalizationCorrections.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/NormalizationCorrections.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NormalizationCorrections.txt#L35
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NormalizationCorrections.txt#L36
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NormalizationCorrections.txt#L37
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NormalizationCorrections.txt#L38-L39
 *
 * @unicodeVersion 15
 * @fields 4
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:32.221Z
 */
export interface NormalizationCorrections {
  /**
   * Unicode code point.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NormalizationCorrections.txt#L35
   */
  code_point: string;

  /**
   * Original (erroneous) decomposition.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NormalizationCorrections.txt#L36
   */
  original_decomposition: string;

  /**
   * Corrected decomposition.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NormalizationCorrections.txt#L37
   */
  corrected_decomposition: string;

  /**
   * Version of Unicode for which the correction was entered into UnicodeData.txt, in n.n.n format.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NormalizationCorrections.txt#L38-L39
   */
  version: string;
}

export const NORMALIZATION_CORRECTIONS_FIELDS = ["code_point", "original_decomposition", "corrected_decomposition", "version"];

// #endregion

// #region NushuSources.txt
/**
 * Parsed row from `NushuSources.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/NushuSources.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NushuSources.txt#L17
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NushuSources.txt#L18
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NushuSources.txt#L19
 *
 * @unicodeVersion 15
 * @fields 3
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:59.929Z
 */
export interface NushuSources {
  /**
   * The code point value in U+xxxxx format.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NushuSources.txt#L17
   */
  code_point: string;

  /**
   * A tag indicating the type of information in the third field.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NushuSources.txt#L18
   */
  tag: string;

  /**
   * The value of the tag (in UTF-8).
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/NushuSources.txt#L19
   */
  value: string;
}

export const NUSHU_SOURCES_FIELDS = ["code_point", "tag", "value"];

// #endregion

// #region PropertyAliases.txt
/**
 * Parsed row from `PropertyAliases.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/PropertyAliases.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/PropertyAliases.txt#L21-L25
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/PropertyAliases.txt#L27-L28
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:41.320Z
 */
export interface PropertyAliases {
  /**
   * The first field is the short name for the property. It is typically an abbreviation, but in a number of cases it is simply a duplicate of the "long name" in the second field.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/PropertyAliases.txt#L21-L25
   */
  short_name: string;

  /**
   * The second field is the long name for the property, typically the formal name used in documentation about the property.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/PropertyAliases.txt#L27-L28
   */
  long_name: string;
}

export const PROPERTY_ALIASES_FIELDS = ["short_name", "long_name"];

// #endregion

// #region PropertyValueAliases.txt
/**
 * Parsed row from `PropertyValueAliases.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/PropertyValueAliases.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/PropertyValueAliases.txt#L22-L24
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/PropertyValueAliases.txt#L25-L27
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/PropertyValueAliases.txt#L29-L30
 *
 * @unicodeVersion 15
 * @fields 3
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:09.736Z
 */
export interface PropertyValueAliases {
  /**
   * The property for which the property value name is used.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/PropertyValueAliases.txt#L22-L24
   */
  property: string;

  /**
   * The short name for the property value, typically an abbreviation.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/PropertyValueAliases.txt#L25-L27
   */
  short_name: string;

  /**
   * The long name for the property value, typically the formal name used in documentation.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/PropertyValueAliases.txt#L29-L30
   */
  long_name: string;
}

export const PROPERTY_VALUE_ALIASES_FIELDS = ["property", "short_name", "long_name"];

// #endregion

// #region PropList.txt
/**
 * Parsed row from `PropList.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/PropList.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:45.937Z
 */
export interface PropList {
  /**
   * Unicode code point or code point range.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point_range: string;

  /**
   * Binary property value (Yes or No).
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property_name: "Y" | "N";
}

export const PROP_LIST_FIELDS = ["code_point_range", "property_name"];

// #endregion

// #region ScriptExtensions.txt
/**
 * Parsed row from `ScriptExtensions.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/ScriptExtensions.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/ScriptExtensions.txt#L38
 *
 * @unicodeVersion 15
 * @fields 1
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:36.530Z
 */
export interface ScriptExtensions {
  /**
   * Set of one or more abbreviated Script property values indicating which characters are commonly used with more than one script.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/ScriptExtensions.txt#L38
   */
  script_extensions: string[];
}

export const SCRIPT_EXTENSIONS_FIELDS = ["script_extensions"];

// #endregion

// #region Scripts.txt
/**
 * Parsed row from `Scripts.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/Scripts.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/Scripts.txt#L23
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/Scripts.txt#L18-L21
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:34.659Z
 */
export interface Scripts {
  /**
   * Unicode code point range in the standard UCD format (e.g. '0000..10FFFF').
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/Scripts.txt#L23
   */
  code_point_range: string;

  /**
   * Script property value; all code points not explicitly listed have the value Unknown (Zzzz).
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/Scripts.txt#L18-L21
   */
  script: "Unknown" | string;
}

export const SCRIPTS_FIELDS = ["code_point_range", "script"];

// #endregion

// #region SpecialCasing.txt
/**
 * Parsed row from `SpecialCasing.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/SpecialCasing.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/SpecialCasing.txt#L32
 *
 * @unicodeVersion 15
 * @fields 6
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:53.577Z
 */
export interface SpecialCasing {
  /**
   * Unicode code point in hexadecimal.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/SpecialCasing.txt#L32
   */
  code: string;

  /**
   * Full lowercase mapping, expressed as one or more character values in hex separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/SpecialCasing.txt#L32
   */
  lower: string;

  /**
   * Full titlecase mapping, expressed as one or more character values in hex separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/SpecialCasing.txt#L32
   */
  title: string;

  /**
   * Full uppercase mapping, expressed as one or more character values in hex separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/SpecialCasing.txt#L32
   */
  upper: string;

  /**
   * Optional list of one or more language IDs or casing contexts separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/SpecialCasing.txt#L32
   */
  condition_list: string;

  /**
   * Informational comment.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/SpecialCasing.txt#L32
   */
  comment: string;
}

export const SPECIAL_CASING_FIELDS = ["code", "lower", "title", "upper", "condition_list", "comment"];

// #endregion

// #region StandardizedVariants.txt
/**
 * Parsed row from `StandardizedVariants.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/StandardizedVariants.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/StandardizedVariants.txt#L38
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/StandardizedVariants.txt#L39
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/StandardizedVariants.txt#L40-L42
 *
 * @unicodeVersion 15
 * @fields 3
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:39.065Z
 */
export interface StandardizedVariants {
  /**
   * the variation sequence
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/StandardizedVariants.txt#L38
   */
  variation_sequence: string;

  /**
   * the description of the desired appearance
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/StandardizedVariants.txt#L39
   */
  description: string;

  /**
   * where the appearance is only different in particular shaping environments; possible values are: isolate, initial, medial, final. If more than one is present, there are spaces between them.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/StandardizedVariants.txt#L40-L42
   */
  shaping_environments: "isolate" | "initial" | "medial" | "final";
}

export const STANDARDIZED_VARIANTS_FIELDS = ["variation_sequence", "description", "shaping_environments"];

// #endregion

// #region TangutSources.txt
/**
 * Parsed row from `TangutSources.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/TangutSources.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/TangutSources.txt#L20
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/TangutSources.txt#L21-L32
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/TangutSources.txt#L22
 *
 * @unicodeVersion 15
 * @fields 3
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:09.511Z
 */
export interface TangutSources {
  /**
   * the Tangut code point value in U+ format
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/TangutSources.txt#L20
   */
  tangut_code_point: string;

  /**
   * a tag indicating the type of information in the third field; current tags: kTGT_MergedSrc (Tangut Merged source), kRSTUnicode (Radical-Stroke indexes)
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/TangutSources.txt#L21-L32
   */
  tag: "kTGT_MergedSrc" | "kRSTUnicode" | (string & {});

  /**
   * the value (in UTF-8)
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/TangutSources.txt#L22
   */
  value: string;
}

export const TANGUT_SOURCES_FIELDS = ["tangut_code_point", "tag", "value"];

// #endregion

// #region UnicodeData.txt
/**
 * Parsed row from `UnicodeData.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/UnicodeData.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 15
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:41:51.149Z
 */
export interface UnicodeData {

}

export const UNICODE_DATA_FIELDS = [];

// #endregion

// #region USourceData.txt
/**
 * Parsed row from `USourceData.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/USourceData.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L12
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L13-L31
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L32-L35
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L36
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L37
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L38
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L39
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L40
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L41
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L42
 *
 * @unicodeVersion 15
 * @fields 10
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:23.352Z
 */
export interface USourceData {
  /**
   * The U-source ID
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L12
   */
  u_source_id: string;

  /**
   * Text indicating the ideograph's status
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L13-L31
   */
  status: "ExtA" | "ExtB" | "ExtC" | "Comp" | "ExtD" | "ExtE" | "ExtF" | "ExtG" | "ExtH" | "N" | "URO" | "UK-2015" | "V" | "W" | "WS-2017" | "WS-2021" | "X" | (string & {});

  /**
   * A Unicode code point specifying the encoded character for this entry, if any; otherwise the encoded character to which this entry is related, generally as a variant.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L32-L35
   */
  unicode_code_point: string;

  /**
   * Radical-stroke count
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L36
   */
  radical_stroke_count: string;

  /**
   * Virtual KangXi dictionary position
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L37
   */
  virtual_kang_xi_position: string;

  /**
   * Ideographic Description Sequence (IDS), if possible
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L38
   */
  ids: string;

  /**
   * Source(s)
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L39
   */
  sources: string;

  /**
   * General comments
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L40
   */
  general_comments: string;

  /**
   * Total strokes
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L41
   */
  total_strokes: string;

  /**
   * First residual stroke
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/USourceData.txt#L42
   */
  first_residual_stroke: string;
}

export const U_SOURCE_DATA_FIELDS = ["u_source_id", "status", "unicode_code_point", "radical_stroke_count", "virtual_kang_xi_position", "ids", "sources", "general_comments", "total_strokes", "first_residual_stroke"];

// #endregion

// #region VerticalOrientation.txt
/**
 * Parsed row from `VerticalOrientation.txt` (Unicode 15).
 *
 * @see https://unicode.org/Public/15.0.0/ucd/VerticalOrientation.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/VerticalOrientation.txt#L16-L17
 * - https://ucdjs.dev/file-explorer/v/15.0.0/ucd/VerticalOrientation.txt#L15-L22
 *
 * @unicodeVersion 15
 * @fields 2
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:54.222Z
 */
export interface VerticalOrientation {
  /**
   * Unicode code point value or range of code point values in hexadecimal form.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/VerticalOrientation.txt#L16-L17
   */
  code_point: string;

  /**
   * Vertical_Orientation property value: U=Upright, R=Rotated, Tu=Transformed typographically with fallback to Upright, Tr=Transformed typographically with fallback to Rotated.
   *
   * @source https://ucdjs.dev/file-explorer/v/15.0.0/ucd/VerticalOrientation.txt#L15-L22
   */
  vertical_orientation: "U" | "R" | "Tu" | "Tr";
}

export const VERTICAL_ORIENTATION_FIELDS = ["code_point", "vertical_orientation"];

// #endregion

