// This file is generated by scripts/codegen/generate-fields.ts. Do not edit directly.
// Unicode Version: 2.1.8
// Generated At: 2026-04-15T14:55:47.137Z
// Files: 7
//   - diff215v216.txt
//   - diff216v217.txt
//   - diff217v218.txt
//   - diff218v218d1.txt
//   - PropList-2.1.8.txt
//   - SpecialCasing-1.txt
//   - UnicodeData-2.1.8.txt

// #region diff215v216.txt
/**
 * Parsed row from `diff215v216.txt` (Unicode 2.1.8).
 *
 * @see https://unicode.org/Public/2.1-Update3/diff215v216.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 2.1.8
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:55:37.930Z
 */
export interface Diff215V216 {

}

export const DIFF215V216_FIELDS = [];

// #endregion

// #region diff216v217.txt
/**
 * Parsed row from `diff216v217.txt` (Unicode 2.1.8).
 *
 * @see https://unicode.org/Public/2.1-Update3/diff216v217.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 2.1.8
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:55:41.974Z
 */
export interface Diff216V217 {

}

export const DIFF216V217_FIELDS = [];

// #endregion

// #region diff217v218.txt
/**
 * Parsed row from `diff217v218.txt` (Unicode 2.1.8).
 *
 * @see https://unicode.org/Public/2.1-Update3/diff217v218.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 2.1.8
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:55:38.738Z
 */
export interface Diff217V218 {

}

export const DIFF217V218_FIELDS = [];

// #endregion

// #region diff218v218d1.txt
/**
 * Parsed row from `diff218v218d1.txt` (Unicode 2.1.8).
 *
 * @see https://unicode.org/Public/2.1-Update3/diff218v218d1.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 2.1.8
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:55:35.610Z
 */
export interface Diff218V218D1 {

}

export const DIFF218V218D1_FIELDS = [];

// #endregion

// #region PropList-2.1.8.txt
/**
 * Parsed row from `PropList-2.1.8.txt` (Unicode 2.1.8).
 *
 * @see https://unicode.org/Public/2.1-Update3/PropList-2.1.8.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 2.1.8
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:55:37.056Z
 */
export interface PropList218 {

}

export const PROP_LIST_218_FIELDS = [];

// #endregion

// #region SpecialCasing-1.txt
/**
 * Parsed row from `SpecialCasing-1.txt` (Unicode 2.1.8).
 *
 * @see https://unicode.org/Public/2.1-Update3/SpecialCasing-1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/2.1-Update3/SpecialCasing-1.txt#L20
 * - https://ucdjs.dev/file-explorer/v/2.1-Update3/SpecialCasing-1.txt#L18
 *
 * @unicodeVersion 2.1.8
 * @fields 6
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:39:12.855Z
 */
export interface SpecialCasing1 {
  /**
   * Source code point.
   *
   * @source https://ucdjs.dev/file-explorer/v/2.1-Update3/SpecialCasing-1.txt#L20
   */
  source: string;

  /**
   * Lowercase code point list.
   *
   * @source https://ucdjs.dev/file-explorer/v/2.1-Update3/SpecialCasing-1.txt#L20
   */
  lower: string;

  /**
   * Titlecase code point list.
   *
   * @source https://ucdjs.dev/file-explorer/v/2.1-Update3/SpecialCasing-1.txt#L20
   */
  title: string;

  /**
   * Uppercase code point list.
   *
   * @source https://ucdjs.dev/file-explorer/v/2.1-Update3/SpecialCasing-1.txt#L20
   */
  upper: string;

  /**
   * Optional condition list for locale or context-specific mappings.
   *
   * @source https://ucdjs.dev/file-explorer/v/2.1-Update3/SpecialCasing-1.txt#L18
   */
  condition_list: string;

  /**
   * Optional comment.
   *
   * @source https://ucdjs.dev/file-explorer/v/2.1-Update3/SpecialCasing-1.txt#L18
   */
  comment: string;
}

export const SPECIAL_CASING_1_FIELDS = ["source", "lower", "title", "upper", "condition_list", "comment"];

// #endregion

// #region UnicodeData-2.1.8.txt
/**
 * Parsed row from `UnicodeData-2.1.8.txt` (Unicode 2.1.8).
 *
 * @see https://unicode.org/Public/2.1-Update3/UnicodeData-2.1.8.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 2.1.8
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:55:47.137Z
 */
export interface UnicodeData218 {

}

export const UNICODE_DATA_218_FIELDS = [];

// #endregion
