// This file is generated by scripts/codegen/generate-fields.ts. Do not edit directly.
// Unicode Version: 2.1.5
// Generated At: 2026-04-23T16:49:49.770Z
// Files: 3
//   - diff212v214.txt
//   - diff214v215.txt
//   - UnicodeData-2.1.5.txt

// #region diff212v214.txt
/**
 * Parsed row from `diff212v214.txt` (Unicode 2.1.5).
 *
 * @see https://unicode.org/Public/2.1-Update2/diff212v214.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 2.1.5
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:49:48.387Z
 */
export interface Diff212V214 {

}

export const DIFF212V214_FIELDS = [];

// #endregion

// #region diff214v215.txt
/**
 * Parsed row from `diff214v215.txt` (Unicode 2.1.5).
 *
 * @see https://unicode.org/Public/2.1-Update2/diff214v215.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 2.1.5
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:49:49.720Z
 */
export interface Diff214V215 {

}

export const DIFF214V215_FIELDS = [];

// #endregion

// #region UnicodeData-2.1.5.txt
/**
 * Parsed row from `UnicodeData-2.1.5.txt` (Unicode 2.1.5).
 *
 * @see https://unicode.org/Public/2.1-Update2/UnicodeData-2.1.5.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 2.1.5
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:49:49.770Z
 */
export interface UnicodeData215 {

}

export const UNICODE_DATA_215_FIELDS = [];

// #endregion

