// This file is generated by scripts/codegen/generate-fields.ts. Do not edit directly.
// Unicode Version: 2
// Generated At: 2026-04-15T14:56:26.757Z
// Files: 9
//   - ArabicShaping-1.txt
//   - Blocks-1.txt
//   - Index-1.txt
//   - Jamo-1.txt
//   - NamesList-1.txt
//   - PropList-2.0.14.txt
//   - Props-2.0.14.txt
//   - UnicodeData-2.0.14.txt
//   - Unihan-1.txt

// #region ArabicShaping-1.txt
/**
 * Parsed row from `ArabicShaping-1.txt` (Unicode 2).
 *
 * @see https://unicode.org/Public/2.0-Update/ArabicShaping-1.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 2
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:55:49.255Z
 */
export interface ArabicShaping1 {

}

export const ARABIC_SHAPING_1_FIELDS = [];

// #endregion

// #region Blocks-1.txt
/**
 * Parsed row from `Blocks-1.txt` (Unicode 2).
 *
 * @see https://unicode.org/Public/2.0-Update/Blocks-1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/2.0-Update/Blocks-1.txt#L1
 *
 * @unicodeVersion 2
 * @fields 3
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:39:18.080Z
 */
export interface Blocks1 {
  /**
   * Starting Unicode code point.
   *
   * @source https://ucdjs.dev/file-explorer/v/2.0-Update/Blocks-1.txt#L1
   */
  start_code: string;

  /**
   * Ending Unicode code point.
   *
   * @source https://ucdjs.dev/file-explorer/v/2.0-Update/Blocks-1.txt#L1
   */
  end_code: string;

  /**
   * Name of the Unicode block.
   *
   * @source https://ucdjs.dev/file-explorer/v/2.0-Update/Blocks-1.txt#L1
   */
  block_name: string;
}

export const BLOCKS_1_FIELDS = ["start_code", "end_code", "block_name"];

// #endregion

// #region Index-1.txt
/**
 * Parsed row from `Index-1.txt` (Unicode 2).
 *
 * @see https://unicode.org/Public/2.0-Update/Index-1.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 2
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:56:02.200Z
 */
export interface Index1 {

}

export const INDEX_1_FIELDS = [];

// #endregion

// #region Jamo-1.txt
/**
 * Parsed row from `Jamo-1.txt` (Unicode 2).
 *
 * @see https://unicode.org/Public/2.0-Update/Jamo-1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/2.0-Update/Jamo-1.txt#L1
 *
 * @unicodeVersion 2
 * @fields 3
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:39:18.148Z
 */
export interface Jamo1 {
  /**
   * Value field.
   *
   * @source https://ucdjs.dev/file-explorer/v/2.0-Update/Jamo-1.txt#L1
   */
  value: string;

  /**
   * Short Name field.
   *
   * @source https://ucdjs.dev/file-explorer/v/2.0-Update/Jamo-1.txt#L1
   */
  short_name: string;

  /**
   * Unicode Name field.
   *
   * @source https://ucdjs.dev/file-explorer/v/2.0-Update/Jamo-1.txt#L1
   */
  unicode_name: string;
}

export const JAMO_1_FIELDS = ["value", "short_name", "unicode_name"];

// #endregion

// #region NamesList-1.txt
/**
 * Parsed row from `NamesList-1.txt` (Unicode 2).
 *
 * @see https://unicode.org/Public/2.0-Update/NamesList-1.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 2
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:56:14.161Z
 */
export interface NamesList1 {

}

export const NAMES_LIST_1_FIELDS = [];

// #endregion

// #region PropList-2.0.14.txt
/**
 * Parsed row from `PropList-2.0.14.txt` (Unicode 2).
 *
 * @see https://unicode.org/Public/2.0-Update/PropList-2.0.14.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 2
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:56:14.835Z
 */
export interface PropList2014 {

}

export const PROP_LIST_2014_FIELDS = [];

// #endregion

// #region Props-2.0.14.txt
/**
 * Parsed row from `Props-2.0.14.txt` (Unicode 2).
 *
 * @see https://unicode.org/Public/2.0-Update/Props-2.0.14.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 2
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:56:26.757Z
 */
export interface Props2014 {
  /**
   * Unicode code point or range.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Alphabetic binary property value.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  alphabetic: "Alphabetic";
}

export const PROPS_2014_FIELDS = ["code_point", "alphabetic"];

// #endregion

// #region UnicodeData-2.0.14.txt
/**
 * Parsed row from `UnicodeData-2.0.14.txt` (Unicode 2).
 *
 * @see https://unicode.org/Public/2.0-Update/UnicodeData-2.0.14.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 2
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:56:16.433Z
 */
export interface UnicodeData2014 {

}

export const UNICODE_DATA_2014_FIELDS = [];

// #endregion

// #region Unihan-1.txt
/**
 * Parsed row from `Unihan-1.txt` (Unicode 2).
 *
 * @see https://unicode.org/Public/2.0-Update/Unihan-1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/2.0-Update/Unihan-1.txt#L31-L34
 *
 * @unicodeVersion 2
 * @fields 3
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:39:27.773Z
 */
export interface Unihan1 {
  /**
   * The Unicode value as U+xxxx
   *
   * @source https://ucdjs.dev/file-explorer/v/2.0-Update/Unihan-1.txt#L31-L34
   */
  unicode_value: string;

  /**
   * A tag indicating the type of information in the third field
   *
   * @source https://ucdjs.dev/file-explorer/v/2.0-Update/Unihan-1.txt#L31-L34
   */
  tag: string;

  /**
   * The line's value
   *
   * @source https://ucdjs.dev/file-explorer/v/2.0-Update/Unihan-1.txt#L31-L34
   */
  value: string;
}

export const UNIHAN_1_FIELDS = ["unicode_value", "tag", "value"];

// #endregion
