// This file is generated by scripts/codegen/generate-fields.ts. Do not edit directly.
// Unicode Version: 3.0.1
// Generated At: 2026-04-23T16:49:40.035Z
// Files: 8
//   - ArabicShaping-3.txt
//   - BidiMirroring-1.txt
//   - CaseFolding-2.txt
//   - CompositionExclusions-2.txt
//   - Jamo-3.txt
//   - PropList-3.0.1.txt
//   - SpecialCasing-3.txt
//   - UnicodeData-3.0.1.txt

// #region ArabicShaping-3.txt
/**
 * Parsed row from `ArabicShaping-3.txt` (Unicode 3.0.1).
 *
 * @see https://unicode.org/Public/3.0-Update1/ArabicShaping-3.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/3.0-Update1/ArabicShaping-3.txt#L16-L17
 * - https://ucdjs.dev/file-explorer/v/3.0-Update1/ArabicShaping-3.txt#L18-L19
 * - https://ucdjs.dev/file-explorer/v/3.0-Update1/ArabicShaping-3.txt#L20-L21
 * - https://ucdjs.dev/file-explorer/v/3.0-Update1/ArabicShaping-3.txt#L22
 *
 * @unicodeVersion 3.0.1
 * @fields 4
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:49:28.685Z
 */
export interface ArabicShaping3 {
  /**
   * The code point, in 4-digit hexadecimal form, of an Arabic or Syriac character.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/ArabicShaping-3.txt#L16-L17
   */
  code_point: string;

  /**
   * A short schematic name for that character, abbreviated from the normative Unicode character name.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/ArabicShaping-3.txt#L18-L19
   */
  schematic_name: string;

  /**
   * The joining type: R right-joining, D dual-joining, U non-joining.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/ArabicShaping-3.txt#L20-L21
   */
  joining_type: "R" | "D" | "U";

  /**
   * The joining group.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/ArabicShaping-3.txt#L22
   */
  joining_group: string;
}

export const ARABIC_SHAPING_3_FIELDS = ["code_point", "schematic_name", "joining_type", "joining_group"];

// #endregion

// #region BidiMirroring-1.txt
/**
 * Parsed row from `BidiMirroring-1.txt` (Unicode 3.0.1).
 *
 * @see https://unicode.org/Public/3.0-Update1/BidiMirroring-1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/3.0-Update1/BidiMirroring-1.txt#L15-L17
 *
 * @unicodeVersion 3.0.1
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:49:29.032Z
 */
export interface BidiMirroring1 {
  /**
   * Code point that has the mirrored property.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/BidiMirroring-1.txt#L15-L17
   */
  source_code_point: string;

  /**
   * Code point that is the mirror image of the source code point's glyph.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/BidiMirroring-1.txt#L15-L17
   */
  mirror_code_point: string;
}

export const BIDI_MIRRORING_1_FIELDS = ["source_code_point", "mirror_code_point"];

// #endregion

// #region CaseFolding-2.txt
/**
 * Parsed row from `CaseFolding-2.txt` (Unicode 3.0.1).
 *
 * @see https://unicode.org/Public/3.0-Update1/CaseFolding-2.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/3.0-Update1/CaseFolding-2.txt#L23
 * - https://ucdjs.dev/file-explorer/v/3.0-Update1/CaseFolding-2.txt#L23-L27
 *
 * @unicodeVersion 3.0.1
 * @fields 4
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:49:31.578Z
 */
export interface CaseFolding2 {
  /**
   * Unicode code point in hexadecimal format.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/CaseFolding-2.txt#L23
   */
  code: string;

  /**
   * Status is L (for Lowercase) if the case mapping matches the standard 1-1 lowercase mapping, E (for exception) if it does not.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/CaseFolding-2.txt#L23-L27
   */
  status: "L" | "E";

  /**
   * Case folding mapping, which may consist of multiple characters separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/CaseFolding-2.txt#L23
   */
  mapping: string;

  /**
   * Character name.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/CaseFolding-2.txt#L23
   */
  name: string;
}

export const CASE_FOLDING_2_FIELDS = ["code", "status", "mapping", "name"];

// #endregion

// #region CompositionExclusions-2.txt
/**
 * Parsed row from `CompositionExclusions-2.txt` (Unicode 3.0.1).
 *
 * @see https://unicode.org/Public/3.0-Update1/CompositionExclusions-2.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr15/
 *
 * @unicodeVersion 3.0.1
 * @fields 1
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:49:27.255Z
 */
export interface CompositionExclusions2 {
  /**
   * Unicode code point or range listed in the Composition Exclusion Table from UTR #15.
   *
   * @source https://ucdjs.dev/reports/tr15/
   */
  code_point: string;
}

export const COMPOSITION_EXCLUSIONS_2_FIELDS = ["code_point"];

// #endregion

// #region Jamo-3.txt
/**
 * Parsed row from `Jamo-3.txt` (Unicode 3.0.1).
 *
 * @see https://unicode.org/Public/3.0-Update1/Jamo-3.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/3.0-Update1/Jamo-3.txt#L15-L17
 * - https://ucdjs.dev/file-explorer/v/3.0-Update1/Jamo-3.txt#L18-L20
 *
 * @unicodeVersion 3.0.1
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:49:28.987Z
 */
export interface Jamo3 {
  /**
   * Code point, in 4-digit hexadecimal form, of a combining jamo character.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/Jamo-3.txt#L15-L17
   */
  code_point: string;

  /**
   * Jamo Short Name as a one-, two-, or three-character ASCII string (or null string for U+110B).
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/Jamo-3.txt#L18-L20
   */
  jamo_short_name: string;
}

export const JAMO_3_FIELDS = ["code_point", "jamo_short_name"];

// #endregion

// #region PropList-3.0.1.txt
/**
 * Parsed row from `PropList-3.0.1.txt` (Unicode 3.0.1).
 *
 * @see https://unicode.org/Public/3.0-Update1/PropList-3.0.1.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 3.0.1
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:49:40.035Z
 */
export interface PropList301 {

}

export const PROP_LIST_301_FIELDS = [];

// #endregion

// #region SpecialCasing-3.txt
/**
 * Parsed row from `SpecialCasing-3.txt` (Unicode 3.0.1).
 *
 * @see https://unicode.org/Public/3.0-Update1/SpecialCasing-3.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/3.0-Update1/SpecialCasing-3.txt#L22
 * - https://ucdjs.dev/file-explorer/v/3.0-Update1/SpecialCasing-3.txt#L24
 * - https://ucdjs.dev/file-explorer/v/3.0-Update1/SpecialCasing-3.txt#L25
 * - https://ucdjs.dev/file-explorer/v/3.0-Update1/SpecialCasing-3.txt#L26
 * - https://ucdjs.dev/file-explorer/v/3.0-Update1/SpecialCasing-3.txt#L32
 * - https://ucdjs.dev/file-explorer/v/3.0-Update1/SpecialCasing-3.txt#L18
 *
 * @unicodeVersion 3.0.1
 * @fields 6
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:49:32.714Z
 */
export interface SpecialCasing3 {
  /**
   * Source code point.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/SpecialCasing-3.txt#L22
   */
  source: string;

  /**
   * Lowercase mapping code point list.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/SpecialCasing-3.txt#L24
   */
  lower: string;

  /**
   * Titlecase mapping code point list.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/SpecialCasing-3.txt#L25
   */
  title: string;

  /**
   * Uppercase mapping code point list.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/SpecialCasing-3.txt#L26
   */
  upper: string;

  /**
   * Optional condition list of locales and contexts.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/SpecialCasing-3.txt#L32
   */
  condition_list: string;

  /**
   * Optional comment.
   *
   * @source https://ucdjs.dev/file-explorer/v/3.0-Update1/SpecialCasing-3.txt#L18
   */
  comment: string;
}

export const SPECIAL_CASING_3_FIELDS = ["source", "lower", "title", "upper", "condition_list", "comment"];

// #endregion

// #region UnicodeData-3.0.1.txt
/**
 * Parsed row from `UnicodeData-3.0.1.txt` (Unicode 3.0.1).
 *
 * @see https://unicode.org/Public/3.0-Update1/UnicodeData-3.0.1.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 3.0.1
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:49:38.665Z
 */
export interface UnicodeData301 {

}

export const UNICODE_DATA_301_FIELDS = [];

// #endregion

