// This file is generated by scripts/codegen/generate-fields.ts. Do not edit directly.
// Unicode Version: 4.0.1
// Generated At: 2026-04-23T16:49:59.663Z
// Files: 28
//   - ArabicShaping-4.0.1.txt
//   - Blocks-4.0.1.txt
//   - CaseFolding-4.0.1.txt
//   - DerivedAge-4.0.1.txt
//   - DerivedCoreProperties-4.0.1.txt
//   - DerivedNormalizationProps-4.0.1.txt
//   - extracted/DerivedBidiClass-4.0.1.txt
//   - extracted/DerivedBinaryProperties-4.0.1.txt
//   - extracted/DerivedCombiningClass-4.0.1.txt
//   - extracted/DerivedDecompositionType-4.0.1.txt
//   - extracted/DerivedEastAsianWidth-4.0.1.txt
//   - extracted/DerivedGeneralCategory-4.0.1.txt
//   - extracted/DerivedJoiningGroup-4.0.1.txt
//   - extracted/DerivedJoiningType-4.0.1.txt
//   - extracted/DerivedLineBreak-4.0.1.txt
//   - extracted/DerivedNumericType-4.0.1.txt
//   - extracted/DerivedNumericValues-4.0.1.txt
//   - HangulSyllableType-4.0.1.txt
//   - Index-4.0.1.txt
//   - Jamo-4.0.1.txt
//   - LineBreak-4.0.1.txt
//   - PropertyAliases-4.0.1.txt
//   - PropertyValueAliases-4.0.1.txt
//   - PropList-4.0.1.txt
//   - Scripts-4.0.1.txt
//   - SpecialCasing-4.0.1.txt
//   - UnicodeData-4.0.1.txt
//   - Unihan-4.0.1.txt

// #region ArabicShaping-4.0.1.txt
/**
 * Parsed row from `ArabicShaping-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/ArabicShaping-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/ArabicShaping-4.0.1.txt#L16-L17
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/ArabicShaping-4.0.1.txt#L18-L19
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/ArabicShaping-4.0.1.txt#L20-L27
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/ArabicShaping-4.0.1.txt#L28
 *
 * @unicodeVersion 4.0.1
 * @fields 4
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:48:24.629Z
 */
export interface ArabicShaping401 {
  /**
   * The code point, in 4-digit hexadecimal form, of an Arabic or Syriac character.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/ArabicShaping-4.0.1.txt#L16-L17
   */
  code_point: string;

  /**
   * A short schematic name for that character, abbreviated from the normative Unicode character name.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/ArabicShaping-4.0.1.txt#L18-L19
   */
  schematic_name: string;

  /**
   * R right-joining, L left-joining, D dual-joining, C join-causing, U non-joining, T transparent.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/ArabicShaping-4.0.1.txt#L20-L27
   */
  joining_type: "R" | "L" | "D" | "C" | "U" | "T";

  /**
   * Joining group.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/ArabicShaping-4.0.1.txt#L28
   */
  joining_group: string;
}

export const ARABIC_SHAPING_401_FIELDS = ["code_point", "schematic_name", "joining_type", "joining_group"];

// #endregion

// #region Blocks-4.0.1.txt
/**
 * Parsed row from `Blocks-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/Blocks-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/Blocks-4.0.1.txt#L17
 *
 * @unicodeVersion 4.0.1
 * @fields 3
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:48:24.910Z
 */
export interface Blocks401 {
  /**
   * Start code point of the block range.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/Blocks-4.0.1.txt#L17
   */
  start_code: string;

  /**
   * End code point of the block range.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/Blocks-4.0.1.txt#L17
   */
  end_code: string;

  /**
   * Name of the Unicode block.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/Blocks-4.0.1.txt#L17
   */
  block_name: string;
}

export const BLOCKS_401_FIELDS = ["start_code", "end_code", "block_name"];

// #endregion

// #region CaseFolding-4.0.1.txt
/**
 * Parsed row from `CaseFolding-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/CaseFolding-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/CaseFolding-4.0.1.txt#L33
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/CaseFolding-4.0.1.txt#L33-L50
 *
 * @unicodeVersion 4.0.1
 * @fields 4
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:48:27.352Z
 */
export interface CaseFolding401 {
  /**
   * Unicode code point.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/CaseFolding-4.0.1.txt#L33
   */
  code: string;

  /**
   * Status field indicating the type of case folding: C (common), F (full), S (simple), T (special Turkic).
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/CaseFolding-4.0.1.txt#L33-L50
   */
  status: "C" | "F" | "S" | "T";

  /**
   * Case folding mapping; multiple characters separated by spaces for full mappings.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/CaseFolding-4.0.1.txt#L33
   */
  mapping: string;

  /**
   * Character name.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/CaseFolding-4.0.1.txt#L33
   */
  name: string;
}

export const CASE_FOLDING_401_FIELDS = ["code", "status", "mapping", "name"];

// #endregion

// #region DerivedAge-4.0.1.txt
/**
 * Parsed row from `DerivedAge-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/DerivedAge-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 4.0.1
 * @fields 3
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:48:52.758Z
 */
export interface DerivedAge401 {
  /**
   * Unicode code point or range.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Age property value: Unicode version in which the code point(s) were first assigned.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  age: string;

  /**
   * Optional comments following the age value.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  comments: string;
}

export const DERIVED_AGE_401_FIELDS = ["code_point", "age", "comments"];

// #endregion

// #region DerivedCoreProperties-4.0.1.txt
/**
 * Parsed row from `DerivedCoreProperties-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/DerivedCoreProperties-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:48:52.270Z
 */
export interface DerivedCoreProperties401 {
  /**
   * Unicode code point or range in hexadecimal notation.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Derived Math property value.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property: "Math";
}

export const DERIVED_CORE_PROPERTIES_401_FIELDS = ["code_point", "property"];

// #endregion

// #region DerivedNormalizationProps-4.0.1.txt
/**
 * Parsed row from `DerivedNormalizationProps-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/DerivedNormalizationProps-4.0.1.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 4.0.1
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:49:16.799Z
 */
export interface DerivedNormalizationProps401 {

}

export const DERIVED_NORMALIZATION_PROPS_401_FIELDS = [];

// #endregion

// #region extracted/DerivedBidiClass-4.0.1.txt
/**
 * Parsed row from `extracted/DerivedBidiClass-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/extracted/DerivedBidiClass-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedBidiClass-4.0.1.txt#L11-L14
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedBidiClass-4.0.1.txt#L11-L18
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:48:27.157Z
 */
export interface ExtractedDerivedBidiClass401 {
  /**
   * Unicode code point or range explicitly listed for Bidi_Class.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedBidiClass-4.0.1.txt#L11-L14
   */
  code_point: string;

  /**
   * Bidi class value (defaults to Left_To_Right (L) for unlisted code points).
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedBidiClass-4.0.1.txt#L11-L18
   */
  bidi_class: "Left_To_Right" | (string & {});
}

export const EXTRACTED_DERIVED_BIDI_CLASS_401_FIELDS = ["code_point", "bidi_class"];

// #endregion

// #region extracted/DerivedBinaryProperties-4.0.1.txt
/**
 * Parsed row from `extracted/DerivedBinaryProperties-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/extracted/DerivedBinaryProperties-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:49:17.489Z
 */
export interface ExtractedDerivedBinaryProperties401 {
  /**
   * Unicode code point or range in hex format listing characters with Bidi_Mirrored property.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Binary property name (Bidi_Mirrored).
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property: string;
}

export const EXTRACTED_DERIVED_BINARY_PROPERTIES_401_FIELDS = ["code_point", "property"];

// #endregion

// #region extracted/DerivedCombiningClass-4.0.1.txt
/**
 * Parsed row from `extracted/DerivedCombiningClass-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/extracted/DerivedCombiningClass-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedCombiningClass-4.0.1.txt#L11-L13
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedCombiningClass-4.0.1.txt#L15-L16
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:48:31.541Z
 */
export interface ExtractedDerivedCombiningClass401 {
  /**
   * Unicode code point range explicitly listed in this file.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedCombiningClass-4.0.1.txt#L11-L13
   */
  code_point_range: string;

  /**
   * Canonical_Combining_Class value; defaults to 0 (Not_Reordered) for unlisted code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedCombiningClass-4.0.1.txt#L15-L16
   */
  ccc: number;
}

export const EXTRACTED_DERIVED_COMBINING_CLASS_401_FIELDS = ["code_point_range", "ccc"];

// #endregion

// #region extracted/DerivedDecompositionType-4.0.1.txt
/**
 * Parsed row from `extracted/DerivedDecompositionType-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/extracted/DerivedDecompositionType-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedDecompositionType-4.0.1.txt#L11
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedDecompositionType-4.0.1.txt#L11-L14
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:48:31.847Z
 */
export interface ExtractedDerivedDecompositionType401 {
  /**
   * Unicode code point or range explicitly listed for Decomposition_Type.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedDecompositionType-4.0.1.txt#L11
   */
  code_point_range: string;

  /**
   * Decomposition_Type value from UnicodeData.txt field 5; default is None for unlisted code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedDecompositionType-4.0.1.txt#L11-L14
   */
  decomposition_type: "Canonical" | "Font" | "NoBreak" | "Initial" | "Medial" | "Final" | "Isolated" | "Circle" | "Super" | "Sub" | "Vertical" | "Wide" | "Narrow" | "Small" | "Square" | "Fraction" | "Compat" | (string & {});
}

export const EXTRACTED_DERIVED_DECOMPOSITION_TYPE_401_FIELDS = ["code_point_range", "decomposition_type"];

// #endregion

// #region extracted/DerivedEastAsianWidth-4.0.1.txt
/**
 * Parsed row from `extracted/DerivedEastAsianWidth-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/extracted/DerivedEastAsianWidth-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedEastAsianWidth-4.0.1.txt#L11
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedEastAsianWidth-4.0.1.txt#L11-L14
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:48:33.485Z
 */
export interface ExtractedDerivedEastAsianWidth401 {
  /**
   * Unicode code point or range explicitly listed for East_Asian_Width.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedEastAsianWidth-4.0.1.txt#L11
   */
  code_point_range: string;

  /**
   * East_Asian_Width property value (Neutral for unlisted code points).
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedEastAsianWidth-4.0.1.txt#L11-L14
   */
  east_asian_width: "Neutral";
}

export const EXTRACTED_DERIVED_EAST_ASIAN_WIDTH_401_FIELDS = ["code_point_range", "east_asian_width"];

// #endregion

// #region extracted/DerivedGeneralCategory-4.0.1.txt
/**
 * Parsed row from `extracted/DerivedGeneralCategory-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/extracted/DerivedGeneralCategory-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedGeneralCategory-4.0.1.txt#L11
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedGeneralCategory-4.0.1.txt#L15
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:49:04.106Z
 */
export interface ExtractedDerivedGeneralCategory401 {
  /**
   * Unicode code point or range with the General_Category property.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedGeneralCategory-4.0.1.txt#L11
   */
  code_point_range: string;

  /**
   * Value of the General_Category property.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedGeneralCategory-4.0.1.txt#L15
   */
  general_category: "Unassigned";
}

export const EXTRACTED_DERIVED_GENERAL_CATEGORY_401_FIELDS = ["code_point_range", "general_category"];

// #endregion

// #region extracted/DerivedJoiningGroup-4.0.1.txt
/**
 * Parsed row from `extracted/DerivedJoiningGroup-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/extracted/DerivedJoiningGroup-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedJoiningGroup-4.0.1.txt#L11-L14
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedJoiningGroup-4.0.1.txt#L11
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:49:04.388Z
 */
export interface ExtractedDerivedJoiningGroup401 {
  /**
   * Unicode code point or range explicitly listed for Joining_Group.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedJoiningGroup-4.0.1.txt#L11-L14
   */
  code_point: string;

  /**
   * Joining Group value from ArabicShaping.txt field 3.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedJoiningGroup-4.0.1.txt#L11
   */
  joining_group: string;
}

export const EXTRACTED_DERIVED_JOINING_GROUP_401_FIELDS = ["code_point", "joining_group"];

// #endregion

// #region extracted/DerivedJoiningType-4.0.1.txt
/**
 * Parsed row from `extracted/DerivedJoiningType-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/extracted/DerivedJoiningType-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedJoiningType-4.0.1.txt#L11-L14
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedJoiningType-4.0.1.txt#L18
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:49:36.210Z
 */
export interface ExtractedDerivedJoiningType401 {
  /**
   * Unicode code point or range (first line of each entry, implicit).
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedJoiningType-4.0.1.txt#L11-L14
   */
  code_point: string;

  /**
   * Derived Joining_Type value as described in ArabicShaping.txt.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedJoiningType-4.0.1.txt#L18
   */
  joining_type: "Join_Causing";
}

export const EXTRACTED_DERIVED_JOINING_TYPE_401_FIELDS = ["code_point", "joining_type"];

// #endregion

// #region extracted/DerivedLineBreak-4.0.1.txt
/**
 * Parsed row from `extracted/DerivedLineBreak-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/extracted/DerivedLineBreak-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedLineBreak-4.0.1.txt#L11-L14
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedLineBreak-4.0.1.txt#L11-L18
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:48:32.772Z
 */
export interface ExtractedDerivedLineBreak401 {
  /**
   * Unicode code point or range explicitly listed for Line_Break.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedLineBreak-4.0.1.txt#L11-L14
   */
  code_point: string;

  /**
   * Line_Break value Unknown (XX) for explicitly listed code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedLineBreak-4.0.1.txt#L11-L18
   */
  line_break: "XX";
}

export const EXTRACTED_DERIVED_LINE_BREAK_401_FIELDS = ["code_point", "line_break"];

// #endregion

// #region extracted/DerivedNumericType-4.0.1.txt
/**
 * Parsed row from `extracted/DerivedNumericType-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/extracted/DerivedNumericType-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedNumericType-4.0.1.txt#L11
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:49:35.570Z
 */
export interface ExtractedDerivedNumericType401 {
  /**
   * Unicode code point or range with explicit Numeric_Type listing.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedNumericType-4.0.1.txt#L11
   */
  code_point_range: string;

  /**
   * Numeric Type from UnicodeData.txt fields 6/7/8 plus Unihan.txt.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/extracted/DerivedNumericType-4.0.1.txt#L11
   */
  numeric_type: "Digit" | "Decimal" | "Numeric" | (string & {});
}

export const EXTRACTED_DERIVED_NUMERIC_TYPE_401_FIELDS = ["code_point_range", "numeric_type"];

// #endregion

// #region extracted/DerivedNumericValues-4.0.1.txt
/**
 * Parsed row from `extracted/DerivedNumericValues-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/extracted/DerivedNumericValues-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:49:08.567Z
 */
export interface ExtractedDerivedNumericValues401 {
  /**
   * Unicode code point or range.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Numeric value extracted from UnicodeData.txt fields 6, 7, or 8.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  numeric_value: string;
}

export const EXTRACTED_DERIVED_NUMERIC_VALUES_401_FIELDS = ["code_point", "numeric_value"];

// #endregion

// #region HangulSyllableType-4.0.1.txt
/**
 * Parsed row from `HangulSyllableType-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/HangulSyllableType-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 4.0.1
 * @fields 3
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:49:17.703Z
 */
export interface HangulSyllableType401 {
  /**
   * Unicode code point or range in hexadecimal notation.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Hangul_Syllable_Type property value such as Leading_Jamo.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  hangul_syllable_type: string;

  /**
   * Optional comment starting with #.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  comment: string;
}

export const HANGUL_SYLLABLE_TYPE_401_FIELDS = ["code_point", "hangul_syllable_type", "comment"];

// #endregion

// #region Index-4.0.1.txt
/**
 * Parsed row from `Index-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/Index-4.0.1.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 4.0.1
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:48:57.593Z
 */
export interface Index401 {

}

export const INDEX_401_FIELDS = [];

// #endregion

// #region Jamo-4.0.1.txt
/**
 * Parsed row from `Jamo-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/Jamo-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/Jamo-4.0.1.txt#L16-L18
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/Jamo-4.0.1.txt#L19-L21
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:49:23.660Z
 */
export interface Jamo401 {
  /**
   * 4-digit hexadecimal form of a combining jamo character that participates in the algorithmic determination Hangul syllable character names.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/Jamo-4.0.1.txt#L16-L18
   */
  code_point: string;

  /**
   * Jamo Short Name as a one-, two-, or three-character ASCII string (or the null string).
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/Jamo-4.0.1.txt#L19-L21
   */
  jamo_short_name: string;
}

export const JAMO_401_FIELDS = ["code_point", "jamo_short_name"];

// #endregion

// #region LineBreak-4.0.1.txt
/**
 * Parsed row from `LineBreak-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/LineBreak-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/LineBreak-4.0.1.txt#L8
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/LineBreak-4.0.1.txt#L7-L16
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:49:19.104Z
 */
export interface LineBreak401 {
  /**
   * Unicode value
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/LineBreak-4.0.1.txt#L8
   */
  unicode_value: string;

  /**
   * LineBreak property, consisting of one of the following values.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/LineBreak-4.0.1.txt#L7-L16
   */
  line_break_property: "BK" | "CR" | "LF" | "CM" | "SG" | "GL" | "CB" | "SP" | "ZW" | "NL" | "WJ" | "XX" | "OP" | "CL" | "QU" | "NS" | "EX" | "SY" | "IS" | "PR" | "PO" | "NU" | "AL" | "ID" | "IN" | "HY" | "BB" | "BA" | "SA" | "AI" | "B2";
}

export const LINE_BREAK_401_FIELDS = ["unicode_value", "line_break_property"];

// #endregion

// #region PropertyAliases-4.0.1.txt
/**
 * Parsed row from `PropertyAliases-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/PropertyAliases-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/PropertyAliases-4.0.1.txt#L20-L22
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/PropertyAliases-4.0.1.txt#L22
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:49:42.965Z
 */
export interface PropertyAliases401 {
  /**
   * The first field is an abbreviated name for the property.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/PropertyAliases-4.0.1.txt#L20-L22
   */
  abbreviated_name: string;

  /**
   * The second field is a long name.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/PropertyAliases-4.0.1.txt#L22
   */
  long_name: string;
}

export const PROPERTY_ALIASES_401_FIELDS = ["abbreviated_name", "long_name"];

// #endregion

// #region PropertyValueAliases-4.0.1.txt
/**
 * Parsed row from `PropertyValueAliases-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/PropertyValueAliases-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/PropertyValueAliases-4.0.1.txt#L21-L22
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/PropertyValueAliases-4.0.1.txt#L24-L25
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/PropertyValueAliases-4.0.1.txt#L27
 *
 * @unicodeVersion 4.0.1
 * @fields 3
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:48:43.299Z
 */
export interface PropertyValueAliases401 {
  /**
   * The property for which that property value name is used.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/PropertyValueAliases-4.0.1.txt#L21-L22
   */
  property: string;

  /**
   * An abbreviated name. If there is no abbreviated name available, the field is marked with "n/a".
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/PropertyValueAliases-4.0.1.txt#L24-L25
   */
  abbreviated_name: "n/a" | string;

  /**
   * A long name.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/PropertyValueAliases-4.0.1.txt#L27
   */
  long_name: string;
}

export const PROPERTY_VALUE_ALIASES_401_FIELDS = ["property", "abbreviated_name", "long_name"];

// #endregion

// #region PropList-4.0.1.txt
/**
 * Parsed row from `PropList-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/PropList-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:49:59.663Z
 */
export interface PropList401 {
  /**
   * Unicode code point or range (e.g. '0020' or '0020..007E').
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  codepoint_range: string;

  /**
   * Binary property name for which the code points have the value 'Yes'.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property: string;
}

export const PROP_LIST_401_FIELDS = ["codepoint_range", "property"];

// #endregion

// #region Scripts-4.0.1.txt
/**
 * Parsed row from `Scripts-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/Scripts-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr24/
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/Scripts-4.0.1.txt#L11-L14
 *
 * @unicodeVersion 4.0.1
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:49:25.406Z
 */
export interface Scripts401 {
  /**
   * Unicode code point or range.
   *
   * @source https://ucdjs.dev/reports/tr24/
   */
  code_point: string;

  /**
   * Script property value; unlisted code points have the value Common (Zyyy).
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/Scripts-4.0.1.txt#L11-L14
   */
  script: "Common" | "Zyyy" | (string & {});
}

export const SCRIPTS_401_FIELDS = ["code_point", "script"];

// #endregion

// #region SpecialCasing-4.0.1.txt
/**
 * Parsed row from `SpecialCasing-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/SpecialCasing-4.0.1.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update1/SpecialCasing-4.0.1.txt#L19
 *
 * @unicodeVersion 4.0.1
 * @fields 6
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:49:35.649Z
 */
export interface SpecialCasing401 {
  /**
   * Unicode code point(s) in hexadecimal format.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/SpecialCasing-4.0.1.txt#L19
   */
  code: string;

  /**
   * Lowercase mapping, one or more character values in hex separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/SpecialCasing-4.0.1.txt#L19
   */
  lower: string;

  /**
   * Titlecase mapping, one or more character values in hex separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/SpecialCasing-4.0.1.txt#L19
   */
  title: string;

  /**
   * Uppercase mapping, one or more character values in hex separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/SpecialCasing-4.0.1.txt#L19
   */
  upper: string;

  /**
   * Optional list of locales or contexts separated by spaces, may be preceded by 'Not_'.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/SpecialCasing-4.0.1.txt#L19
   */
  condition_list: string;

  /**
   * Informational comment.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update1/SpecialCasing-4.0.1.txt#L19
   */
  comment: string;
}

export const SPECIAL_CASING_401_FIELDS = ["code", "lower", "title", "upper", "condition_list", "comment"];

// #endregion

// #region UnicodeData-4.0.1.txt
/**
 * Parsed row from `UnicodeData-4.0.1.txt` (Unicode 4.0.1).
 *
 * @see https://unicode.org/Public/4.0-Update1/UnicodeData-4.0.1.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 4.0.1
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:49:23.686Z
 */
export interface UnicodeData401 {

}

export const UNICODE_DATA_401_FIELDS = [];

// #endregion

