// This file is generated by scripts/codegen/generate-fields.ts. Do not edit directly.
// Unicode Version: 4
// Generated At: 2026-04-15T14:54:26.824Z
// Files: 31
//   - ArabicShaping-4.0.0.txt
//   - BidiMirroring-4.0.0.txt
//   - Blocks-4.0.0.txt
//   - CaseFolding-4.0.0.txt
//   - CompositionExclusions-4.0.0.txt
//   - DerivedAge-4.0.0.txt
//   - DerivedCoreProperties-4.0.0.txt
//   - DerivedNormalizationProps-4.0.0.txt
//   - EastAsianWidth-4.0.0.txt
//   - extracted/DerivedBidiClass-4.0.0.txt
//   - extracted/DerivedBinaryProperties-4.0.0.txt
//   - extracted/DerivedCombiningClass-4.0.0.txt
//   - extracted/DerivedDecompositionType-4.0.0.txt
//   - extracted/DerivedEastAsianWidth-4.0.0.txt
//   - extracted/DerivedGeneralCategory-4.0.0.txt
//   - extracted/DerivedJoiningGroup-4.0.0.txt
//   - extracted/DerivedJoiningType-4.0.0.txt
//   - extracted/DerivedLineBreak-4.0.0.txt
//   - extracted/DerivedNumericType-4.0.0.txt
//   - extracted/DerivedNumericValues-4.0.0.txt
//   - HangulSyllableType-4.0.0.txt
//   - LineBreak-4.0.0.txt
//   - NamesList-4.0.0.txt
//   - NormalizationCorrections-4.0.0.txt
//   - PropertyAliases-4.0.0.txt
//   - PropertyValueAliases-4.0.0.txt
//   - PropList-4.0.0.txt
//   - Scripts-4.0.0.txt
//   - SpecialCasing-4.0.0.txt
//   - StandardizedVariants-4.0.0.txt
//   - UnicodeData-4.0.0.txt

// #region ArabicShaping-4.0.0.txt
/**
 * Parsed row from `ArabicShaping-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/ArabicShaping-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/ArabicShaping-4.0.0.txt#L16
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/ArabicShaping-4.0.0.txt#L18
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/ArabicShaping-4.0.0.txt#L20-L26
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/ArabicShaping-4.0.0.txt#L28
 *
 * @unicodeVersion 4
 * @fields 4
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:22.391Z
 */
export interface ArabicShaping400 {
  /**
   * the code point, in 4-digit hexadecimal form, of an Arabic or Syriac character.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/ArabicShaping-4.0.0.txt#L16
   */
  code_point: string;

  /**
   * a short schematic name for that character, abbreviated from the normative Unicode character name.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/ArabicShaping-4.0.0.txt#L18
   */
  name: string;

  /**
   * defines the joining type R right-joining, L left-joining, D dual-joining, C join-causing U non-joining T transparent.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/ArabicShaping-4.0.0.txt#L20-L26
   */
  joining_type: "R" | "L" | "D" | "C" | "U" | "T";

  /**
   * defines the joining group.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/ArabicShaping-4.0.0.txt#L28
   */
  joining_group: string;
}

export const ARABIC_SHAPING_400_FIELDS = ["code_point", "name", "joining_type", "joining_group"];

// #endregion

// #region BidiMirroring-4.0.0.txt
/**
 * Parsed row from `BidiMirroring-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/BidiMirroring-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/BidiMirroring-4.0.0.txt#L15-L17
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:25.308Z
 */
export interface BidiMirroring400 {
  /**
   * Code point represented as a variable-length hexadecimal value with 4 to 6 digits that has the mirrored property.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/BidiMirroring-4.0.0.txt#L15-L17
   */
  source_code_point: string;

  /**
   * Code point represented as a variable-length hexadecimal value with 4 to 6 digits that is the mirror image glyph mapping.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/BidiMirroring-4.0.0.txt#L15-L17
   */
  mirror_code_point: string;
}

export const BIDI_MIRRORING_400_FIELDS = ["source_code_point", "mirror_code_point"];

// #endregion

// #region Blocks-4.0.0.txt
/**
 * Parsed row from `Blocks-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/Blocks-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/Blocks-4.0.0.txt#L8
 *
 * @unicodeVersion 4
 * @fields 3
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:22.057Z
 */
export interface Blocks400 {
  /**
   * Starting code point of the block range.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/Blocks-4.0.0.txt#L8
   */
  start_code: string;

  /**
   * Ending code point of the block range.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/Blocks-4.0.0.txt#L8
   */
  end_code: string;

  /**
   * Name of the Unicode block.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/Blocks-4.0.0.txt#L8
   */
  block_name: string;
}

export const BLOCKS_400_FIELDS = ["start_code", "end_code", "block_name"];

// #endregion

// #region CaseFolding-4.0.0.txt
/**
 * Parsed row from `CaseFolding-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/CaseFolding-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/CaseFolding-4.0.0.txt#L29
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/CaseFolding-4.0.0.txt#L29-L36
 *
 * @unicodeVersion 4
 * @fields 4
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:22.857Z
 */
export interface CaseFolding400 {
  /**
   * Unicode code point.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/CaseFolding-4.0.0.txt#L29
   */
  code: string;

  /**
   * Status field indicating the type of case folding: C for common, F for full, S for simple, T for special Turkic.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/CaseFolding-4.0.0.txt#L29-L36
   */
  status: "C" | "F" | "S" | "T";

  /**
   * Case folding mapping; multiple characters separated by spaces for full mappings.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/CaseFolding-4.0.0.txt#L29
   */
  mapping: string;

  /**
   * Character name.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/CaseFolding-4.0.0.txt#L29
   */
  name: string;
}

export const CASE_FOLDING_400_FIELDS = ["code", "status", "mapping", "name"];

// #endregion

// #region CompositionExclusions-4.0.0.txt
/**
 * Parsed row from `CompositionExclusions-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/CompositionExclusions-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr15/
 *
 * @unicodeVersion 4
 * @fields 1
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:23.936Z
 */
export interface CompositionExclusions400 {
  /**
   * Unicode code point listed as a Composition Exclusion from the UAX #15 Composition Exclusion Table.
   *
   * @source https://ucdjs.dev/reports/tr15/
   */
  code_point: string;
}

export const COMPOSITION_EXCLUSIONS_400_FIELDS = ["code_point"];

// #endregion

// #region DerivedAge-4.0.0.txt
/**
 * Parsed row from `DerivedAge-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/DerivedAge-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:54:09.749Z
 */
export interface DerivedAge400 {
  /**
   * Unicode code point or range to which the age applies.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  codepoint_range: string;

  /**
   * Unicode version when the code points were first designated.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  age: string;
}

export const DERIVED_AGE_400_FIELDS = ["codepoint_range", "age"];

// #endregion

// #region DerivedCoreProperties-4.0.0.txt
/**
 * Parsed row from `DerivedCoreProperties-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/DerivedCoreProperties-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:54:09.733Z
 */
export interface DerivedCoreProperties400 {
  /**
   * Unicode code point or range where the derived property is true.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Derived core property name, such as Uppercase or Default_Ignorable_Code_Point.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property: string;
}

export const DERIVED_CORE_PROPERTIES_400_FIELDS = ["code_point", "property"];

// #endregion

// #region DerivedNormalizationProps-4.0.0.txt
/**
 * Parsed row from `DerivedNormalizationProps-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/DerivedNormalizationProps-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 4
 * @fields 5
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:54:13.313Z
 */
export interface DerivedNormalizationProps400 {
  /**
   * Unicode code point or range.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * NFC Quick Check property value.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  nfc_qc: "Yes" | "No" | "Maybe";

  /**
   * NFD Quick Check property value.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  nfd_qc: "Yes" | "No" | "Maybe";

  /**
   * NFKC Quick Check property value.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  nfkc_qc: "Yes" | "No" | "Maybe";

  /**
   * NFKD Quick Check property value.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  nfkd_qc: "Yes" | "No" | "Maybe";
}

export const DERIVED_NORMALIZATION_PROPS_400_FIELDS = ["code_point", "nfc_qc", "nfd_qc", "nfkc_qc", "nfkd_qc"];

// #endregion

// #region EastAsianWidth-4.0.0.txt
/**
 * Parsed row from `EastAsianWidth-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/EastAsianWidth-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/EastAsianWidth-4.0.0.txt#L8
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/EastAsianWidth-4.0.0.txt#L8-L10
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:34.307Z
 */
export interface EastAsianWidth400 {
  /**
   * Unicode value
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/EastAsianWidth-4.0.0.txt#L8
   */
  unicode_value: string;

  /**
   * East Asian Width property, consisting of one of the following values: "N", "A", "H", "W", "F", "Na"
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/EastAsianWidth-4.0.0.txt#L8-L10
   */
  east_asian_width: "N" | "A" | "H" | "W" | "F" | "Na";
}

export const EAST_ASIAN_WIDTH_400_FIELDS = ["unicode_value", "east_asian_width"];

// #endregion

// #region extracted/DerivedBidiClass-4.0.0.txt
/**
 * Parsed row from `extracted/DerivedBidiClass-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/extracted/DerivedBidiClass-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedBidiClass-4.0.0.txt#L13-L16
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedBidiClass-4.0.0.txt#L13
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:32.343Z
 */
export interface ExtractedDerivedBidiClass400 {
  /**
   * Unicode code point or range explicitly listed with non-default Bidi_Class.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedBidiClass-4.0.0.txt#L13-L16
   */
  code_point_range: string;

  /**
   * Bidi Class derived from UnicodeData.txt field 4.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedBidiClass-4.0.0.txt#L13
   */
  bidi_class: string;
}

export const EXTRACTED_DERIVED_BIDI_CLASS_400_FIELDS = ["code_point_range", "bidi_class"];

// #endregion

// #region extracted/DerivedBinaryProperties-4.0.0.txt
/**
 * Parsed row from `extracted/DerivedBinaryProperties-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/extracted/DerivedBinaryProperties-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedBinaryProperties-4.0.0.txt#L13-L16
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:32.535Z
 */
export interface ExtractedDerivedBinaryProperties400 {
  /**
   * Unicode code point or range explicitly listed as having Bidi_Mirrored property value other than the default N.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedBinaryProperties-4.0.0.txt#L13-L16
   */
  code_point: string;

  /**
   * BidiMirrored property value (Y for listed code points; default N for all others).
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedBinaryProperties-4.0.0.txt#L13-L16
   */
  bidi_mirrored: "Y";
}

export const EXTRACTED_DERIVED_BINARY_PROPERTIES_400_FIELDS = ["code_point", "bidi_mirrored"];

// #endregion

// #region extracted/DerivedCombiningClass-4.0.0.txt
/**
 * Parsed row from `extracted/DerivedCombiningClass-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/extracted/DerivedCombiningClass-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedCombiningClass-4.0.0.txt#L13-L16
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:32.713Z
 */
export interface ExtractedDerivedCombiningClass400 {
  /**
   * Unicode code point or range explicitly listed with non-default combining class.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedCombiningClass-4.0.0.txt#L13-L16
   */
  code_point_range: string;

  /**
   * Canonical combining class value from UnicodeData.txt field 3; default 0 for unlisted code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedCombiningClass-4.0.0.txt#L13-L16
   */
  combining_class: number;
}

export const EXTRACTED_DERIVED_COMBINING_CLASS_400_FIELDS = ["code_point_range", "combining_class"];

// #endregion

// #region extracted/DerivedDecompositionType-4.0.0.txt
/**
 * Parsed row from `extracted/DerivedDecompositionType-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/extracted/DerivedDecompositionType-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedDecompositionType-4.0.0.txt#L13-L16
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:34.167Z
 */
export interface ExtractedDerivedDecompositionType400 {
  /**
   * Unicode code point or range explicitly listed with a non-default Decomposition Type.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedDecompositionType-4.0.0.txt#L13-L16
   */
  code_point_range: string;

  /**
   * Decomposition Type property value; defaults to 'None' for unlisted code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedDecompositionType-4.0.0.txt#L13-L16
   */
  decomposition_type: "Canonical" | "Font" | "NoBreak" | "Initial" | "Medial" | "Final" | "Isolated" | "Circle" | "Super" | "Sub" | "Vertical" | "Wide" | "Narrow" | "Small" | "Square" | "Fraction" | "Compat";
}

export const EXTRACTED_DERIVED_DECOMPOSITION_TYPE_400_FIELDS = ["code_point_range", "decomposition_type"];

// #endregion

// #region extracted/DerivedEastAsianWidth-4.0.0.txt
/**
 * Parsed row from `extracted/DerivedEastAsianWidth-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/extracted/DerivedEastAsianWidth-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedEastAsianWidth-4.0.0.txt#L13-L16
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:37.250Z
 */
export interface ExtractedDerivedEastAsianWidth400 {
  /**
   * Unicode code point or range explicitly listed in this file.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedEastAsianWidth-4.0.0.txt#L13-L16
   */
  code_point_range: string;

  /**
   * East Asian Width property value (listing EastAsianWidth.txt, field 1); defaults to N for unlisted code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedEastAsianWidth-4.0.0.txt#L13-L16
   */
  east_asian_width: "F" | "H" | "W" | "Na" | "A" | "N";
}

export const EXTRACTED_DERIVED_EAST_ASIAN_WIDTH_400_FIELDS = ["code_point_range", "east_asian_width"];

// #endregion

// #region extracted/DerivedGeneralCategory-4.0.0.txt
/**
 * Parsed row from `extracted/DerivedGeneralCategory-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/extracted/DerivedGeneralCategory-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedGeneralCategory-4.0.0.txt#L13-L16
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:36.895Z
 */
export interface ExtractedDerivedGeneralCategory400 {
  /**
   * Unicode code point or range explicitly listed with a derived General_Category value.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedGeneralCategory-4.0.0.txt#L13-L16
   */
  code_point_range: string;

  /**
   * General Category property value; defaults to Cn for unlisted code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedGeneralCategory-4.0.0.txt#L13-L16
   */
  general_category: string;
}

export const EXTRACTED_DERIVED_GENERAL_CATEGORY_400_FIELDS = ["code_point_range", "general_category"];

// #endregion

// #region extracted/DerivedJoiningGroup-4.0.0.txt
/**
 * Parsed row from `extracted/DerivedJoiningGroup-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/extracted/DerivedJoiningGroup-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedJoiningGroup-4.0.0.txt#L13-L16
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedJoiningGroup-4.0.0.txt#L13
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:34.709Z
 */
export interface ExtractedDerivedJoiningGroup400 {
  /**
   * Unicode code point or range with Joining Group value other than NO_JOINING_GROUP.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedJoiningGroup-4.0.0.txt#L13-L16
   */
  code_point_range: string;

  /**
   * Joining Group as listed in ArabicShaping.txt field 3.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedJoiningGroup-4.0.0.txt#L13
   */
  joining_group: string;
}

export const EXTRACTED_DERIVED_JOINING_GROUP_400_FIELDS = ["code_point_range", "joining_group"];

// #endregion

// #region extracted/DerivedJoiningType-4.0.0.txt
/**
 * Parsed row from `extracted/DerivedJoiningType-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/extracted/DerivedJoiningType-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedJoiningType-4.0.0.txt#L13-L17
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:34.597Z
 */
export interface ExtractedDerivedJoiningType400 {
  /**
   * Unicode code point range explicitly listed in this derived property file.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedJoiningType-4.0.0.txt#L13-L17
   */
  code_point_range: string;

  /**
   * Derived Joining Type property value, where T indicates special type as described in ArabicShaping.txt and all unlisted code points have value U.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedJoiningType-4.0.0.txt#L13-L17
   */
  joining_type: "T" | "U";
}

export const EXTRACTED_DERIVED_JOINING_TYPE_400_FIELDS = ["code_point_range", "joining_type"];

// #endregion

// #region extracted/DerivedLineBreak-4.0.0.txt
/**
 * Parsed row from `extracted/DerivedLineBreak-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/extracted/DerivedLineBreak-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedLineBreak-4.0.0.txt#L13-L16
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:37.290Z
 */
export interface ExtractedDerivedLineBreak400 {
  /**
   * Unicode code point or range explicitly listed in this file.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedLineBreak-4.0.0.txt#L13-L16
   */
  code_point_range: string;

  /**
   * Line Break property value from LineBreak.txt field 1; defaults to XX for unlisted code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedLineBreak-4.0.0.txt#L13-L16
   */
  line_break: string;
}

export const EXTRACTED_DERIVED_LINE_BREAK_400_FIELDS = ["code_point_range", "line_break"];

// #endregion

// #region extracted/DerivedNumericType-4.0.0.txt
/**
 * Parsed row from `extracted/DerivedNumericType-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/extracted/DerivedNumericType-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedNumericType-4.0.0.txt#L13-L16
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:32.370Z
 */
export interface ExtractedDerivedNumericType400 {
  /**
   * Unicode code point or range explicitly listed with Numeric Type property.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedNumericType-4.0.0.txt#L13-L16
   */
  code_point_range: string;

  /**
   * Numeric Type from UnicodeData.txt fields 6/7/8 plus Unihan.txt; default value None.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/extracted/DerivedNumericType-4.0.0.txt#L13-L16
   */
  numeric_type: string;
}

export const EXTRACTED_DERIVED_NUMERIC_TYPE_400_FIELDS = ["code_point_range", "numeric_type"];

// #endregion

// #region extracted/DerivedNumericValues-4.0.0.txt
/**
 * Parsed row from `extracted/DerivedNumericValues-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/extracted/DerivedNumericValues-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:54:26.824Z
 */
export interface ExtractedDerivedNumericValues400 {
  /**
   * Unicode code point or range.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Numeric Values (from UnicodeData.txt, field 6/7/8)
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  numeric_value: string;
}

export const EXTRACTED_DERIVED_NUMERIC_VALUES_400_FIELDS = ["code_point", "numeric_value"];

// #endregion

// #region HangulSyllableType-4.0.0.txt
/**
 * Parsed row from `HangulSyllableType-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/HangulSyllableType-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/HangulSyllableType-4.0.0.txt#L13-L14
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/HangulSyllableType-4.0.0.txt#L12
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:26.286Z
 */
export interface HangulSyllableType400 {
  /**
   * Unicode code point or range explicitly listed with a non-default Hangul Syllable Type value.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/HangulSyllableType-4.0.0.txt#L13-L14
   */
  codepoint_range: string;

  /**
   * Hangul Syllable Type property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/HangulSyllableType-4.0.0.txt#L12
   */
  hangul_syllable_type: "L" | "V" | "T" | "LV" | "LVT";
}

export const HANGUL_SYLLABLE_TYPE_400_FIELDS = ["codepoint_range", "hangul_syllable_type"];

// #endregion

// #region LineBreak-4.0.0.txt
/**
 * Parsed row from `LineBreak-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/LineBreak-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/LineBreak-4.0.0.txt#L8
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/LineBreak-4.0.0.txt#L9-L16
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:36.168Z
 */
export interface LineBreak400 {
  /**
   * Unicode value
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/LineBreak-4.0.0.txt#L8
   */
  unicode_value: string;

  /**
   * LineBreak property, consisting of one of the following values.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/LineBreak-4.0.0.txt#L9-L16
   */
  line_break_property: "BK" | "CR" | "LF" | "CM" | "SG" | "GL" | "CB" | "SP" | "ZW" | "NL" | "WJ" | "XX" | "OP" | "CL" | "QU" | "NS" | "EX" | "SY" | "IS" | "PR" | "PO" | "NU" | "AL" | "ID" | "IN" | "HY" | "BB" | "BA" | "SA" | "AI" | "B2";
}

export const LINE_BREAK_400_FIELDS = ["unicode_value", "line_break_property"];

// #endregion

// #region NamesList-4.0.0.txt
/**
 * Parsed row from `NamesList-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/NamesList-4.0.0.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 4
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:54:18.731Z
 */
export interface NamesList400 {

}

export const NAMES_LIST_400_FIELDS = [];

// #endregion

// #region NormalizationCorrections-4.0.0.txt
/**
 * Parsed row from `NormalizationCorrections-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/NormalizationCorrections-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/NormalizationCorrections-4.0.0.txt#L29
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/NormalizationCorrections-4.0.0.txt#L30
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/NormalizationCorrections-4.0.0.txt#L31
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/NormalizationCorrections-4.0.0.txt#L32-L33
 *
 * @unicodeVersion 4
 * @fields 4
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:25.132Z
 */
export interface NormalizationCorrections400 {
  /**
   * Unicode code point
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/NormalizationCorrections-4.0.0.txt#L29
   */
  code_point: string;

  /**
   * Original (erroneous) decomposition
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/NormalizationCorrections-4.0.0.txt#L30
   */
  original_decomposition: string;

  /**
   * Corrected decomposition
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/NormalizationCorrections-4.0.0.txt#L31
   */
  corrected_decomposition: string;

  /**
   * Version of Unicode for which the correction was entered into UnicodeData.txt, in n.n.n format.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/NormalizationCorrections-4.0.0.txt#L32-L33
   */
  version: string;
}

export const NORMALIZATION_CORRECTIONS_400_FIELDS = ["code_point", "original_decomposition", "corrected_decomposition", "version"];

// #endregion

// #region PropertyAliases-4.0.0.txt
/**
 * Parsed row from `PropertyAliases-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/PropertyAliases-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/PropertyAliases-4.0.0.txt#L16-L17
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/PropertyAliases-4.0.0.txt#L18
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:29.453Z
 */
export interface PropertyAliases400 {
  /**
   * The first field is an abbreviated name for the property.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/PropertyAliases-4.0.0.txt#L16-L17
   */
  abbreviated_name: string;

  /**
   * The second field is a long name.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/PropertyAliases-4.0.0.txt#L18
   */
  long_name: string;
}

export const PROPERTY_ALIASES_400_FIELDS = ["abbreviated_name", "long_name"];

// #endregion

// #region PropertyValueAliases-4.0.0.txt
/**
 * Parsed row from `PropertyValueAliases-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/PropertyValueAliases-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/PropertyValueAliases-4.0.0.txt#L17-L20
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/PropertyValueAliases-4.0.0.txt#L21-L22
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/PropertyValueAliases-4.0.0.txt#L24
 *
 * @unicodeVersion 4
 * @fields 3
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:29.460Z
 */
export interface PropertyValueAliases400 {
  /**
   * The property for which that property value name is used.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/PropertyValueAliases-4.0.0.txt#L17-L20
   */
  property: string;

  /**
   * The abbreviated name. If there is no abbreviated name available, the field is marked with 'n/a'.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/PropertyValueAliases-4.0.0.txt#L21-L22
   */
  abbreviated_name: string;

  /**
   * The long name.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/PropertyValueAliases-4.0.0.txt#L24
   */
  long_name: string;
}

export const PROPERTY_VALUE_ALIASES_400_FIELDS = ["property", "abbreviated_name", "long_name"];

// #endregion

// #region PropList-4.0.0.txt
/**
 * Parsed row from `PropList-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/PropList-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:54:18.799Z
 */
export interface PropList400 {
  /**
   * Unicode code point or range in hexadecimal.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Name of the binary property listed in PropList.txt.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property: string;
}

export const PROP_LIST_400_FIELDS = ["code_point", "property"];

// #endregion

// #region Scripts-4.0.0.txt
/**
 * Parsed row from `Scripts-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/Scripts-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr24/
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/Scripts-4.0.0.txt#L11-L14
 *
 * @unicodeVersion 4
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:31.352Z
 */
export interface Scripts400 {
  /**
   * Unicode code point or range explicitly listed in the file.
   *
   * @source https://ucdjs.dev/reports/tr24/
   */
  code_point: string;

  /**
   * Script property value; unlisted code points have the default value COMMON.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/Scripts-4.0.0.txt#L11-L14
   */
  script: string;
}

export const SCRIPTS_400_FIELDS = ["code_point", "script"];

// #endregion

// #region SpecialCasing-4.0.0.txt
/**
 * Parsed row from `SpecialCasing-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/SpecialCasing-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/SpecialCasing-4.0.0.txt#L19
 *
 * @unicodeVersion 4
 * @fields 6
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:29.442Z
 */
export interface SpecialCasing400 {
  /**
   * Unicode code point in hexadecimal.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/SpecialCasing-4.0.0.txt#L19
   */
  code: string;

  /**
   * Lowercase mapping; one or more character values in hex, separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/SpecialCasing-4.0.0.txt#L19
   */
  lower: string;

  /**
   * Titlecase mapping; one or more character values in hex, separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/SpecialCasing-4.0.0.txt#L19
   */
  title: string;

  /**
   * Uppercase mapping; one or more character values in hex, separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/SpecialCasing-4.0.0.txt#L19
   */
  upper: string;

  /**
   * Optional list of locales or contexts separated by spaces, enclosed in parentheses.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/SpecialCasing-4.0.0.txt#L19
   */
  condition_list: string;

  /**
   * Informational comment.
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/SpecialCasing-4.0.0.txt#L19
   */
  comment: string;
}

export const SPECIAL_CASING_400_FIELDS = ["code", "lower", "title", "upper", "condition_list", "comment"];

// #endregion

// #region StandardizedVariants-4.0.0.txt
/**
 * Parsed row from `StandardizedVariants-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/StandardizedVariants-4.0.0.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/StandardizedVariants-4.0.0.txt#L14
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/StandardizedVariants-4.0.0.txt#L15
 * - https://ucdjs.dev/file-explorer/v/4.0-Update/StandardizedVariants-4.0.0.txt#L16-L18
 *
 * @unicodeVersion 4
 * @fields 3
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-15T14:38:28.491Z
 */
export interface StandardizedVariants400 {
  /**
   * the variation sequence
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/StandardizedVariants-4.0.0.txt#L14
   */
  variation_sequence: string;

  /**
   * the description of the desired appearance
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/StandardizedVariants-4.0.0.txt#L15
   */
  description: string;

  /**
   * where the appearance is only different in particular shaping environments; possible values: isolate, initial, medial, final (space-separated if multiple)
   *
   * @source https://ucdjs.dev/file-explorer/v/4.0-Update/StandardizedVariants-4.0.0.txt#L16-L18
   */
  shaping_environments: string;
}

export const STANDARDIZED_VARIANTS_400_FIELDS = ["variation_sequence", "description", "shaping_environments"];

// #endregion

// #region UnicodeData-4.0.0.txt
/**
 * Parsed row from `UnicodeData-4.0.0.txt` (Unicode 4).
 *
 * @see https://unicode.org/Public/4.0-Update/UnicodeData-4.0.0.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 4
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-15T14:54:16.670Z
 */
export interface UnicodeData400 {

}

export const UNICODE_DATA_400_FIELDS = [];

// #endregion
