// This file is generated by scripts/codegen/generate-fields.ts. Do not edit directly.
// Unicode Version: 8
// Generated At: 2026-04-23T16:46:39.277Z
// Files: 46
//   - ArabicShaping.txt
//   - auxiliary/GraphemeBreakProperty.txt
//   - auxiliary/SentenceBreakProperty.txt
//   - auxiliary/WordBreakProperty.txt
//   - BidiBrackets.txt
//   - BidiMirroring.txt
//   - Blocks.txt
//   - CaseFolding.txt
//   - CJKRadicals.txt
//   - CompositionExclusions.txt
//   - DerivedAge.txt
//   - DerivedCoreProperties.txt
//   - DerivedNormalizationProps.txt
//   - EastAsianWidth.txt
//   - EmojiSources.txt
//   - extracted/DerivedBidiClass.txt
//   - extracted/DerivedBinaryProperties.txt
//   - extracted/DerivedCombiningClass.txt
//   - extracted/DerivedDecompositionType.txt
//   - extracted/DerivedEastAsianWidth.txt
//   - extracted/DerivedGeneralCategory.txt
//   - extracted/DerivedJoiningGroup.txt
//   - extracted/DerivedJoiningType.txt
//   - extracted/DerivedLineBreak.txt
//   - extracted/DerivedNumericType.txt
//   - extracted/DerivedNumericValues.txt
//   - HangulSyllableType.txt
//   - Index.txt
//   - IndicPositionalCategory.txt
//   - IndicSyllabicCategory.txt
//   - Jamo.txt
//   - LineBreak.txt
//   - NameAliases.txt
//   - NamedSequences.txt
//   - NamedSequencesProv.txt
//   - NamesList.txt
//   - NormalizationCorrections.txt
//   - PropertyAliases.txt
//   - PropertyValueAliases.txt
//   - PropList.txt
//   - ScriptExtensions.txt
//   - Scripts.txt
//   - SpecialCasing.txt
//   - StandardizedVariants.txt
//   - UnicodeData.txt
//   - USourceData.txt

// #region ArabicShaping.txt
/**
 * Parsed row from `ArabicShaping.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/ArabicShaping.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/ArabicShaping.txt#L24-L26
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/ArabicShaping.txt#L28-L33
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/ArabicShaping.txt#L35-L41
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/ArabicShaping.txt#L50
 *
 * @unicodeVersion 8
 * @fields 4
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:29.264Z
 */
export interface ArabicShaping {
  /**
   * the code point, in 4-digit hexadecimal form, of an Arabic, Syriac, N'Ko, Mandaic, Mongolian, Phags-pa, Manichaean, Psalter Pahlavi, or other character.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/ArabicShaping.txt#L24-L26
   */
  code_point: string;

  /**
   * gives a short schematic name for that character. The schematic name is descriptive of the shape, based as consistently as possible on a name for the skeleton and then the diacritic marks applied to the skeleton, if any. Note that this schematic name is considered a comment, and does not constitute a formal property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/ArabicShaping.txt#L28-L33
   */
  schematic_name: string;

  /**
   * defines the joining type (property name: Joining_Type) R Right_Joining L Left_Joining D Dual_Joining C Join_Causing U Non_Joining T Transparent
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/ArabicShaping.txt#L35-L41
   */
  joining_type: "R" | "L" | "D" | "C" | "U" | "T";

  /**
   * defines the joining group (property name: Joining_Group)
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/ArabicShaping.txt#L50
   */
  joining_group: string;
}

export const ARABIC_SHAPING_FIELDS = ["code_point", "schematic_name", "joining_type", "joining_group"];

// #endregion

// #region auxiliary/GraphemeBreakProperty.txt
/**
 * Parsed row from `auxiliary/GraphemeBreakProperty.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/auxiliary/GraphemeBreakProperty.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr29/
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:31.103Z
 */
export interface AuxiliaryGraphemeBreakProperty {
  /**
   * Unicode code point or range explicitly listed for Grapheme_Cluster_Break.
   *
   * @source https://ucdjs.dev/reports/tr29/
   */
  code_point: string;

  /**
   * Grapheme_Cluster_Break property value; defaults to Other (XX) for unlisted code points.
   *
   * @source https://ucdjs.dev/reports/tr29/
   */
  grapheme_cluster_break: "Other" | (string & {});
}

export const AUXILIARY_GRAPHEME_BREAK_PROPERTY_FIELDS = ["code_point", "grapheme_cluster_break"];

// #endregion

// #region auxiliary/SentenceBreakProperty.txt
/**
 * Parsed row from `auxiliary/SentenceBreakProperty.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/auxiliary/SentenceBreakProperty.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/auxiliary/SentenceBreakProperty.txt#L11-L14
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:33.132Z
 */
export interface AuxiliarySentenceBreakProperty {
  /**
   * Unicode code point or range.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Sentence_Break property value; defaults to Other (XX) for unlisted code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/auxiliary/SentenceBreakProperty.txt#L11-L14
   */
  sentence_break: "ATerm" | "Close" | "CR" | "Extend" | "Format" | "LF" | "Lower" | "Numeric" | "OLetter" | "Other" | "SContinue" | "Sep" | "Sp" | "STerm" | "Upper";
}

export const AUXILIARY_SENTENCE_BREAK_PROPERTY_FIELDS = ["code_point", "sentence_break"];

// #endregion

// #region auxiliary/WordBreakProperty.txt
/**
 * Parsed row from `auxiliary/WordBreakProperty.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/auxiliary/WordBreakProperty.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr29/
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:32.360Z
 */
export interface AuxiliaryWordBreakProperty {
  /**
   * Unicode code point or range.
   *
   * @source https://ucdjs.dev/reports/tr29/
   */
  code_point: string;

  /**
   * Word_Break property value; defaults to Other (XX) for unlisted code points.
   *
   * @source https://ucdjs.dev/reports/tr29/
   */
  word_break: "ALetter" | "Double_Quote" | "CR" | "E_Base" | "E_Base_GAZ" | "E_Modifier" | "Extend" | "ExtendNumLet" | "Hebrew_Letter" | "Katakana" | "LE" | "LF" | "MidLetter" | "MidNum" | "MidNumLet" | "Newline" | "Numeric" | "Other" | "Perl" | "RI" | "Regional_Indicator" | "Single_Quote" | "WSegSpace" | "ZWJ" | (string & {});
}

export const AUXILIARY_WORD_BREAK_PROPERTY_FIELDS = ["code_point", "word_break"];

// #endregion

// #region BidiBrackets.txt
/**
 * Parsed row from `BidiBrackets.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/BidiBrackets.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/BidiBrackets.txt#L40
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/BidiBrackets.txt#L41
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/BidiBrackets.txt#L42-L45
 *
 * @unicodeVersion 8
 * @fields 3
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:31.829Z
 */
export interface BidiBrackets {
  /**
   * Unicode code point value, represented as a hexadecimal value.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/BidiBrackets.txt#L40
   */
  code_point: string;

  /**
   * Bidi_Paired_Bracket property value, a code point value or <none>.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/BidiBrackets.txt#L41
   */
  bidi_paired_bracket: string;

  /**
   * Bidi_Paired_Bracket_Type property value: o=Open, c=Close, n=None.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/BidiBrackets.txt#L42-L45
   */
  bidi_paired_bracket_type: "o" | "c" | "n";
}

export const BIDI_BRACKETS_FIELDS = ["code_point", "bidi_paired_bracket", "bidi_paired_bracket_type"];

// #endregion

// #region BidiMirroring.txt
/**
 * Parsed row from `BidiMirroring.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/BidiMirroring.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/BidiMirroring.txt#L24-L26
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:31.244Z
 */
export interface BidiMirroring {
  /**
   * Code point represented as a variable-length hexadecimal value with 4 to 6 digits that has the Bidi_Mirrored=Yes property.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/BidiMirroring.txt#L24-L26
   */
  source_codepoint: string;

  /**
   * Code point represented as a variable-length hexadecimal value with 4 to 6 digits that typically has a glyph that is the mirror image of the source code point's glyph.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/BidiMirroring.txt#L24-L26
   */
  mirror_codepoint: string;
}

export const BIDI_MIRRORING_FIELDS = ["source_codepoint", "mirror_codepoint"];

// #endregion

// #region Blocks.txt
/**
 * Parsed row from `Blocks.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/Blocks.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/Blocks.txt#L10
 *
 * @unicodeVersion 8
 * @fields 3
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:29.353Z
 */
export interface Blocks {
  /**
   * Start of the code point range in hexadecimal notation.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/Blocks.txt#L10
   */
  start_code: string;

  /**
   * End of the code point range in hexadecimal notation.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/Blocks.txt#L10
   */
  end_code: string;

  /**
   * Name of the Unicode block.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/Blocks.txt#L10
   */
  block_name: string;
}

export const BLOCKS_FIELDS = ["start_code", "end_code", "block_name"];

// #endregion

// #region CaseFolding.txt
/**
 * Parsed row from `CaseFolding.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/CaseFolding.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/CaseFolding.txt#L35
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/CaseFolding.txt#L35-L53
 *
 * @unicodeVersion 8
 * @fields 4
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:32.252Z
 */
export interface CaseFolding {
  /**
   * Unicode code point in hexadecimal format.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/CaseFolding.txt#L35
   */
  code: string;

  /**
   * Status field indicating the type of case folding: C for common, F for full, S for simple, T for special Turkic cases.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/CaseFolding.txt#L35-L53
   */
  status: "C" | "F" | "S" | "T";

  /**
   * Case folding mapping, which may be a single code point or multiple separated by spaces for full mappings.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/CaseFolding.txt#L35
   */
  mapping: string;

  /**
   * Character name or comment.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/CaseFolding.txt#L35
   */
  name: string;
}

export const CASE_FOLDING_FIELDS = ["code", "status", "mapping", "name"];

// #endregion

// #region CJKRadicals.txt
/**
 * Parsed row from `CJKRadicals.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/CJKRadicals.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/CJKRadicals.txt#L19-L20
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/CJKRadicals.txt#L20
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/CJKRadicals.txt#L21
 *
 * @unicodeVersion 8
 * @fields 3
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:34.501Z
 */
export interface CjkRadicals {
  /**
   * The radical number matching the regular expression [1-9][0-9]{0,2}'?.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/CJKRadicals.txt#L19-L20
   */
  radical_number: string;

  /**
   * The CJK radical character from the Kangxi Radicals block or the CJK Radicals Supplement block.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/CJKRadicals.txt#L20
   */
  cjk_radical_character: string;

  /**
   * The CJK unified ideograph which is formed from that radical only.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/CJKRadicals.txt#L21
   */
  cjk_unified_ideograph: string;
}

export const CJK_RADICALS_FIELDS = ["radical_number", "cjk_radical_character", "cjk_unified_ideograph"];

// #endregion

// #region CompositionExclusions.txt
/**
 * Parsed row from `CompositionExclusions.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/CompositionExclusions.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr15/
 *
 * @unicodeVersion 8
 * @fields 1
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:37.043Z
 */
export interface CompositionExclusions {
  /**
   * Unicode code point listed for the Composition Exclusion Table as defined in UAX #15.
   *
   * @source https://ucdjs.dev/reports/tr15/
   */
  code_point: string;
}

export const COMPOSITION_EXCLUSIONS_FIELDS = ["code_point"];

// #endregion

// #region DerivedAge.txt
/**
 * Parsed row from `DerivedAge.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/DerivedAge.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/DerivedAge.txt#L36
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:40.931Z
 */
export interface DerivedAge {
  /**
   * Unicode code point or range first assigned in the specified version.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/DerivedAge.txt#L36
   */
  code_point_range: string;

  /**
   * Age property value indicating Unicode version when code points were first assigned.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/DerivedAge.txt#L36
   */
  age: "V1_1" | "V1_1_5" | "V2_0" | "V2_1" | "V3_0" | "V3_1" | "V3_2" | "V4_0" | "V4_1" | "V5_0" | "V5_1" | "V5_2" | "V6_0" | "V6_1" | "V6_2" | "V6_3" | "V7_0" | "V8_0" | "V9_0" | "V10_0" | "V11_0" | "V12_0" | "V12_1" | "V13_0" | "V14_0" | "V15_0" | "V15_1" | "V16_0" | (string & {});
}

export const DERIVED_AGE_FIELDS = ["code_point_range", "age"];

// #endregion

// #region DerivedCoreProperties.txt
/**
 * Parsed row from `DerivedCoreProperties.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/DerivedCoreProperties.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:45:10.658Z
 */
export interface DerivedCoreProperties {
  /**
   * Unicode code point or range in hexadecimal notation.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Derived core property name indicating the binary property value is Yes for the code point(s).
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property: string;
}

export const DERIVED_CORE_PROPERTIES_FIELDS = ["code_point", "property"];

// #endregion

// #region DerivedNormalizationProps.txt
/**
 * Parsed row from `DerivedNormalizationProps.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/DerivedNormalizationProps.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 8
 * @fields 4
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:45:15.671Z
 */
export interface DerivedNormalizationProps {
  /**
   * Hexadecimal code point whose normalization closure is being specified.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Derived normalization property name.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property: "FC_NFKC_Closure";

  /**
   * Space-separated list of hexadecimal code points constituting the closure.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  closure: string;

  /**
   * Optional comment providing additional information.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  comment: string;
}

export const DERIVED_NORMALIZATION_PROPS_FIELDS = ["code_point", "property", "closure", "comment"];

// #endregion

// #region EastAsianWidth.txt
/**
 * Parsed row from `EastAsianWidth.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/EastAsianWidth.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/EastAsianWidth.txt#L13
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/EastAsianWidth.txt#L14-L15
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:34.642Z
 */
export interface EastAsianWidth {
  /**
   * Unicode code point value or range of code point values.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/EastAsianWidth.txt#L13
   */
  code_point: string;

  /**
   * East_Asian_Width property, consisting of one of the following values: "N", "A", "H", "W", "F", "Na".
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/EastAsianWidth.txt#L14-L15
   */
  east_asian_width: "N" | "A" | "H" | "W" | "F" | "Na";
}

export const EAST_ASIAN_WIDTH_FIELDS = ["code_point", "east_asian_width"];

// #endregion

// #region EmojiSources.txt
/**
 * Parsed row from `EmojiSources.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/EmojiSources.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/EmojiSources.txt#L25
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/EmojiSources.txt#L26
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/EmojiSources.txt#L27
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/EmojiSources.txt#L28
 *
 * @unicodeVersion 8
 * @fields 4
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:35.260Z
 */
export interface EmojiSources {
  /**
   * Unicode code point or sequence.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/EmojiSources.txt#L25
   */
  unicode_code_point_or_sequence: string;

  /**
   * DoCoMo Shift-JIS code.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/EmojiSources.txt#L26
   */
  docomo_shift_jis_code: string;

  /**
   * KDDI Shift-JIS code.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/EmojiSources.txt#L27
   */
  kddi_shift_jis_code: string;

  /**
   * SoftBank Shift-JIS code.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/EmojiSources.txt#L28
   */
  softbank_shift_jis_code: string;
}

export const EMOJI_SOURCES_FIELDS = ["unicode_code_point_or_sequence", "docomo_shift_jis_code", "kddi_shift_jis_code", "softbank_shift_jis_code"];

// #endregion

// #region extracted/DerivedBidiClass.txt
/**
 * Parsed row from `extracted/DerivedBidiClass.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/extracted/DerivedBidiClass.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedBidiClass.txt#L11
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:38.685Z
 */
export interface ExtractedDerivedBidiClass {
  /**
   * Unicode code point or range explicitly listed for Bidi_Class.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedBidiClass.txt#L11
   */
  code_point: string;

  /**
   * Bidi Class property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedBidiClass.txt#L11
   */
  bidi_class: "L" | "R" | "AL" | "ET" | "BN" | (string & {});
}

export const EXTRACTED_DERIVED_BIDI_CLASS_FIELDS = ["code_point", "bidi_class"];

// #endregion

// #region extracted/DerivedBinaryProperties.txt
/**
 * Parsed row from `extracted/DerivedBinaryProperties.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/extracted/DerivedBinaryProperties.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 8
 * @fields 3
 * @confidence 0.80
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:45:04.108Z
 */
export interface ExtractedDerivedBinaryProperties {
  /**
   * Code point or range of code points.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point_range: string;

  /**
   * Name of the binary property.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property: string;

  /**
   * Binary status value: Y (Yes) or N (No).
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  status: "Y" | "N";
}

export const EXTRACTED_DERIVED_BINARY_PROPERTIES_FIELDS = ["code_point_range", "property", "status"];

// #endregion

// #region extracted/DerivedCombiningClass.txt
/**
 * Parsed row from `extracted/DerivedCombiningClass.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/extracted/DerivedCombiningClass.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedCombiningClass.txt#L11-L20
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:44.825Z
 */
export interface ExtractedDerivedCombiningClass {
  /**
   * Unicode code point or range with explicit Canonical_Combining_Class value.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedCombiningClass.txt#L11-L20
   */
  code_point_range: string;

  /**
   * Canonical Combining Class value; unlisted code points have value Not_Reordered (0).
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedCombiningClass.txt#L11-L20
   */
  combining_class: "Not_Reordered" | number;
}

export const EXTRACTED_DERIVED_COMBINING_CLASS_FIELDS = ["code_point_range", "combining_class"];

// #endregion

// #region extracted/DerivedDecompositionType.txt
/**
 * Parsed row from `extracted/DerivedDecompositionType.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/extracted/DerivedDecompositionType.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedDecompositionType.txt#L11-L14
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedDecompositionType.txt#L11
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:49.143Z
 */
export interface ExtractedDerivedDecompositionType {
  /**
   * Unicode code point or range explicitly listed with a Decomposition_Type value other than the default None.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedDecompositionType.txt#L11-L14
   */
  code_point_range: string;

  /**
   * Decomposition_Type values from UnicodeData.txt field 5.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedDecompositionType.txt#L11
   */
  decomposition_type: "Canonical" | "Font" | "NoBreak" | "Initial" | "Medial" | "Final" | "Isolated" | "Circle" | "Super" | "Sub" | "Vertical" | "Wide" | "Narrow" | "Small" | "Square" | "Fraction" | "Compat" | (string & {});
}

export const EXTRACTED_DERIVED_DECOMPOSITION_TYPE_FIELDS = ["code_point_range", "decomposition_type"];

// #endregion

// #region extracted/DerivedEastAsianWidth.txt
/**
 * Parsed row from `extracted/DerivedEastAsianWidth.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/extracted/DerivedEastAsianWidth.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedEastAsianWidth.txt#L11
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:45:22.381Z
 */
export interface ExtractedDerivedEastAsianWidth {
  /**
   * Unicode code point or range.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point_range: string;

  /**
   * East_Asian_Width property value (listing EastAsianWidth.txt, field 1).
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedEastAsianWidth.txt#L11
   */
  east_asian_width: "F" | "H" | "W" | "Na" | "A" | "N";
}

export const EXTRACTED_DERIVED_EAST_ASIAN_WIDTH_FIELDS = ["code_point_range", "east_asian_width"];

// #endregion

// #region extracted/DerivedGeneralCategory.txt
/**
 * Parsed row from `extracted/DerivedGeneralCategory.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/extracted/DerivedGeneralCategory.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:46:17.869Z
 */
export interface ExtractedDerivedGeneralCategory {
  /**
   * Unicode code point or range in hexadecimal format.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point_range: string;

  /**
   * General_Category property value.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  general_category: string;
}

export const EXTRACTED_DERIVED_GENERAL_CATEGORY_FIELDS = ["code_point_range", "general_category"];

// #endregion

// #region extracted/DerivedJoiningGroup.txt
/**
 * Parsed row from `extracted/DerivedJoiningGroup.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/extracted/DerivedJoiningGroup.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedJoiningGroup.txt#L16
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedJoiningGroup.txt#L13-L14
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:43.240Z
 */
export interface ExtractedDerivedJoiningGroup {
  /**
   * Code point range with the Joining_Group property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedJoiningGroup.txt#L16
   */
  code_point_range: string;

  /**
   * Default value for all code points not explicitly listed as having a Joining_Group.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedJoiningGroup.txt#L13-L14
   */
  joining_group: "No_Joining_Group";
}

export const EXTRACTED_DERIVED_JOINING_GROUP_FIELDS = ["code_point_range", "joining_group"];

// #endregion

// #region extracted/DerivedJoiningType.txt
/**
 * Parsed row from `extracted/DerivedJoiningType.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/extracted/DerivedJoiningType.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedJoiningType.txt#L16
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedJoiningType.txt#L11
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:42.363Z
 */
export interface ExtractedDerivedJoiningType {
  /**
   * Unicode code point or range explicitly listed with a Joining_Type value other than the default Non_Joining.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedJoiningType.txt#L16
   */
  code_point_range: string;

  /**
   * Joining_Type property value, derived as described in ArabicShaping.txt.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedJoiningType.txt#L11
   */
  joining_type: "Join_Causing" | (string & {});
}

export const EXTRACTED_DERIVED_JOINING_TYPE_FIELDS = ["code_point_range", "joining_type"];

// #endregion

// #region extracted/DerivedLineBreak.txt
/**
 * Parsed row from `extracted/DerivedLineBreak.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/extracted/DerivedLineBreak.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr14/
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedLineBreak.txt#L11-L14
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:46.436Z
 */
export interface ExtractedDerivedLineBreak {
  /**
   * Unicode code point or range explicitly listed for Line_Break.
   *
   * @source https://ucdjs.dev/reports/tr14/
   */
  code_point_range: string;

  /**
   * Line_Break property value; defaults to Unknown (XX) for unlisted code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedLineBreak.txt#L11-L14
   */
  line_break: "Unknown" | (string & {});
}

export const EXTRACTED_DERIVED_LINE_BREAK_FIELDS = ["code_point_range", "line_break"];

// #endregion

// #region extracted/DerivedNumericType.txt
/**
 * Parsed row from `extracted/DerivedNumericType.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/extracted/DerivedNumericType.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedNumericType.txt#L11-L19
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:45:17.852Z
 */
export interface ExtractedDerivedNumericType {
  /**
   * Unicode code point or range explicitly listed with a Numeric_Type value other than the default None.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedNumericType.txt#L11-L19
   */
  code_point: string;

  /**
   * Derived Numeric_Type property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedNumericType.txt#L11-L19
   */
  numeric_type: "Decimal" | "Digit" | "Numeric" | "None";
}

export const EXTRACTED_DERIVED_NUMERIC_TYPE_FIELDS = ["code_point", "numeric_type"];

// #endregion

// #region extracted/DerivedNumericValues.txt
/**
 * Parsed row from `extracted/DerivedNumericValues.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/extracted/DerivedNumericValues.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedNumericValues.txt#L12-L18
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedNumericValues.txt#L19-L20
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedNumericValues.txt#L22-L30
 *
 * @unicodeVersion 8
 * @fields 3
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:55.011Z
 */
export interface ExtractedDerivedNumericValues {
  /**
   * The values are based on field 8 of UnicodeData.txt, plus the fields kAccountingNumeric, kOtherNumeric, kPrimaryNumeric in the Unicode Han Database (Unihan). The derivations for these values are as follows: Numeric_Value = the value of kAccountingNumeric, kOtherNumeric, or kPrimaryNumeric, if they exist; otherwise Numeric_Value = the value of field 8, if it exists; otherwise Numeric_Value = NaN.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedNumericValues.txt#L12-L18
   */
  numeric_value: string;

  /**
   * This field is empty; it used to be a copy of the numeric type.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedNumericValues.txt#L19-L20
   */
  unused_numeric_type: string;

  /**
   * Expressing the same numeric value either as a whole integer where possible, or as a rational fraction such as "1/6". Certain values, such as 0.16666667, are repeating fractions. Although they are only printed with a limited number of decimal places in this file, they should be expressed to the limits of the precision available when used.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/extracted/DerivedNumericValues.txt#L22-L30
   */
  numeric_value_fraction: string;
}

export const EXTRACTED_DERIVED_NUMERIC_VALUES_FIELDS = ["numeric_value", "unused_numeric_type", "numeric_value_fraction"];

// #endregion

// #region HangulSyllableType.txt
/**
 * Parsed row from `HangulSyllableType.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/HangulSyllableType.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/HangulSyllableType.txt#L11-L14
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:45:00.852Z
 */
export interface HangulSyllableType {
  /**
   * Unicode code point or range explicitly listed as having a specific Hangul_Syllable_Type value.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/HangulSyllableType.txt#L11-L14
   */
  code_point: string;

  /**
   * Value of the Hangul_Syllable_Type property; all unlisted code points have value Not_Applicable.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/HangulSyllableType.txt#L11-L14
   */
  hangul_syllable_type: "Leading_Jamo" | "Trailing_Jamo" | "Vowel_Jamo" | "LVT_Syllable" | "LV_Syllable" | (string & {});
}

export const HANGUL_SYLLABLE_TYPE_FIELDS = ["code_point", "hangul_syllable_type"];

// #endregion

// #region Index.txt
/**
 * Parsed row from `Index.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/Index.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 8
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:45:48.130Z
 */
export interface Index {

}

export const INDEX_FIELDS = [];

// #endregion

// #region IndicPositionalCategory.txt
/**
 * Parsed row from `IndicPositionalCategory.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/IndicPositionalCategory.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/IndicPositionalCategory.txt#L47-L48
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/IndicPositionalCategory.txt#L48
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:46:24.154Z
 */
export interface IndicPositionalCategory {
  /**
   * Unicode code point value or range of code point values
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/IndicPositionalCategory.txt#L47-L48
   */
  code_point: string;

  /**
   * Indic_Positional_Category property value
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/IndicPositionalCategory.txt#L48
   */
  indic_positional_category: string;
}

export const INDIC_POSITIONAL_CATEGORY_FIELDS = ["code_point", "indic_positional_category"];

// #endregion

// #region IndicSyllabicCategory.txt
/**
 * Parsed row from `IndicSyllabicCategory.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/IndicSyllabicCategory.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/IndicSyllabicCategory.txt#L27
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/IndicSyllabicCategory.txt#L28
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:50.743Z
 */
export interface IndicSyllabicCategory {
  /**
   * Unicode code point value or range of code point values
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/IndicSyllabicCategory.txt#L27
   */
  code_point: string;

  /**
   * Indic_Syllabic_Category property value
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/IndicSyllabicCategory.txt#L28
   */
  indic_syllabic_category: string;
}

export const INDIC_SYLLABIC_CATEGORY_FIELDS = ["code_point", "indic_syllabic_category"];

// #endregion

// #region Jamo.txt
/**
 * Parsed row from `Jamo.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/Jamo.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/Jamo.txt#L16-L18
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/Jamo.txt#L19-L21
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:49.433Z
 */
export interface Jamo {
  /**
   * 4-digit hexadecimal form of a conjoining jamo character that participates in the algorithmic determination of Hangul syllable character names.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/Jamo.txt#L16-L18
   */
  code_point: string;

  /**
   * Jamo_Short_Name as a one-, two-, or three-character ASCII string (or the null string for U+110B).
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/Jamo.txt#L19-L21
   */
  jamo_short_name: string;
}

export const JAMO_FIELDS = ["code_point", "jamo_short_name"];

// #endregion

// #region LineBreak.txt
/**
 * Parsed row from `LineBreak.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/LineBreak.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/LineBreak.txt#L14
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/LineBreak.txt#L13-L22
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:44:57.611Z
 */
export interface LineBreak {
  /**
   * Unicode code point value or range of code point values.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/LineBreak.txt#L14
   */
  code_point: string;

  /**
   * Line_Break property, consisting of one of the following values.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/LineBreak.txt#L13-L22
   */
  line_break: "BK" | "CR" | "LF" | "CM" | "SG" | "GL" | "CB" | "SP" | "ZW" | "NL" | "WJ" | "JL" | "JV" | "JT" | "H2" | "H3" | "XX" | "OP" | "CL" | "CP" | "QU" | "NS" | "EX" | "SY" | "IS" | "PR" | "PO" | "NU" | "AL" | "ID" | "IN" | "HY" | "BB" | "BA" | "SA" | "AI" | "B2" | "HL" | "CJ" | "RI";
}

export const LINE_BREAK_FIELDS = ["code_point", "line_break"];

// #endregion

// #region NameAliases.txt
/**
 * Parsed row from `NameAliases.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/NameAliases.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NameAliases.txt#L47
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NameAliases.txt#L48
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NameAliases.txt#L14-L30
 *
 * @unicodeVersion 8
 * @fields 3
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:45:33.360Z
 */
export interface NameAliases {
  /**
   * Unicode code point in hexadecimal notation.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NameAliases.txt#L47
   */
  code_point: string;

  /**
   * Formal name alias for the character.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NameAliases.txt#L48
   */
  alias: string;

  /**
   * Type label of the alias: correction, control, alternate, figment, or abbreviation.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NameAliases.txt#L14-L30
   */
  type: "correction" | "control" | "alternate" | "figment" | "abbreviation" | (string & {});
}

export const NAME_ALIASES_FIELDS = ["code_point", "alias", "type"];

// #endregion

// #region NamedSequences.txt
/**
 * Parsed row from `NamedSequences.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/NamedSequences.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NamedSequences.txt#L13
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:45:10.948Z
 */
export interface NamedSequences {
  /**
   * Name of Sequence.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NamedSequences.txt#L13
   */
  name: string;

  /**
   * Code Point Sequence for USI, using spaces as delimiters.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NamedSequences.txt#L13
   */
  code_point_sequence: string;
}

export const NAMED_SEQUENCES_FIELDS = ["name", "code_point_sequence"];

// #endregion

// #region NamedSequencesProv.txt
/**
 * Parsed row from `NamedSequencesProv.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/NamedSequencesProv.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NamedSequencesProv.txt#L14
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:45:12.617Z
 */
export interface NamedSequencesProv {
  /**
   * Name of Sequence.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NamedSequencesProv.txt#L14
   */
  name: string;

  /**
   * Code Point Sequence for USI, space-delimited hexadecimal code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NamedSequencesProv.txt#L14
   */
  code_point_sequence: string;
}

export const NAMED_SEQUENCES_PROV_FIELDS = ["name", "code_point_sequence"];

// #endregion

// #region NamesList.txt
/**
 * Parsed row from `NamesList.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/NamesList.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 8
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:46:06.838Z
 */
export interface NamesList {

}

export const NAMES_LIST_FIELDS = [];

// #endregion

// #region NormalizationCorrections.txt
/**
 * Parsed row from `NormalizationCorrections.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/NormalizationCorrections.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NormalizationCorrections.txt#L33
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NormalizationCorrections.txt#L34
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NormalizationCorrections.txt#L35
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NormalizationCorrections.txt#L36-L37
 *
 * @unicodeVersion 8
 * @fields 4
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:46:29.967Z
 */
export interface NormalizationCorrections {
  /**
   * Unicode code point.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NormalizationCorrections.txt#L33
   */
  code_point: string;

  /**
   * Original (erroneous) decomposition.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NormalizationCorrections.txt#L34
   */
  original_decomposition: string;

  /**
   * Corrected decomposition.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NormalizationCorrections.txt#L35
   */
  corrected_decomposition: string;

  /**
   * Version of Unicode for which the correction was entered into UnicodeData.txt, in n.n.n format.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/NormalizationCorrections.txt#L36-L37
   */
  version: string;
}

export const NORMALIZATION_CORRECTIONS_FIELDS = ["code_point", "original_decomposition", "corrected_decomposition", "version"];

// #endregion

// #region PropertyAliases.txt
/**
 * Parsed row from `PropertyAliases.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/PropertyAliases.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/PropertyAliases.txt#L20
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/PropertyAliases.txt#L22
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:45:03.955Z
 */
export interface PropertyAliases {
  /**
   * The first field is an abbreviated name for the property.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/PropertyAliases.txt#L20
   */
  abbreviated_name: string;

  /**
   * The second field is a long name.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/PropertyAliases.txt#L22
   */
  long_name: string;
}

export const PROPERTY_ALIASES_FIELDS = ["abbreviated_name", "long_name"];

// #endregion

// #region PropertyValueAliases.txt
/**
 * Parsed row from `PropertyValueAliases.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/PropertyValueAliases.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/PropertyValueAliases.txt#L21-L23
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/PropertyValueAliases.txt#L24-L25
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/PropertyValueAliases.txt#L26
 *
 * @unicodeVersion 8
 * @fields 3
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:45:00.323Z
 */
export interface PropertyValueAliases {
  /**
   * The property for which the property value name is used.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/PropertyValueAliases.txt#L21-L23
   */
  property: string;

  /**
   * Abbreviated name (numeric for ccc).
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/PropertyValueAliases.txt#L24-L25
   */
  abbrev_name: string;

  /**
   * Long name.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/PropertyValueAliases.txt#L26
   */
  long_name: string;
}

export const PROPERTY_VALUE_ALIASES_FIELDS = ["property", "abbrev_name", "long_name"];

// #endregion

// #region PropList.txt
/**
 * Parsed row from `PropList.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/PropList.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:45:53.757Z
 */
export interface PropList {
  /**
   * Unicode code point or code point range in hexadecimal without U+ prefix.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Name of the informative binary property (value 'Yes') from PropList.txt.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property: string;
}

export const PROP_LIST_FIELDS = ["code_point", "property"];

// #endregion

// #region ScriptExtensions.txt
/**
 * Parsed row from `ScriptExtensions.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/ScriptExtensions.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/ScriptExtensions.txt#L27-L28
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/ScriptExtensions.txt#L18-L21
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:45:44.520Z
 */
export interface ScriptExtensions {
  /**
   * List of code points associated with a distinct Script_Extensions value, listed in code point order.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/ScriptExtensions.txt#L27-L28
   */
  code_point_range: string;

  /**
   * Set of one or more abbreviated Script property values, given in alphabetical order.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/ScriptExtensions.txt#L18-L21
   */
  script_extensions: string;
}

export const SCRIPT_EXTENSIONS_FIELDS = ["code_point_range", "script_extensions"];

// #endregion

// #region Scripts.txt
/**
 * Parsed row from `Scripts.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/Scripts.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr24/
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/Scripts.txt#L17-L22
 *
 * @unicodeVersion 8
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:45:23.150Z
 */
export interface Scripts {
  /**
   * Unicode code point or range explicitly listed for Script.
   *
   * @source https://ucdjs.dev/reports/tr24/
   */
  code_point_range: string;

  /**
   * Script property value; all code points not explicitly listed have the value Unknown (Zzzz).
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/Scripts.txt#L17-L22
   */
  script: "Zzzz" | (string & {});
}

export const SCRIPTS_FIELDS = ["code_point_range", "script"];

// #endregion

// #region SpecialCasing.txt
/**
 * Parsed row from `SpecialCasing.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/SpecialCasing.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/SpecialCasing.txt#L31
 *
 * @unicodeVersion 8
 * @fields 6
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:45:24.926Z
 */
export interface SpecialCasing {
  /**
   * Unicode code point(s) in hexadecimal format.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/SpecialCasing.txt#L31
   */
  code: string;

  /**
   * Full lowercase mapping, one or more character values in hex separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/SpecialCasing.txt#L31
   */
  lower: string;

  /**
   * Full titlecase mapping, one or more character values in hex separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/SpecialCasing.txt#L31
   */
  title: string;

  /**
   * Full uppercase mapping, one or more character values in hex separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/SpecialCasing.txt#L31
   */
  upper: string;

  /**
   * Optional condition list of language IDs or casing contexts separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/SpecialCasing.txt#L31
   */
  condition_list: string;

  /**
   * Informational comment.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/SpecialCasing.txt#L31
   */
  comment: string;
}

export const SPECIAL_CASING_FIELDS = ["code", "lower", "title", "upper", "condition_list", "comment"];

// #endregion

// #region StandardizedVariants.txt
/**
 * Parsed row from `StandardizedVariants.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/StandardizedVariants.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/StandardizedVariants.txt#L30
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/StandardizedVariants.txt#L31
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/StandardizedVariants.txt#L32-L34
 *
 * @unicodeVersion 8
 * @fields 3
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:46:14.718Z
 */
export interface StandardizedVariants {
  /**
   * The variation sequence.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/StandardizedVariants.txt#L30
   */
  variation_sequence: string;

  /**
   * The description of the desired appearance.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/StandardizedVariants.txt#L31
   */
  description: string;

  /**
   * Where the appearance is only different in particular shaping environments; possible values are isolate, initial, medial, final.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/StandardizedVariants.txt#L32-L34
   */
  shaping_environments: "isolate" | "initial" | "medial" | "final";
}

export const STANDARDIZED_VARIANTS_FIELDS = ["variation_sequence", "description", "shaping_environments"];

// #endregion

// #region UnicodeData.txt
/**
 * Parsed row from `UnicodeData.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/UnicodeData.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 8
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:46:39.277Z
 */
export interface UnicodeData {

}

export const UNICODE_DATA_FIELDS = [];

// #endregion

// #region USourceData.txt
/**
 * Parsed row from `USourceData.txt` (Unicode 8).
 *
 * @see https://unicode.org/Public/8.0.0/ucd/USourceData.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/USourceData.txt#L12
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/USourceData.txt#L13-L23
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/USourceData.txt#L24-L27
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/USourceData.txt#L28
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/USourceData.txt#L29
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/USourceData.txt#L30
 * - https://ucdjs.dev/file-explorer/v/8.0.0/ucd/USourceData.txt#L31
 *
 * @unicodeVersion 8
 * @fields 7
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:45:16.361Z
 */
export interface USourceData {
  /**
   * The U-source ID
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/USourceData.txt#L12
   */
  u_source_id: string;

  /**
   * Text indicating the ideograph's status: C=Included in Extension C, D=Included in Extension D, E=Included in Extension E, F=Submitted for Extension F, N=Planned to be submitted for a future extension, U=Encoded, UNC-2013=Included in the UTC's 2013 "Urgently Needed Characters" proposal, V=Variant of an encoded character, W=Not to encode, X=No action taken.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/USourceData.txt#L13-L23
   */
  status: "C" | "D" | "E" | "F" | "N" | "U" | "UNC-2013" | "V" | "W" | "X";

  /**
   * A Unicode code point. If the status is V (Field 1), the code point in Field 2 specifies the encoded character for which this entry is a variant. Otherwise, the code point specifies the encoded character for this entry.
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/USourceData.txt#L24-L27
   */
  unicode_code_point: string;

  /**
   * Radical-stroke count
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/USourceData.txt#L28
   */
  radical_stroke_count: string;

  /**
   * Virtual KangXi dictionary position
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/USourceData.txt#L29
   */
  virtual_kang_xi_position: string;

  /**
   * Ideographic Description Sequence (IDS), if possible
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/USourceData.txt#L30
   */
  ids: string;

  /**
   * Source(s)
   *
   * @source https://ucdjs.dev/file-explorer/v/8.0.0/ucd/USourceData.txt#L31
   */
  sources: string;
}

export const U_SOURCE_DATA_FIELDS = ["u_source_id", "status", "unicode_code_point", "radical_stroke_count", "virtual_kang_xi_position", "ids", "sources"];

// #endregion

