// This file is generated by scripts/codegen/generate-fields.ts. Do not edit directly.
// Unicode Version: 9
// Generated At: 2026-04-23T16:43:24.539Z
// Files: 47
//   - ArabicShaping.txt
//   - auxiliary/GraphemeBreakProperty.txt
//   - auxiliary/SentenceBreakProperty.txt
//   - auxiliary/WordBreakProperty.txt
//   - BidiBrackets.txt
//   - BidiMirroring.txt
//   - Blocks.txt
//   - CaseFolding.txt
//   - CJKRadicals.txt
//   - CompositionExclusions.txt
//   - DerivedAge.txt
//   - DerivedCoreProperties.txt
//   - DerivedNormalizationProps.txt
//   - EastAsianWidth.txt
//   - EmojiSources.txt
//   - extracted/DerivedBidiClass.txt
//   - extracted/DerivedBinaryProperties.txt
//   - extracted/DerivedCombiningClass.txt
//   - extracted/DerivedDecompositionType.txt
//   - extracted/DerivedEastAsianWidth.txt
//   - extracted/DerivedGeneralCategory.txt
//   - extracted/DerivedJoiningGroup.txt
//   - extracted/DerivedJoiningType.txt
//   - extracted/DerivedLineBreak.txt
//   - extracted/DerivedNumericType.txt
//   - extracted/DerivedNumericValues.txt
//   - HangulSyllableType.txt
//   - Index.txt
//   - IndicPositionalCategory.txt
//   - IndicSyllabicCategory.txt
//   - Jamo.txt
//   - LineBreak.txt
//   - NameAliases.txt
//   - NamedSequences.txt
//   - NamedSequencesProv.txt
//   - NamesList.txt
//   - NormalizationCorrections.txt
//   - PropertyAliases.txt
//   - PropertyValueAliases.txt
//   - PropList.txt
//   - ScriptExtensions.txt
//   - Scripts.txt
//   - SpecialCasing.txt
//   - StandardizedVariants.txt
//   - TangutSources.txt
//   - UnicodeData.txt
//   - USourceData.txt

// #region ArabicShaping.txt
/**
 * Parsed row from `ArabicShaping.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/ArabicShaping.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/ArabicShaping.txt#L24-L26
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/ArabicShaping.txt#L28-L33
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/ArabicShaping.txt#L35-L42
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/ArabicShaping.txt#L50
 *
 * @unicodeVersion 9
 * @fields 4
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:42.258Z
 */
export interface ArabicShaping {
  /**
   * the code point, in 4-digit hexadecimal form, of an Arabic, Syriac, N'Ko, Mandaic, Mongolian, Phags-pa, Manichaean, Psalter Pahlavi, or other character.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/ArabicShaping.txt#L24-L26
   */
  code_point: string;

  /**
   * gives a short schematic name for that character. The schematic name is descriptive of the shape, based as consistently as possible on a name for the skeleton and then the diacritic marks applied to the skeleton, if any. Note that this schematic name is considered a comment, and does not constitute a formal property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/ArabicShaping.txt#L28-L33
   */
  name: string;

  /**
   * defines the joining type (property name: Joining_Type)
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/ArabicShaping.txt#L35-L42
   */
  joining_type: "R" | "L" | "D" | "C" | "U" | "T";

  /**
   * defines the joining group (property name: Joining_Group)
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/ArabicShaping.txt#L50
   */
  joining_group: string;
}

export const ARABIC_SHAPING_FIELDS = ["code_point", "name", "joining_type", "joining_group"];

// #endregion

// #region auxiliary/GraphemeBreakProperty.txt
/**
 * Parsed row from `auxiliary/GraphemeBreakProperty.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/auxiliary/GraphemeBreakProperty.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr29/
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/auxiliary/GraphemeBreakProperty.txt#L12-L15
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:44.077Z
 */
export interface AuxiliaryGraphemeBreakProperty {
  /**
   * Unicode code point or range.
   *
   * @source https://ucdjs.dev/reports/tr29/
   */
  code_point: string;

  /**
   * Grapheme_Cluster_Break property value; defaults to Other (XX) for unlisted code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/auxiliary/GraphemeBreakProperty.txt#L12-L15
   */
  grapheme_cluster_break: "Other" | "XX" | (string & {});
}

export const AUXILIARY_GRAPHEME_BREAK_PROPERTY_FIELDS = ["code_point", "grapheme_cluster_break"];

// #endregion

// #region auxiliary/SentenceBreakProperty.txt
/**
 * Parsed row from `auxiliary/SentenceBreakProperty.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/auxiliary/SentenceBreakProperty.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/auxiliary/SentenceBreakProperty.txt#L12-L15
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:45.614Z
 */
export interface AuxiliarySentenceBreakProperty {
  /**
   * Unicode code point or range.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Sentence_Break property value; unlisted code points have the value Other (XX).
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/auxiliary/SentenceBreakProperty.txt#L12-L15
   */
  sentence_break: "ATerm" | "Close" | "CR" | "Extend" | "Format" | "LF" | "Lower" | "Numeric" | "OLetter" | "Other" | "Sep" | "Sp" | "STerm" | "Upper" | (string & {});
}

export const AUXILIARY_SENTENCE_BREAK_PROPERTY_FIELDS = ["code_point", "sentence_break"];

// #endregion

// #region auxiliary/WordBreakProperty.txt
/**
 * Parsed row from `auxiliary/WordBreakProperty.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/auxiliary/WordBreakProperty.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/auxiliary/WordBreakProperty.txt#L14
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/auxiliary/WordBreakProperty.txt#L12
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:43.471Z
 */
export interface AuxiliaryWordBreakProperty {
  /**
   * Unicode code point or range explicitly listed for Word_Break.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/auxiliary/WordBreakProperty.txt#L14
   */
  code_point: string;

  /**
   * Word_Break property value; unlisted code points have value Other (XX).
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/auxiliary/WordBreakProperty.txt#L12
   */
  word_break: "ALetter" | "ATerm" | "CR" | "Double_Quote" | "E_Base" | "E_Base_GAZ" | "E_Modifier" | "Extend" | "ExtendNumLet" | "FO" | "Format" | "Glue_After_Zwj" | "Hebrew_Letter" | "Hybrid_Start" | "Katakana" | "LF" | "MidLetter" | "MidNum" | "MidNumLet" | "Newline" | "Numeric" | "Other" | "Perl" | "RI" | "Regional_Indicator" | "Single_Quote" | "Space" | "WSegmenter" | "ZWJ" | (string & {});
}

export const AUXILIARY_WORD_BREAK_PROPERTY_FIELDS = ["code_point", "word_break"];

// #endregion

// #region BidiBrackets.txt
/**
 * Parsed row from `BidiBrackets.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/BidiBrackets.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/BidiBrackets.txt#L49
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/BidiBrackets.txt#L50
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/BidiBrackets.txt#L51-L54
 *
 * @unicodeVersion 9
 * @fields 3
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:42.771Z
 */
export interface BidiBrackets {
  /**
   * Unicode code point value, represented as a hexadecimal value.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/BidiBrackets.txt#L49
   */
  code_point: string;

  /**
   * Bidi_Paired_Bracket property value, a code point value or <none>.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/BidiBrackets.txt#L50
   */
  bidi_paired_bracket: string;

  /**
   * Bidi_Paired_Bracket_Type property value: o=Open, c=Close, n=None.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/BidiBrackets.txt#L51-L54
   */
  bidi_paired_bracket_type: "o" | "c" | "n";
}

export const BIDI_BRACKETS_FIELDS = ["code_point", "bidi_paired_bracket", "bidi_paired_bracket_type"];

// #endregion

// #region BidiMirroring.txt
/**
 * Parsed row from `BidiMirroring.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/BidiMirroring.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/BidiMirroring.txt#L14-L40
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/BidiMirroring.txt#L20-L28
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:45.113Z
 */
export interface BidiMirroring {
  /**
   * Code point that has Bidi_Mirrored=Yes and requires character-based mirroring.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/BidiMirroring.txt#L14-L40
   */
  source_codepoint: string;

  /**
   * Code point whose glyph is the mirror image of the source code point's glyph.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/BidiMirroring.txt#L20-L28
   */
  mirror_codepoint: string;
}

export const BIDI_MIRRORING_FIELDS = ["source_codepoint", "mirror_codepoint"];

// #endregion

// #region Blocks.txt
/**
 * Parsed row from `Blocks.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/Blocks.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/Blocks.txt#L10
 *
 * @unicodeVersion 9
 * @fields 3
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:42.196Z
 */
export interface Blocks {
  /**
   * Start of the code point range in hexadecimal notation.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/Blocks.txt#L10
   */
  start_code: string;

  /**
   * End of the code point range in hexadecimal notation.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/Blocks.txt#L10
   */
  end_code: string;

  /**
   * Name of the Unicode block.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/Blocks.txt#L10
   */
  block_name: string;
}

export const BLOCKS_FIELDS = ["start_code", "end_code", "block_name"];

// #endregion

// #region CaseFolding.txt
/**
 * Parsed row from `CaseFolding.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/CaseFolding.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/CaseFolding.txt#L36
 *
 * @unicodeVersion 9
 * @fields 4
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:47.395Z
 */
export interface CaseFolding {
  /**
   * Unicode code point in hexadecimal notation.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/CaseFolding.txt#L36
   */
  code: string;

  /**
   * Status field indicating the type of case folding: C for common, F for full, S for simple, T for special Turkic.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/CaseFolding.txt#L36
   */
  status: "C" | "F" | "S" | "T";

  /**
   * Case folding mapping, which may be a single code point or multiple separated by spaces for full mappings.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/CaseFolding.txt#L36
   */
  mapping: string;

  /**
   * Character name or comment.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/CaseFolding.txt#L36
   */
  name: string;
}

export const CASE_FOLDING_FIELDS = ["code", "status", "mapping", "name"];

// #endregion

// #region CJKRadicals.txt
/**
 * Parsed row from `CJKRadicals.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/CJKRadicals.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/CJKRadicals.txt#L17-L22
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/CJKRadicals.txt#L17-L19
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/CJKRadicals.txt#L17-L20
 *
 * @unicodeVersion 9
 * @fields 3
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:49.638Z
 */
export interface CjkRadicals {
  /**
   * CJK radical number matching the regular expression [1-9][0-9]{0,2}'?.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/CJKRadicals.txt#L17-L22
   */
  cjk_radical_number: string;

  /**
   * CJK radical character in the Kangxi Radicals block or the CJK Radicals Supplement block.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/CJKRadicals.txt#L17-L19
   */
  cjk_radical_character: string;

  /**
   * CJK unified ideograph which is formed from that radical only.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/CJKRadicals.txt#L17-L20
   */
  cjk_unified_ideograph: string;
}

export const CJK_RADICALS_FIELDS = ["cjk_radical_number", "cjk_radical_character", "cjk_unified_ideograph"];

// #endregion

// #region CompositionExclusions.txt
/**
 * Parsed row from `CompositionExclusions.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/CompositionExclusions.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr15/
 *
 * @unicodeVersion 9
 * @fields 1
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:50.147Z
 */
export interface CompositionExclusions {
  /**
   * Unicode code point that is a member of the Composition Exclusion Table as defined in UAX #15.
   *
   * @source https://ucdjs.dev/reports/tr15/
   */
  codepoint: string;
}

export const COMPOSITION_EXCLUSIONS_FIELDS = ["codepoint"];

// #endregion

// #region DerivedAge.txt
/**
 * Parsed row from `DerivedAge.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/DerivedAge.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/DerivedAge.txt#L52
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/DerivedAge.txt#L37
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:52.538Z
 */
export interface DerivedAge {
  /**
   * Code point range first assigned in the specified Unicode version.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/DerivedAge.txt#L52
   */
  codepoint_range: string;

  /**
   * Unicode version when code points were first designated as assigned characters.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/DerivedAge.txt#L37
   */
  age: "V1_1" | "V2_0" | "V3_0" | "V3_1" | "V3_2" | "V4_0" | "V4_1" | "V5_0" | "V5_1" | "V5_2" | "V6_0" | "V6_1" | "V6_2" | "V6_3" | "V7_0" | "V8_0" | "V9_0" | "V10_0" | "V11_0" | "V12_0" | "V12_1" | "V13_0" | "V14_0" | "V15_0" | "V15_1" | "V16_0" | "V17_0" | (string & {});
}

export const DERIVED_AGE_FIELDS = ["codepoint_range", "age"];

// #endregion

// #region DerivedCoreProperties.txt
/**
 * Parsed row from `DerivedCoreProperties.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/DerivedCoreProperties.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/DerivedCoreProperties.txt#L12-L13
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:49.204Z
 */
export interface DerivedCoreProperties {
  /**
   * Unicode code point range with characters having the derived Math property.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/DerivedCoreProperties.txt#L12-L13
   */
  code_point_range: string;

  /**
   * Binary value for the derived Math property (generated from Sm + Other_Math).
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/DerivedCoreProperties.txt#L12-L13
   */
  math: "Y" | "N";
}

export const DERIVED_CORE_PROPERTIES_FIELDS = ["code_point_range", "math"];

// #endregion

// #region DerivedNormalizationProps.txt
/**
 * Parsed row from `DerivedNormalizationProps.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/DerivedNormalizationProps.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 9
 * @fields 3
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:42:27.165Z
 */
export interface DerivedNormalizationProps {
  /**
   * Unicode code point or range to which the derived normalization property applies.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Name of the derived normalization property, such as FC_NFKC_Closure.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property: string;

  /**
   * Space-separated list of Unicode code points constituting the property value (e.g. closure).
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  value: Array<string>;
}

export const DERIVED_NORMALIZATION_PROPS_FIELDS = ["code_point", "property", "value"];

// #endregion

// #region EastAsianWidth.txt
/**
 * Parsed row from `EastAsianWidth.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/EastAsianWidth.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/EastAsianWidth.txt#L16
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/EastAsianWidth.txt#L17-L18
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:48.281Z
 */
export interface EastAsianWidth {
  /**
   * Unicode code point value or range of code point values.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/EastAsianWidth.txt#L16
   */
  codepoints: string;

  /**
   * East_Asian_Width property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/EastAsianWidth.txt#L17-L18
   */
  east_asian_width: "A" | "F" | "H" | "N" | "Na" | "W";
}

export const EAST_ASIAN_WIDTH_FIELDS = ["codepoints", "east_asian_width"];

// #endregion

// #region EmojiSources.txt
/**
 * Parsed row from `EmojiSources.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/EmojiSources.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/EmojiSources.txt#L25
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/EmojiSources.txt#L26
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/EmojiSources.txt#L27
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/EmojiSources.txt#L28
 *
 * @unicodeVersion 9
 * @fields 4
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:46.571Z
 */
export interface EmojiSources {
  /**
   * Unicode code point or sequence.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/EmojiSources.txt#L25
   */
  unicode: string;

  /**
   * DoCoMo Shift-JIS code.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/EmojiSources.txt#L26
   */
  docomo_shift_jis: string;

  /**
   * KDDI Shift-JIS code.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/EmojiSources.txt#L27
   */
  kddi_shift_jis: string;

  /**
   * SoftBank Shift-JIS code.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/EmojiSources.txt#L28
   */
  softbank_shift_jis: string;
}

export const EMOJI_SOURCES_FIELDS = ["unicode", "docomo_shift_jis", "kddi_shift_jis", "softbank_shift_jis"];

// #endregion

// #region extracted/DerivedBidiClass.txt
/**
 * Parsed row from `extracted/DerivedBidiClass.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/extracted/DerivedBidiClass.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedBidiClass.txt#L12
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:53.099Z
 */
export interface ExtractedDerivedBidiClass {
  /**
   * Unicode code point or range explicitly listed for Bidi_Class.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedBidiClass.txt#L12
   */
  code_point: string;

  /**
   * Bidi Class property value (see UAX #44).
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedBidiClass.txt#L12
   */
  bidi_class: "L" | "R" | "AL" | "ET" | "BN" | (string & {});
}

export const EXTRACTED_DERIVED_BIDI_CLASS_FIELDS = ["code_point", "bidi_class"];

// #endregion

// #region extracted/DerivedBinaryProperties.txt
/**
 * Parsed row from `extracted/DerivedBinaryProperties.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/extracted/DerivedBinaryProperties.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedBinaryProperties.txt#L12
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:55.973Z
 */
export interface ExtractedDerivedBinaryProperties {
  /**
   * Unicode code point or range.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedBinaryProperties.txt#L12
   */
  code_point_range: string;

  /**
   * Bidi_Mirrored property value listing UnicodeData.txt field 9.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedBinaryProperties.txt#L12
   */
  bidi_mirrored: "Y" | "N";
}

export const EXTRACTED_DERIVED_BINARY_PROPERTIES_FIELDS = ["code_point_range", "bidi_mirrored"];

// #endregion

// #region extracted/DerivedCombiningClass.txt
/**
 * Parsed row from `extracted/DerivedCombiningClass.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/extracted/DerivedCombiningClass.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedCombiningClass.txt#L12
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedCombiningClass.txt#L12-L15
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:58.130Z
 */
export interface ExtractedDerivedCombiningClass {
  /**
   * Unicode code point or range with explicit Canonical_Combining_Class value.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedCombiningClass.txt#L12
   */
  code_point_range: string;

  /**
   * Canonical_Combining_Class property value (defaults to Not_Reordered (0) for unlisted code points).
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedCombiningClass.txt#L12-L15
   */
  combining_class: string;
}

export const EXTRACTED_DERIVED_COMBINING_CLASS_FIELDS = ["code_point_range", "combining_class"];

// #endregion

// #region extracted/DerivedDecompositionType.txt
/**
 * Parsed row from `extracted/DerivedDecompositionType.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/extracted/DerivedDecompositionType.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedDecompositionType.txt#L12-L17
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedDecompositionType.txt#L12-L15
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:57.305Z
 */
export interface ExtractedDerivedDecompositionType {
  /**
   * Unicode code point or range explicitly listed with a Decomposition_Type value; unlisted code points have value None.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedDecompositionType.txt#L12-L17
   */
  code_point_range: string;

  /**
   * Decomposition_Type (from UnicodeData.txt, field 5); default value is None.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedDecompositionType.txt#L12-L15
   */
  decomposition_type: "none" | string;
}

export const EXTRACTED_DERIVED_DECOMPOSITION_TYPE_FIELDS = ["code_point_range", "decomposition_type"];

// #endregion

// #region extracted/DerivedEastAsianWidth.txt
/**
 * Parsed row from `extracted/DerivedEastAsianWidth.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/extracted/DerivedEastAsianWidth.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedEastAsianWidth.txt#L12
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:55.047Z
 */
export interface ExtractedDerivedEastAsianWidth {
  /**
   * Unicode code point range or single code point.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point_range: string;

  /**
   * East_Asian_Width property value (Neutral for unlisted code points).
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedEastAsianWidth.txt#L12
   */
  east_asian_width: "Neutral";
}

export const EXTRACTED_DERIVED_EAST_ASIAN_WIDTH_FIELDS = ["code_point_range", "east_asian_width"];

// #endregion

// #region extracted/DerivedGeneralCategory.txt
/**
 * Parsed row from `extracted/DerivedGeneralCategory.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/extracted/DerivedGeneralCategory.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:42.527Z
 */
export interface ExtractedDerivedGeneralCategory {
  /**
   * Unicode code point range in the standard abbreviated format.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  codepoint_range: string;

  /**
   * General_Category property value, such as Unassigned.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  general_category: "Unassigned" | (string & {});
}

export const EXTRACTED_DERIVED_GENERAL_CATEGORY_FIELDS = ["codepoint_range", "general_category"];

// #endregion

// #region extracted/DerivedJoiningGroup.txt
/**
 * Parsed row from `extracted/DerivedJoiningGroup.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/extracted/DerivedJoiningGroup.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedJoiningGroup.txt#L12
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:55.161Z
 */
export interface ExtractedDerivedJoiningGroup {
  /**
   * Unicode code point or range with explicit Joining_Group value (referencing ArabicShaping.txt field 3).
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedJoiningGroup.txt#L12
   */
  code_point: string;

  /**
   * Joining Group property value.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedJoiningGroup.txt#L12
   */
  joining_group: string;
}

export const EXTRACTED_DERIVED_JOINING_GROUP_FIELDS = ["code_point", "joining_group"];

// #endregion

// #region extracted/DerivedJoiningType.txt
/**
 * Parsed row from `extracted/DerivedJoiningType.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/extracted/DerivedJoiningType.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedJoiningType.txt#L14-L15
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedJoiningType.txt#L12
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:53.034Z
 */
export interface ExtractedDerivedJoiningType {
  /**
   * Unicode code point or range explicitly listed for the Joining_Type.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedJoiningType.txt#L14-L15
   */
  code_point_range: string;

  /**
   * Joining_Type value for the listed code points, derived as described in ArabicShaping.txt.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedJoiningType.txt#L12
   */
  joining_type: "Join_Causing";
}

export const EXTRACTED_DERIVED_JOINING_TYPE_FIELDS = ["code_point_range", "joining_type"];

// #endregion

// #region extracted/DerivedLineBreak.txt
/**
 * Parsed row from `extracted/DerivedLineBreak.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/extracted/DerivedLineBreak.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:42:37.434Z
 */
export interface ExtractedDerivedLineBreak {
  /**
   * Unicode code point or range explicitly listed for Line_Break.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Value of the Line_Break property; defaults to Unknown (XX) for unlisted code points.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  line_break: string;
}

export const EXTRACTED_DERIVED_LINE_BREAK_FIELDS = ["code_point", "line_break"];

// #endregion

// #region extracted/DerivedNumericType.txt
/**
 * Parsed row from `extracted/DerivedNumericType.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/extracted/DerivedNumericType.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedNumericType.txt#L12-L23
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedNumericType.txt#L12-L20
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:00.145Z
 */
export interface ExtractedDerivedNumericType {
  /**
   * Unicode code point or range explicitly listed with a Numeric_Type value other than the default None.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedNumericType.txt#L12-L23
   */
  code_point_range: string;

  /**
   * Derived Numeric_Type property value: Decimal when UnicodeData.txt field 6 has value; Digit when field 7 has value but not 6; Numeric when Unihan numeric fields or field 8 has value but not 7; None otherwise.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedNumericType.txt#L12-L20
   */
  numeric_type: "Decimal" | "Digit" | "Numeric" | (string & {});
}

export const EXTRACTED_DERIVED_NUMERIC_TYPE_FIELDS = ["code_point_range", "numeric_type"];

// #endregion

// #region extracted/DerivedNumericValues.txt
/**
 * Parsed row from `extracted/DerivedNumericValues.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/extracted/DerivedNumericValues.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedNumericValues.txt#L13-L19
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedNumericValues.txt#L20-L21
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedNumericValues.txt#L23-L31
 *
 * @unicodeVersion 9
 * @fields 3
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:03.180Z
 */
export interface ExtractedDerivedNumericValues {
  /**
   * The values are based on field 8 of UnicodeData.txt, plus the fields kAccountingNumeric, kOtherNumeric, kPrimaryNumeric in the Unicode Han Database (Unihan).
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedNumericValues.txt#L13-L19
   */
  numeric_value: string;

  /**
   * This field is empty; it used to be a copy of the numeric type.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedNumericValues.txt#L20-L21
   */
  unused_numeric_type: string;

  /**
   * Expressing the same numeric value either as a whole integer where possible, or as a rational fraction such as "1/6".
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/extracted/DerivedNumericValues.txt#L23-L31
   */
  numeric_value_fraction: string;
}

export const EXTRACTED_DERIVED_NUMERIC_VALUES_FIELDS = ["numeric_value", "unused_numeric_type", "numeric_value_fraction"];

// #endregion

// #region HangulSyllableType.txt
/**
 * Parsed row from `HangulSyllableType.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/HangulSyllableType.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:42:34.404Z
 */
export interface HangulSyllableType {
  /**
   * Unicode code point or range.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point: string;

  /**
   * Hangul_Syllable_Type property value.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  hangul_syllable_type: "NA" | "L" | "V" | "T" | "LV" | "LVT";
}

export const HANGUL_SYLLABLE_TYPE_FIELDS = ["code_point", "hangul_syllable_type"];

// #endregion

// #region Index.txt
/**
 * Parsed row from `Index.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/Index.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 9
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:42:00.664Z
 */
export interface Index {

}

export const INDEX_FIELDS = [];

// #endregion

// #region IndicPositionalCategory.txt
/**
 * Parsed row from `IndicPositionalCategory.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/IndicPositionalCategory.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/IndicPositionalCategory.txt#L47
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/IndicPositionalCategory.txt#L48
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:57.782Z
 */
export interface IndicPositionalCategory {
  /**
   * Unicode code point value or range of code point values
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/IndicPositionalCategory.txt#L47
   */
  code_point: string;

  /**
   * Indic_Positional_Category property value
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/IndicPositionalCategory.txt#L48
   */
  indic_positional_category: string;
}

export const INDIC_POSITIONAL_CATEGORY_FIELDS = ["code_point", "indic_positional_category"];

// #endregion

// #region IndicSyllabicCategory.txt
/**
 * Parsed row from `IndicSyllabicCategory.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/IndicSyllabicCategory.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/IndicSyllabicCategory.txt#L27
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/IndicSyllabicCategory.txt#L28
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:41:58.171Z
 */
export interface IndicSyllabicCategory {
  /**
   * Unicode code point value or range of code point values
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/IndicSyllabicCategory.txt#L27
   */
  code_point: string;

  /**
   * Indic_Syllabic_Category property value
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/IndicSyllabicCategory.txt#L28
   */
  indic_syllabic_category: string;
}

export const INDIC_SYLLABIC_CATEGORY_FIELDS = ["code_point", "indic_syllabic_category"];

// #endregion

// #region Jamo.txt
/**
 * Parsed row from `Jamo.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/Jamo.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/Jamo.txt#L16-L18
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/Jamo.txt#L19-L21
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:00.336Z
 */
export interface Jamo {
  /**
   * 4-digit hexadecimal form of a conjoining jamo character that participates in the algorithmic determination of Hangul syllable character names.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/Jamo.txt#L16-L18
   */
  code_point: string;

  /**
   * Jamo_Short_Name as a one-, two-, or three-character ASCII string (or the null string).
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/Jamo.txt#L19-L21
   */
  jamo_short_name: string;
}

export const JAMO_FIELDS = ["code_point", "jamo_short_name"];

// #endregion

// #region LineBreak.txt
/**
 * Parsed row from `LineBreak.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/LineBreak.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/LineBreak.txt#L16
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/LineBreak.txt#L15-L24
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:54.846Z
 */
export interface LineBreak {
  /**
   * Unicode code point value or range of code point values.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/LineBreak.txt#L16
   */
  code_point_or_range: string;

  /**
   * Line_Break property, consisting of one of the following values: Non-tailorable: "BK", "CM", "CR", "GL", "LF", "NL", "SP", "WJ", "ZW", "ZWJ"; Tailorable: "AI", "AL", "B2", "BA", "BB", "CB", "CJ", "CL", "CP", "EB", "EM", "EX", "H2", "H3", "HL", "HY", "ID", "IN", "IS", "JL", "JT", "JV", "NS", "NU", "OP", "PO", "PR", "QU", "RI", "SA", "SG", "SY", "XX".
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/LineBreak.txt#L15-L24
   */
  line_break: "BK" | "CM" | "CR" | "GL" | "LF" | "NL" | "SP" | "WJ" | "ZW" | "ZWJ" | "AI" | "AL" | "B2" | "BA" | "BB" | "CB" | "CJ" | "CL" | "CP" | "EB" | "EM" | "EX" | "H2" | "H3" | "HL" | "HY" | "ID" | "IN" | "IS" | "JL" | "JT" | "JV" | "NS" | "NU" | "OP" | "PO" | "PR" | "QU" | "RI" | "SA" | "SG" | "SY" | "XX";
}

export const LINE_BREAK_FIELDS = ["code_point_or_range", "line_break"];

// #endregion

// #region NameAliases.txt
/**
 * Parsed row from `NameAliases.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/NameAliases.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NameAliases.txt#L47-L51
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NameAliases.txt#L16-L32
 *
 * @unicodeVersion 9
 * @fields 3
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:05.480Z
 */
export interface NameAliases {
  /**
   * Unicode code point in hexadecimal notation.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NameAliases.txt#L47-L51
   */
  code_point: string;

  /**
   * Formal name alias for the character.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NameAliases.txt#L47-L51
   */
  alias: string;

  /**
   * Type label of the formal name alias (case-insensitive).
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NameAliases.txt#L16-L32
   */
  type: "correction" | "control" | "alternate" | "figment" | "abbreviation";
}

export const NAME_ALIASES_FIELDS = ["code_point", "alias", "type"];

// #endregion

// #region NamedSequences.txt
/**
 * Parsed row from `NamedSequences.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/NamedSequences.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NamedSequences.txt#L15
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:08.522Z
 */
export interface NamedSequences {
  /**
   * Name of Sequence.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NamedSequences.txt#L15
   */
  name: string;

  /**
   * Code Point Sequence for USI, space-delimited hexadecimal code points.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NamedSequences.txt#L15
   */
  code_point_sequence: string;
}

export const NAMED_SEQUENCES_FIELDS = ["name", "code_point_sequence"];

// #endregion

// #region NamedSequencesProv.txt
/**
 * Parsed row from `NamedSequencesProv.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/NamedSequencesProv.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NamedSequencesProv.txt#L16
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:48.621Z
 */
export interface NamedSequencesProv {
  /**
   * Name of Sequence.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NamedSequencesProv.txt#L16
   */
  name: string;

  /**
   * Code Point Sequence for USI.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NamedSequencesProv.txt#L16
   */
  code_point_sequence: string;
}

export const NAMED_SEQUENCES_PROV_FIELDS = ["name", "code_point_sequence"];

// #endregion

// #region NamesList.txt
/**
 * Parsed row from `NamesList.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/NamesList.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 9
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:42:14.725Z
 */
export interface NamesList {

}

export const NAMES_LIST_FIELDS = [];

// #endregion

// #region NormalizationCorrections.txt
/**
 * Parsed row from `NormalizationCorrections.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/NormalizationCorrections.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NormalizationCorrections.txt#L35
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NormalizationCorrections.txt#L36
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NormalizationCorrections.txt#L37
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NormalizationCorrections.txt#L38-L39
 *
 * @unicodeVersion 9
 * @fields 4
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:10.739Z
 */
export interface NormalizationCorrections {
  /**
   * Unicode code point.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NormalizationCorrections.txt#L35
   */
  code_point: string;

  /**
   * Original (erroneous) decomposition.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NormalizationCorrections.txt#L36
   */
  original_decomposition: string;

  /**
   * Corrected decomposition.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NormalizationCorrections.txt#L37
   */
  corrected_decomposition: string;

  /**
   * Version of Unicode for which the correction was entered into UnicodeData.txt, in n.n.n format.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/NormalizationCorrections.txt#L38-L39
   */
  version: string;
}

export const NORMALIZATION_CORRECTIONS_FIELDS = ["code_point", "original_decomposition", "corrected_decomposition", "version"];

// #endregion

// #region PropertyAliases.txt
/**
 * Parsed row from `PropertyAliases.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/PropertyAliases.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/PropertyAliases.txt#L21-L23
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/PropertyAliases.txt#L23
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:01.670Z
 */
export interface PropertyAliases {
  /**
   * The first field is an abbreviated name for the property.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/PropertyAliases.txt#L21-L23
   */
  abbreviated_name: string;

  /**
   * The second field is a long name.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/PropertyAliases.txt#L23
   */
  long_name: string;
}

export const PROPERTY_ALIASES_FIELDS = ["abbreviated_name", "long_name"];

// #endregion

// #region PropertyValueAliases.txt
/**
 * Parsed row from `PropertyValueAliases.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/PropertyValueAliases.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/PropertyValueAliases.txt#L22
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/PropertyValueAliases.txt#L25
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/PropertyValueAliases.txt#L27
 *
 * @unicodeVersion 9
 * @fields 3
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:06.505Z
 */
export interface PropertyValueAliases {
  /**
   * The property for which the property value name is used.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/PropertyValueAliases.txt#L22
   */
  property: string;

  /**
   * Abbreviated name (numeric for ccc).
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/PropertyValueAliases.txt#L25
   */
  abbreviated_name: string;

  /**
   * Long name.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/PropertyValueAliases.txt#L27
   */
  long_name: string;
}

export const PROPERTY_VALUE_ALIASES_FIELDS = ["property", "abbreviated_name", "long_name"];

// #endregion

// #region PropList.txt
/**
 * Parsed row from `PropList.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/PropList.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.70
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:09.125Z
 */
export interface PropList {
  /**
   * Unicode code point or code point range.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  code_point_range: string;

  /**
   * Binary property value (Yes or No).
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  property_name: "Y" | "N";
}

export const PROP_LIST_FIELDS = ["code_point_range", "property_name"];

// #endregion

// #region ScriptExtensions.txt
/**
 * Parsed row from `ScriptExtensions.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/ScriptExtensions.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr24/
 * - https://ucdjs.dev/reports/tr44/
 *
 * @unicodeVersion 9
 * @fields 4
 * @confidence 0.70
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:43:24.231Z
 */
export interface ScriptExtensions {
  /**
   * Unicode code point or range.
   *
   * @source https://ucdjs.dev/reports/tr24/
   */
  code_point: string;

  /**
   * Set of Script property values assigned by the Script_Extensions property.
   *
   * @source https://ucdjs.dev/reports/tr24/
   */
  script_extensions: Array<string>;

  /**
   * Optional comment providing additional information such as general category and character names.
   *
   * @source https://ucdjs.dev/reports/tr24/
   */
  comment: string;

  /**
   * Optional source attribution for the property value.
   *
   * @source https://ucdjs.dev/reports/tr44/
   */
  source: string;
}

export const SCRIPT_EXTENSIONS_FIELDS = ["code_point", "script_extensions", "comment", "source"];

// #endregion

// #region Scripts.txt
/**
 * Parsed row from `Scripts.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/Scripts.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/reports/tr24/
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/Scripts.txt#L18-L21
 *
 * @unicodeVersion 9
 * @fields 2
 * @confidence 0.80
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:21.895Z
 */
export interface Scripts {
  /**
   * Unicode code point range or single code point.
   *
   * @source https://ucdjs.dev/reports/tr24/
   */
  code_point_range: string;

  /**
   * Script property value; Unknown (Zzzz) for all code points not explicitly listed.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/Scripts.txt#L18-L21
   */
  script: "Zzzz" | (string & {});
}

export const SCRIPTS_FIELDS = ["code_point_range", "script"];

// #endregion

// #region SpecialCasing.txt
/**
 * Parsed row from `SpecialCasing.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/SpecialCasing.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/SpecialCasing.txt#L32
 *
 * @unicodeVersion 9
 * @fields 6
 * @confidence 0.90
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:02.932Z
 */
export interface SpecialCasing {
  /**
   * Unicode code point(s) in hexadecimal format.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/SpecialCasing.txt#L32
   */
  code: string;

  /**
   * Full lowercase case mapping, expressed as one or more hexadecimal character values separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/SpecialCasing.txt#L32
   */
  lower: string;

  /**
   * Full titlecase case mapping, expressed as one or more hexadecimal character values separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/SpecialCasing.txt#L32
   */
  title: string;

  /**
   * Full uppercase case mapping, expressed as one or more hexadecimal character values separated by spaces.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/SpecialCasing.txt#L32
   */
  upper: string;

  /**
   * Optional list of one or more language IDs or casing contexts separated by spaces, enclosed in parentheses.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/SpecialCasing.txt#L32
   */
  condition_list: string;

  /**
   * Informational comment.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/SpecialCasing.txt#L32
   */
  comment: string;
}

export const SPECIAL_CASING_FIELDS = ["code", "lower", "title", "upper", "condition_list", "comment"];

// #endregion

// #region StandardizedVariants.txt
/**
 * Parsed row from `StandardizedVariants.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/StandardizedVariants.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/StandardizedVariants.txt#L28
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/StandardizedVariants.txt#L29
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/StandardizedVariants.txt#L30-L33
 *
 * @unicodeVersion 9
 * @fields 3
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:26.096Z
 */
export interface StandardizedVariants {
  /**
   * the variation sequence
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/StandardizedVariants.txt#L28
   */
  variation_sequence: string;

  /**
   * the description of the desired appearance
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/StandardizedVariants.txt#L29
   */
  description: string;

  /**
   * where the appearance is only different in particular shaping environments; possible values are: isolate, initial, medial, final. If more than one is present, there are spaces between them.
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/StandardizedVariants.txt#L30-L33
   */
  shaping_environments: "isolate" | "initial" | "medial" | "final" | (string & {});
}

export const STANDARDIZED_VARIANTS_FIELDS = ["variation_sequence", "description", "shaping_environments"];

// #endregion

// #region TangutSources.txt
/**
 * Parsed row from `TangutSources.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/TangutSources.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/TangutSources.txt#L20
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/TangutSources.txt#L21-L32
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/TangutSources.txt#L22
 *
 * @unicodeVersion 9
 * @fields 3
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:43:24.539Z
 */
export interface TangutSources {
  /**
   * the Tangut code point value in U+ format
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/TangutSources.txt#L20
   */
  tangut_code_point: string;

  /**
   * a tag indicating the type of information in the third field; current tag list: Tangut Merged source: kTGT_MergedSrc, Radical-Stroke indexes: kRSTUnicode
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/TangutSources.txt#L21-L32
   */
  tag: "kTGT_MergedSrc" | "kRSTUnicode" | (string & {});

  /**
   * the value (in UTF-8)
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/TangutSources.txt#L22
   */
  value: string;
}

export const TANGUT_SOURCES_FIELDS = ["tangut_code_point", "tag", "value"];

// #endregion

// #region UnicodeData.txt
/**
 * Parsed row from `UnicodeData.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/UnicodeData.txt
 *
 * Fields derived from:

 *
 * @unicodeVersion 9
 * @fields 0
 * @confidence 0.00
 * @model grok-4-1-fast-reasoning
 * @generated 2026-04-23T16:42:15.322Z
 */
export interface UnicodeData {

}

export const UNICODE_DATA_FIELDS = [];

// #endregion

// #region USourceData.txt
/**
 * Parsed row from `USourceData.txt` (Unicode 9).
 *
 * @see https://unicode.org/Public/9.0.0/ucd/USourceData.txt
 *
 * Fields derived from:
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/USourceData.txt#L12
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/USourceData.txt#L13-L27
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/USourceData.txt#L28-L31
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/USourceData.txt#L32
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/USourceData.txt#L33
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/USourceData.txt#L34
 * - https://ucdjs.dev/file-explorer/v/9.0.0/ucd/USourceData.txt#L35
 *
 * @unicodeVersion 9
 * @fields 7
 * @confidence 1.00
 * @model grok-4-1-fast-non-reasoning
 * @generated 2026-04-23T16:42:13.684Z
 */
export interface USourceData {
  /**
   * The U-source ID
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/USourceData.txt#L12
   */
  u_source_id: string;

  /**
   * Text indicating the ideograph's status
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/USourceData.txt#L13-L27
   */
  status: "C" | "D" | "E" | "F" | "H" | "N" | "U" | "UNC-2013" | "UNC-2015" | "UK-2015" | "V" | "W" | "X" | (string & {});

  /**
   * A Unicode code point
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/USourceData.txt#L28-L31
   */
  code_point: string;

  /**
   * Radical-stroke count
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/USourceData.txt#L32
   */
  radical_stroke_count: string;

  /**
   * Virtual KangXi dictionary position
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/USourceData.txt#L33
   */
  virtual_kang_xi_position: string;

  /**
   * Ideographic Description Sequence (IDS), if possible
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/USourceData.txt#L34
   */
  ids: string;

  /**
   * Source(s)
   *
   * @source https://ucdjs.dev/file-explorer/v/9.0.0/ucd/USourceData.txt#L35
   */
  sources: string;
}

export const U_SOURCE_DATA_FIELDS = ["u_source_id", "status", "code_point", "radical_stroke_count", "virtual_kang_xi_position", "ids", "sources"];

// #endregion

