// This file is generated by scripts/codegen/generate-fields.ts. Do not edit directly.
// Unicode Version: 2.1.8
// Files: 7
//   - diff215v216.txt
//   - diff216v217.txt
//   - diff217v218.txt
//   - diff218v218d1.txt
//   - PropList-2.1.8.txt
//   - SpecialCasing-1.txt
//   - UnicodeData-2.1.8.txt

export * from "./diff215v216";
export * from "./diff216v217";
export * from "./diff217v218";
export * from "./diff218v218d1";
export * from "./PropList-2.1.8";
export * from "./SpecialCasing-1";
export * from "./UnicodeData-2.1.8";
