/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/unicode-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all Unicode Versions available, including metadata. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of Unicode versions with metadata. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnicodeVersions"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Rate Limit Exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/unicode-versions/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all Unicode Versions mappings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of Unicode versions mappings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnicodeVersionMappings"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/unicode-files/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all UCD files for a specific Unicode version. */
        get: {
            parameters: {
                query?: {
                    /** @description Optional exclude filters to apply to the file list. */
                    exclude?: string;
                    /** @description Whether to include test files in the response. */
                    includeTests?: boolean;
                    /** @description Whether to include Readme files in the response. */
                    includeReadmes?: boolean;
                    /** @description Whether to include HTML files in the response. */
                    includeHTMLFiles?: boolean;
                };
                header?: never;
                path: {
                    /** @description The Unicode version to get files for. */
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of UCD files for the specified Unicode version. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnicodeVersionFiles"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Rate Limit Exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Bad Gateway */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UnicodeVersion: {
            /** @description The version of the Unicode standard. */
            version: string;
            /**
             * Format: uri
             * @description The URL to the Unicode version documentation.
             */
            documentationUrl: string;
            /** @description The year of the Unicode version. */
            date: string | null;
            /**
             * Format: uri
             * @description The URL to the Unicode Character Database (UCD) for this version.
             */
            ucdUrl: string;
            /** @description The status of the Unicode version. */
            status: "stable" | "draft";
        };
        UnicodeVersions: components["schemas"]["UnicodeVersion"][];
        /** @description An error response */
        ApiError: {
            /** @description The path of the request */
            path: string;
            /** @description The error message */
            message: string;
            /** @description The HTTP status code */
            status: number;
            /** @description The timestamp of the error */
            timestamp: string;
        };
        UnicodeVersionMappings: {
            [key: string]: string;
        };
        UnicodeVersionFile: {
            /** @description The name of the file or directory. */
            name: string;
            /** @description The path to the file or directory. */
            path: string;
            /** @description The children of the directory, if it is a directory. */
            children?: components["schemas"]["UnicodeVersionFile"][];
        };
        UnicodeVersionFiles: components["schemas"]["UnicodeVersionFile"][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
