import { fileURLToPath } from "node:url";
import { expect, it } from "vitest";
import { getPackageExportsManifest } from "vitest-package-exports";

it("exports-snapshot", async () => {
  const manifest = await getPackageExportsManifest({
    importMode: "src",
    cwd: fileURLToPath(import.meta.url),
  });

  expect(manifest.exports).toEqual({
    ".": {
      expandHexRange: "function",
      fromHexToCodepoint: "function",
      getBoundaryLineStyle: "function",
      getCurrentDraftVersion: "function",
      getPropertyValue: "function",
      hasUCDFolderPath: "function",
      inferFileName: "function",
      inferVersion: "function",
      isBoundaryLine: "function",
      isCommentLine: "function",
      isDashBoundary: "function",
      isEmptyLine: "function",
      isEOFMarker: "function",
      isEqualsBoundary: "function",
      isHashBoundary: "function",
      isLineWithData: "function",
      isMissingAnnotation: "function",
      isPropertyLine: "function",
      parseFileNameLine: "function",
      parseMissingAnnotation: "function",
      RawDataFile: "function",
      resolveUCDVersion: "function",
      stripHex: "function",
      trimCommentLine: "function",
      UNICODE_DRAFT_VERSION: "string",
      UNICODE_STABLE_VERSION: "string",
      UNICODE_TO_UCD_VERSION_MAPPINGS: "object",
      UNICODE_VERSION_METADATA: "object",
      buildUCDPath: "function",
    },
    "./constants": {
      UNICODE_DRAFT_VERSION: "string",
      UNICODE_STABLE_VERSION: "string",
      UNICODE_VERSION_METADATA: "object",
    },
    "./datafile": {
      NodeTypes: "object",
      RawDataFile: "function",
      astUtils: "object",
      hasSections: "function",
      isBoundaryNode: "function",
      isCommentNode: "function",
      isEmptyCommentNode: "function",
      isDataNode: "function",
      isEOFNode: "function",
      isEmptyNode: "function",
      isNode: "function",
      isPropertyNode: "function",
      isRootNode: "function",
      isUnknownNode: "function",
      parseSections: "function",
    },
    "./line-helpers": {
      getBoundaryLineStyle: "function",
      getPropertyValue: "function",
      inferFileName: "function",
      inferVersion: "function",
      isBoundaryLine: "function",
      isCommentLine: "function",
      isDashBoundary: "function",
      isEmptyLine: "function",
      isEOFMarker: "function",
      isEqualsBoundary: "function",
      isHashBoundary: "function",
      isLineWithData: "function",
      isMissingAnnotation: "function",
      isPropertyLine: "function",
      parseFileNameLine: "function",
      parseMissingAnnotation: "function",
      trimCommentLine: "function",
    },
  });
});
