import { existsSync, readdirSync, readFileSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import path, { join } from "node:path";

import { parseDataFileIntoAst } from "../packages/parser/src/parser";
import { inferHeaderFromAst } from "../packages/parser/src/header";

const COMMENT = `\
/**
 * This file is auto-generated by scripts/generate-header-tests.ts
 * Do not edit it manually.
 * To regenerate, run:
 *  pnpm tsx scripts/generate-header-tests.ts
 */`;

const UCD_FILES_DIR = join(process.cwd(), "ucd-files");
const TEST_OUTPUT_DIR = join(process.cwd(), "packages/parser/test/headers/generated");

function readFilesRecursive(dir: string): string[] {
  const entries = readdirSync(dir, { withFileTypes: true });

  const files = entries
    .filter((entry) => !entry.isDirectory() && entry.name.endsWith(".txt") && !entry.name.endsWith(".comments.txt"))
    .map((entry) => join(dir, entry.name));

  const folders = entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => join(dir, entry.name));

  return [...files, ...folders.flatMap((folder) => readFilesRecursive(folder))];
}

function trimVersionString(version: string): string {
  return version
    .replace(/^v/, "")
    .replace(/(\.0+)+$/, "")
    .replace(/^0+(\d)/, "$1");
}

async function run() {
  const versions = readdirSync(UCD_FILES_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .toSorted();

  if (versions.length === 0) {
    throw new Error("No version directories found in ucd-files");
  }

  // Ensure output directory exists
  if (!existsSync(TEST_OUTPUT_DIR)) {
    const { mkdir } = await import("node:fs/promises");
    await mkdir(TEST_OUTPUT_DIR, { recursive: true });
  }

  const promises = versions.map(async (version) => {
    const versionDir = join(UCD_FILES_DIR, version);
    const formattedVersion = trimVersionString(version);
    const files = readFilesRecursive(versionDir);

    // Group files by subdirectory
    const grouped = files.reduce<Record<string, string[]>>((acc, filePath) => {
      const relativePath = filePath.replace(`${versionDir}/`, "");
      const dirPath = path.parse(relativePath).dir;

      if (!acc[dirPath]) {
        acc[dirPath] = [];
      }
      acc[dirPath].push(relativePath);
      return acc;
    }, {});

    // Generate .comments.txt files
    for (const filePaths of Object.values(grouped)) {
      for (const relativePath of filePaths) {
        const fullPath = join(versionDir, relativePath);
        const commentsPath = fullPath.replace(/\.txt$/, ".comments.txt");

        const content = readFileSync(fullPath, "utf-8");
        const ast = parseDataFileIntoAst(content);
        const header = inferHeaderFromAst(ast);

        await writeFile(commentsPath, header.text, "utf-8");
      }
    }

    // Generate test file
    const testCases = Object.entries(grouped)
      .map(([dirPath, filePaths]) => {
        const dirSegments = dirPath.split("/").filter(Boolean);

        const tests = filePaths
          .map((relativePath) => {
            return `  ucdTest("${relativePath}")(({ header, expectedText }) => {
    expect(header.text).toBe(expectedText);
  });`;
          })
          .join("\n\n");

        if (dirSegments.length === 0) {
          return tests;
        }

        return dirSegments.reduceRight((content, segment) => {
          return `  describe("${segment}", () => {
${content}
  });`;
        }, tests);
      })
      .join("\n\n");

    const content = `${COMMENT}
import { describe, expect } from "vitest";

import { createUcdTest } from "../__utils";

const ucdTest = createUcdTest("${version}");

describe("inferHeaderFromAst - ${formattedVersion}", () => {
${testCases}
});
`;

    const testFilePath = join(TEST_OUTPUT_DIR, `heading-${formattedVersion}.test.ts`);
    await writeFile(testFilePath, content, "utf-8");
    console.log(`Generated: heading-${formattedVersion}.test.ts (${files.length} files)`);
  });

  await Promise.all(promises);
  console.log("Done.");
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
