/* eslint-disable node/prefer-global/process */
import { existsSync, readdirSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import path, { join } from "node:path";

const COMMENT = `/**
 * This file is auto-generated by scripts/generate-infer-test-files.ts
 * Do not edit it manually.
 * To regenerate, run the script with:
 *  pnpm run generate:infer-test-files
 */`;

async function run() {
  const ucdFilesDir = join(process.cwd(), "ucd-files");

  // read ucd-files for versions
  const versions = readdirSync(ucdFilesDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);

  if (versions.length === 0) {
    throw new Error("No version directories found in ucd-files");
  }

  const promises = versions.map(async (version) => {
    const versionDir = join(ucdFilesDir, version);

    if (!existsSync(versionDir)) {
      throw new Error(`Version directory does not exist: ${versionDir}`);
    }

    function readFiles(dir: string): string[] {
      const entries = readdirSync(dir, { withFileTypes: true });

      const files = entries
        .filter((entry) => !entry.isDirectory())
        .map((entry) => join(dir, entry.name));

      const folders = entries
        .filter((entry) => entry.isDirectory())
        .map((entry) => join(dir, entry.name));

      const subFiles = folders.flatMap((folder) => readFiles(folder));

      return [...files, ...subFiles];
    }

    function trimVersionString(version: string): string {
      // remove trailing zeros and dots
      const trimmed = version.replace(/(\.0+)+$/, "").replace(/\.0+$/, "");
      // remove leading zeros
      return trimmed.replace(/^0+(\d)/, "$1");
    }

    const formattedVersion = trimVersionString(version);

    const files = readFiles(versionDir);

    const content = `${COMMENT}
import { describe, expect, it } from "vitest";
import { parseDataFileIntoAst } from "../../../src/datafile/parser";
import { inferHeadingFromAST } from "../../../src/inference/heading";
import { mapUCDFiles } from "../../__utils";

const ucdFiles = await mapUCDFiles("${version}");

describe("heading inference ${formattedVersion}", async () => {
  ${Object.entries(
    files
      .filter((file) => !file.endsWith(".comments.txt"))
      .reduce(
        (acc, filePath) => {
          const fileName = filePath.replace(`${versionDir}/`, "");
          const parsed = path.parse(fileName);
          const dirPath = parsed.dir;

          if (!acc[dirPath]) {
            acc[dirPath] = [];
          }
          acc[dirPath].push(fileName);
          return acc;
        },
        {} as Record<string, string[]>,
      ),
  )
    .map(([dirPath, fileNames]) => {
      // split directory path into segments for nested describes
      const dirSegments = dirPath.split("/").filter(Boolean);

      if (dirSegments.length === 0) {
        // for root level files
        return fileNames
          .map((fileName, idx) => {
            const parsed = path.parse(fileName);
            return `${idx === 0 ? "" : "  "}it("inferHeadingFromAST(${fileName})", () => {
    const content = ucdFiles.file("${fileName}");
    const expected = ucdFiles.expected("${parsed.name}.comments.txt");
    const ast = parseDataFileIntoAst(content);

    expect(inferHeadingFromAST(ast)).toBe(expected);
  });`;
          })
          .join("\n\n");
      }

      // create test cases for files in this directory
      const testContent = fileNames
        .map((fileName) => {
          const parsed = path.parse(fileName);
          return `    it("inferHeadingFromAST(${parsed.base})", () => {
      const content = ucdFiles.file("${fileName}");
      const expected = ucdFiles.expected("${fileName.replace(".txt", ".comments.txt")}");
      const ast = parseDataFileIntoAst(content);

      expect(inferHeadingFromAST(ast)).toBe(expected);
    });`;
        })
        .join("\n\n");

      // wrap in describe blocks for each directory level
      return dirSegments.reduceRight((content, segment) => {
        return `describe("${segment}", () => {
${content}
  });`;
      }, testContent);
    })
    .join("\n\n  ")}

  it("ensure that all files have been tested", () => {
    expect(ucdFiles.files).toEqual([]);
    expect(ucdFiles.files.length).toBe(0);
  });
});\n`;

    const outputPath = join(
      process.cwd(),
      "packages/parser/test/inference/generated",
      `heading-${formattedVersion}.test.ts`,
    );
    console.log(`Test file generated: heading-${formattedVersion}.test.ts`);
    writeFile(outputPath, content, "utf-8");
  });

  await Promise.all(promises);
  console.log("All test files generated successfully.");
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
