name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  ci:
    uses: luxass/shared-workflows/.github/workflows/ci.yaml@554e26b2e40b5deab8185f0f1f0259ac1b33c252 # v0.2.0
    with:
      fmt: true
      fmt-script: "fmt:check"

  test:
    uses: luxass/shared-workflows/.github/workflows/test.yaml@554e26b2e40b5deab8185f0f1f0259ac1b33c252 # v0.2.0

