name: Check Unicode Releases

on:
  schedule:
    - cron: "0 0 * * *" # run daily
  workflow_dispatch: # allow manual triggers

jobs:
  check-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Unicode Releases
        uses: luxass/unicode-releases-action@v0.2.0
        id: unicode
      - name: Use Release Information
        run: |
          echo "Latest Release: ${{ steps.unicode.outputs.latest_release }}"
          echo "All Releases: ${{ steps.unicode.outputs.all_releases }}"
          echo "Current Draft: ${{ steps.unicode.outputs.current_draft }}"
